### ISSUE TITLE
Massive integration test failures

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-dotnet-instrumentation#1009]
Examples:

- https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/actions/runs/2755073455
- https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/actions/runs/2755126398
- https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/actions/runs/2749693766

**Comment by Kielek** [comment]
Temporary issue. Closing.
