### ISSUE TITLE
Cannot run examples (./run-example.sh)

### ISSUE THREAD

**Issue by faisalcse98a** [open-telemetry/opentelemetry-dotnet-instrumentation#1010]
# Bug Report

## Symptom

**Describe the bug**
When I am running ./run-example.sh at the repository root, the execution finishes with the following error "/cygdrive/d/repo/opentelemetry-dotnet-instrumentation/dev/envvars.sh: line 26: pwd: -W: invalid option" (also see Screenshot 1). Then I attempted to remove "-W" from envvars.sh and run ./run-example.sh again. How, the execution finishes with the following error "Unhandled exception. System.ArgumentException: The startup hook simple assembly name '/cygdrive/d/repo/opentelemetry-dotnet-instrumentation/bin/tracer-home/netcoreapp3.1/OpenTelemetry.AutoInstrumentation.Startup
Hook.dll' is invalid. It must be a valid assembly name and it may not contain directory separator, space or comma characters and must not end with '.dll'." (also see Screenshot 2).

I am using Windows operating system. Hence, I am running the command from cygwin.

**Expected behavior**
./run-example.sh should finish with success.

**Screenshots**
Screenshot 1
![image](https://user-images.githubusercontent.com/110192003/181599898-756613d0-ab2e-45b7-b775-af2980474471.png)

Screenshot 2
![image](https://user-images.githubusercontent.com/110192003/181600417-ecb45166-5577-41b3-9aa8-a0a8200ceec9.png)

**Runtime environment (please complete the following information):**

- OpenTelemetry Automatic Instrumentation version: [e.g. 1.0.0]
- OS: [e.g. Windows Server 2012 R2 ]
- .NET version: [e.g. .NET Framework 4.6.2, .NET Core 2.1]

**Additional context**
None

## Reproduce

 1. Go to repository root.
 2. Run ./run-example.sh => results in Screetshot 1
 3. Replace "pwd -W" with "pwd" at envvars.sh.
 4. Run ./run-example.sh => results in Screenshot 2

<!--
NOTE: If possible, also include the tracer log files found (by default) in:
Windows: `%ProgramData%\OpenTelemetry .NET AutoInstrumentation\logs\`
Linux: /var/log/opentelemetry/dotnet/
--!>

**Comment by pellared** [comment]
It is designed to work on Git Bash in Windows. Can you try it instead of cygwin?

**Comment by faisalcse98a** [comment]
> It is designed to work with Git Bash on Windows. Can you try it instead of cygwin?

Thanks. It solves the issue.
