### ISSUE TITLE
Remove DDSpanContextPropagator

### ISSUE THREAD

**Issue by iNikem** [open-telemetry/opentelemetry-dotnet-instrumentation#106]
[OpenTelemetry spec says](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/context/api-propagators.md#propagators-distribution):

> Additional Propagators implementing vendor-specific protocols such as AWS X-Ray trace header protocol MUST NOT be maintained or distributed as part of the Core OpenTelemetry repositories.

As this repo qualifies as "Core OpenTelemetry repository" (correct me if I am wrong), it must not contain vendor-specific propagators.

**Comment by macrogreg** [comment]
Thanks for pointing this out.
This will be a relevant topic when we get to GA and we have OTel-usage.

For now this is not a priority for scheduling and architectural reasons.

**Comment by pellared** [comment]
No longer valid.
