### ISSUE TITLE
Implement or remove OTEL_DOTNET_AUTO_TRACES_ENABLED

### ISSUE THREAD

**Issue by pjanotti** [open-telemetry/opentelemetry-dotnet-instrumentation#1080]
`OTEL_DOTNET_AUTO_TRACES_ENABLED` was incorrectly disabling the CLR profiler. After that is [fixed](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/1082) there is still a config key for this variable, however, the key is not used. Either it should be removed or implemented.

**Comment by Kielek** [comment]
SIG meeting: remove it for now, we can bring it back when needed.
