### ISSUE TITLE
Consider if OTLP settings should be separate per signal

### ISSUE THREAD

**Issue by pjanotti** [open-telemetry/opentelemetry-dotnet-instrumentation#1083]
This came up in a PR, see [comment here](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/708/files#r886378692). This issue is to track decide if we really want to do it or not.

**Comment by Kielek** [comment]
SIG meetings, postpone to 1.0.0-rc

**Comment by Kielek** [comment]
We can expect some changes on the SDK level. Probably 1.5.0 or later.

**Comment by Kielek** [comment]
Fixed by #3527
