### ISSUE TITLE
Use C# build automation tool

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-dotnet-instrumentation#109]
## Why

Currently, the build pipeline is tightly coupled to Azure Pipelines which makes it very hard to run the build in the local environment.

## What

Migrate the build pipeline to use https://github.com/adamralph/bullseye with https://github.com/adamralph/simple-exec or https://nuke.build/.

**Comment by macrogreg** [comment]
@andrewlock is working on this on the Datadog side.

making @zacharycmontoya the owner just to keep this racking item up to date.

**Comment by zacharycmontoya** [comment]
PR introduced in Datadog repo: https://github.com/DataDog/dd-trace-dotnet/pull/1476

This will likely require further iteration

**Comment by zacharycmontoya** [comment]
The initial PR has been merged: https://github.com/DataDog/dd-trace-dotnet/pull/1476

**Comment by pellared** [comment]
Done.
