### ISSUE TITLE
Support for OTEL_TRACES_SAMPLER and OTEL_TRACES_SAMPLER_ARG

### ISSUE THREAD

**Issue by Kielek** [open-telemetry/opentelemetry-dotnet-instrumentation#1091]
# Feature Request

**Are you requesting automatic instrumentation for a framework or library? Please describe.**

Add support for `OTEL_TRACES_SAMPLER` and `OTEL_TRACES_SAMPLER_ARG` per specification: 
https://github.com/open-telemetry/opentelemetry-specification/blob/6ce62202e5407518e19c56c445c13682ef51a51d/specification/sdk-environment-variables.md?plain=1#L46

**Describe the solution you'd like**
I think that it should be implemented on the OTel SDK side. All (most?) samplers are provided there.

**Describe alternatives you've considered**
Implement it on Automatic Instrumentation side. It can be proffered way if there will be no possibility to cover all sampler types on Sdk side.

**Additional context**
Follow up to #1087.

**Comment by anneelisabethlelievre** [comment]
Hello @Kielek, do you know when this issue will be addressed, in which milestone ?

**Comment by pellared** [comment]
@anneelisabethlelievre You can also ask here: https://github.com/open-telemetry/opentelemetry-dotnet/issues/3601. We cannot say when it will be addressed.

**Comment by Kielek** [comment]
@anneelisabethlelievre, it will be supported by Auto Instrumentation in the next release - or you can try to use current main branch to build and use it.

We do not know when OTel SDK will have such support.
