### ISSUE TITLE
Add bytecode instrumentation for WCF .NET Core Client integration

### ISSUE THREAD

**Issue by dszmigielski** [open-telemetry/opentelemetry-dotnet-instrumentation#1143]
WCF integration for .NET Core Client can be simplified for users by adding bytecode instrumentation. See the below comment:

https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/1125#discussion_r953885710

**Comment by pellared** [comment]
I think this can be postponed as we have a documented way to enable it and nobody complains so far.

**Comment by pjanotti** [comment]
Per SIG: look also at context propagation.

**Comment by Kielek** [comment]
Fixed by #2876
