### ISSUE TITLE
Introduce OTEL_DOTNET_AUTO_PLUGINS

### ISSUE THREAD

**Issue by rajkumar-rangaraj** [open-telemetry/opentelemetry-dotnet-instrumentation#1149]
Replace `OTEL_DOTNET_AUTO_TRACES_PLUGIN`, `OTEL_DOTNET_AUTO_METRICS_PLUGINS` and `OTEL_DOTNET_AUTO_LOGS_PLUGINS` with one environment variable `OTEL_DOTNET_AUTO_PLUGINS`. This will help maintain less environment variables and makes it easier for user to integrate.

**Comment by Kielek** [comment]
We have made changes in opposite direction some time ago. I think that we have time to reintroduce it when needed. Droping will be harder part. Please check: #420

**Comment by pellared** [comment]
See: https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/issues/420#issuecomment-1088050411

> The plugins environment variable could be the exception. I think that most people wouldn't want to package their custom plugins separately based on signal (trace, metrics, and logs) type.

**Comment by rajkumar-rangaraj** [comment]
> See: [#420 (comment)](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/issues/420#issuecomment-1088050411) by @nrcventura
> 
> > The plugins environment variable could be the exception. I think that most people wouldn't want to package their custom plugins separately based on signal (trace, metrics, and logs) type.

Yes. For the same reason created this issue. There are no reasons for users to have plugins in different package. 
As @nrcventura mentioned here https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/issues/420#issuecomment-1088050411,  I feel that we have reached a state where we need to combine plugins for all three signals.

**Comment by Kielek** [comment]
SIG meeting: Lets create one env. variable to load but have separate _interfaces_ to load plugins based on the type.
Old env. variables should be removed.
