### ISSUE TITLE
Configuration source binding & validation

### ISSUE THREAD

**Issue by RassK** [open-telemetry/opentelemetry-dotnet-instrumentation#115]
### **Why**
Currently some of the configuration source values will be validated late at runtime. We should NOT throw invalid configuration exceptions later than initialization. In same time some of the configuration values will fallback to the default value when invalid value is passed (for eg: enums) - this could lead to confusion for user and also internally (the other part of the system does not know the actual behavior due setting value and behavior differs).

### **What**
- Settings instance should be read only after initialization
- All settings should be validated in early startup so we can fail fast.
- All defaults should be set in early startup

Open for ideas to implement validators. Example:
**Using property attributes** 

```
class MySettings : IAppSettings
{
   [Configuration(ConfigurationKeys.DebugEnabled, default: false)]
   public bool DebugEnabled { get; private set; }

   [Configuration(ConfigurationKeys.MyEnum)]
   [ConfigurationValidator(typeof(EnumValidator))]
   public MyEnum { get; private set; }
}
```

pros:
- easy to read

cons:
- requires some reflection (slow but done only once)

**UPD 2023: Consider using fluent style, so no reflection is needed and readability remains** 

### **Example issues**
- https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/102#pullrequestreview-628734402
- https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/104#pullrequestreview-629247977
- https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/104#pullrequestreview-629248164

### **Current implementations**
- TracerSettings
- IntegrationSettings
- GlobalSettings

**Comment by macrogreg** [comment]
This may require significant re-architecture / refactoring.
May be related to changed needed for https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/issues/116
Also may be related to https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/issues/133
Not required for Betra release.

**Comment by Kielek** [comment]
Discussed with @RassK we can postopone after 1.0.0.

**Comment by RassK** [comment]
Closing, mostly done but differently.
