### ISSUE TITLE
Testing - Support for different versions of libraries 

### ISSUE THREAD

**Issue by Kielek** [open-telemetry/opentelemetry-dotnet-instrumentation#1213]
# Feature Request

**Are you requesting automatic instrumentation for a framework or library? Please describe.**

We need a way to execute our pipeline with different versions of libraries.
For example, we should execute `StackExchange.Redis` tests with at least 4 different versions. To fully cover all cases. See https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/4ac185f24b92e8c6515b7a0ae8546441df43b353/src/OpenTelemetry.AutoInstrumentation/Instrumentations/StackExchangeRedis/StackExchangeRedisIntegration.cs#L27-L54

**Describe the solution you'd like**
TBD

**Describe alternatives you've considered**
TBD

**Additional Context**
Discussion started at https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/1171

**Comment by pellared** [comment]
I think it would be easier if the integration test would build and run the instrumented application. What I mean is that I would move the code that builds the test application from Nuke target to the integration tests.

**Comment by Kielek** [comment]
Leftovers from https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/2241#pullrequestreview-1310937584

Asp.NET MVS - separate issue created #2245
HttpClient - only the latest release for .NET Fx is not deprecated. Nothing to extend for now.

Closing.
