### ISSUE TITLE
Add support for MassTransit instrumentation

### ISSUE THREAD

**Issue by nrcventura** [open-telemetry/opentelemetry-dotnet-instrumentation#1215]
# Feature Request

**Are you requesting automatic instrumentation for a framework or library? Please describe.**

There is an [instrumentation library available for MassTransit](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/tree/main/src/OpenTelemetry.Instrumentation.MassTransit). We should add support for this library.

**Is your feature request related to a problem? Please describe.**
No, but it would be good to expand our support for message queuing systems so we can get some feedback for those types of applications.

**Describe the solution you'd like**
When someone is using a supported version of MassTransit we should automatically collect telemetry data for that library.

**Describe alternatives you've considered**
Leveraging bytecode instrumentation, but it should be simpler to leverage the existing instrumentation library.

**Additional context**
None

**Comment by Kielek** [comment]
Worth to verify if we need changes from https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/667
