### ISSUE TITLE
Native code is not creating full log path on Linux

### ISSUE THREAD

**Issue by Kielek** [open-telemetry/opentelemetry-dotnet-instrumentation#1218]
# Bug Report

## Symptom

**Describe the bug**
Enable Auto Instrumentation on Linux where there is no `opentelemetry` folder under `/var/log/`.
(At least two folder have to be created to be able to crate folder under `/var/log/opentelemetry/dotnet/`).
Fist time execute instrumentation.
There will be no native-logs.

**Expected behavior**
Whole folder structure is created, as for managed code.

**Runtime environment (please complete the following information):**

Docker file based on `FROM mcr.microsoft.com/dotnet/aspnet:6.0`

**Additional context**
Managed logs are created.

There is a different way to create folders under Windows/non-Windows
https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/10f7d805950a3a3930751395d5db00315261fc9d/src/OpenTelemetry.AutoInstrumentation.Native/logging.cpp#L32-L51
and https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/5812eda2bc8f80f7b2cc6ab1afbfccc45c8b387d/src/OpenTelemetry.AutoInstrumentation.Native/logger_impl.h#L84-L106

Based on https://stackoverflow.com/a/68913206 it should be fine to use Windows version both for Windows and non-Windows.

**Comment by pellared** [comment]
I just want to let know that it is a "known" issue that is currently "handled" via:

https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/c3ab16995535536aae1e1d3886fe2546590ae9e9/docs/README.md?plain=1#L97-L103

**Comment by Kielek** [comment]
Found while working on https://github.com/open-telemetry/opentelemetry-operator/pull/1081.
Instrumentation is working, but there is not log files for native code by default for pods with enabled operator.
