### ISSUE TITLE
Better log file names

### ISSUE THREAD

**Issue by Kielek** [open-telemetry/opentelemetry-dotnet-instrumentation#1225]
# Feature Request

**Are you requesting automatic instrumentation for a framework or library? Please describe.**

Better name for log files.

For now, log files looks like
```
root@redis-deployment-5f4744b9b6-vjs9l:/var/log/opentelemetry/dotnet# ls -l
total 52
-rw-r--r-- 1 root root    71 Sep 14 07:49 dotnet-tracer-loader-TestApplication.StackExchangeRedis-1.log
-rw-r--r-- 1 root root   229 Sep 14 07:49 dotnet-tracer-managed-TestApplication.StackExchangeRedis-1.log
-rw-r--r-- 1 root root 44487 Sep 14 07:50 dotnet-tracer-native-dotnet-1.log
```

Auto Instrumentation is more than tracer.

**Is your feature request related to a problem? Please describe.**
File names could be misleading.

**Describe the solution you'd like**
The prefix should be changed from `dotnet-tracer-` to `otel-dotnet-auto-`.

**Describe alternatives you've considered**
The prefix should be changed from `dotnet-tracer-` to `dotnet-autoinstrumentation-` or `dotnet-intrumentation-`.

**Comment by pellared** [comment]
I propose `otel-dotnet-auto-` prefix (like our env vars)

**Comment by Kielek** [comment]
> I propose `otel-dotnet-auto-` prefix (like our env vars)

Description updated.
