### ISSUE TITLE
Convenient installation scripts: add support for getting the latest version

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-dotnet-instrumentation#1250]
See: https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/1243/files#r974593778

**Comment by RassK** [comment]
@pellared if not done, might need rephrasing what else is missing / expected.

**Comment by pellared** [comment]
I think we just might want to add to the docs that if the user would like to have a script that always installs the latest release then he should use one of the following URLs:

- `https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/releases/download/latest/otel-dotnet-auto-install.sh`
- `https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/releases/download/latest/otel-dotnet-auto-install.sh`

But I would discourage doing so as newer version may e.g. drop support for legacy .NET versions or have breaking changes (especially now before we go stable, but even afterwards it can break once we release `v2`).

Alternatively we can close this issue if we prefer just to have the current recommendation (my preference).

_Removing the milestone so that we can discuss it during SIG meeting._
