### ISSUE TITLE
Flaky test: IntegrationTests.SmokeTests.PrometheusExporter

### ISSUE THREAD

**Issue by pjanotti** [open-telemetry/opentelemetry-dotnet-instrumentation#1260]
The IntegrationTests.SmokeTests.PrometheusExporter test fails frequently without any metrics captured, see https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/actions/runs/3100807847/jobs/5021491754#step:4:3423 for instance.

Another issue related to the same test was recently fixed via #1259

**Comment by pellared** [comment]
This is reproducible via `verify-test` GH workflow. E.g.:

- https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/actions/runs/3103075971
- https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/actions/runs/3103076002

I am going to try to increase the timeout and see what happens.
