### ISSUE TITLE
Add env var to control cache timeout in Prometheus exporter

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-dotnet-instrumentation#1266]
Alternative approach, can we reduce cache timeout in Prometheus? In never version, it is set to `300` ms for AspNetCore, and probably, by mistake to no cache on HttpListener. See https://github.com/open-telemetry/opentelemetry-dotnet/issues/3679#issuecomment-1252172029

_Originally posted by @Kielek in https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/issues/1263#issuecomment-1254666849_

**Comment by Kielek** [comment]
HttpListener exporter has disabled cache and marked as dev. only. Closing.
