### ISSUE TITLE
Default Log Level for collection

### ISSUE THREAD

**Issue by rajkumar-rangaraj** [open-telemetry/opentelemetry-dotnet-instrumentation#1268]
# Feature Request

**Describe the solution you'd like**

Auto-Instrumentation collects all log levels. Collecting informational logs by default could be lot of it. We should collect log level warning and above by default. 

Introduce `OTEL_DOTNET_AUTO_LOGS_LEVEL` to control this behavior.

**Comment by Kielek** [comment]
Closing per SIG discussion.
