### ISSUE TITLE
Unsafe reference: System.Runtime.CompilerServices.Unsafe

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-dotnet-instrumentation#127]
See: https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/68d5b3775ca55eeff28e2fe5da04ae9bf3fafe36/src/Datadog.Trace/Datadog.Trace.csproj#L28

What will happen if the instrumented code would reference e.g. 5.0.0 or some version that will be incompatible?

I guess it can lead to a runtime exception.

Can anyone confirm my assumptions?

**Comment by zacharycmontoya** [comment]
This is one specific issue we faced: https://github.com/DataDog/dd-trace-dotnet/issues/771

Since this class of issue has not happened in some time, I don't have a great explanation for you at the top of my head on the exact scenario and the runtime decisions that cause the issue.

**Comment by lucaspimentel** [comment]
Version 4.5.1 of this package includes binaries for `netcoreapp2.0`, `netstandard1.0`, and `netstandard2.0`, but this project targets `net45` and `net461` which are not compatible.

If `Unsafe` is only used in .NET Core, you should probably add a condition to this `PackageReference` or move it into a different `ItemGroup`, like this one: https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/68d5b3775ca55eeff28e2fe5da04ae9bf3fafe36/src/Datadog.Trace/Datadog.Trace.csproj#L17

You probably also want to deploy `System.Runtime.CompilerServices.Unsafe.dll` with the installer packages.

There are other issues in .NET Framework (like strict assembly binding or referencing `netstandard2.0` from projects that target .NET Framework 4.7.1 or below), but I don't think they apply here.

**Comment by pellared** [comment]
> This is one specific issue we faced: [DataDog/dd-trace-dotnet#771](https://github.com/DataDog/dd-trace-dotnet/issues/771)
> 
> Since this class of issue has not happened in some time, I don't have a great explanation for you at the top of my head on the exact scenario and the runtime decisions that cause the issue.

@zacharycmontoya 
Maybe you have removed this reference? 😉 
Compare: https://github.com/DataDog/dd-trace-dotnet/search?l=XML&q=Unsafe&type=code to https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/search?l=XML&q=Unsafe

**Comment by zacharycmontoya** [comment]
Yes, in the `dd-trace-dotnet` repo we definitely removed the `System.Runtime.CompilerServices.Unsafe` package reference. It was recently reintroduced in this repo in this PR: https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/72
