### ISSUE TITLE
Remove OTEL_DOTNET_AUTO_LOGS_PARSE_STATE_VALUES

### ISSUE THREAD

**Issue by rajkumar-rangaraj** [open-telemetry/opentelemetry-dotnet-instrumentation#1273]
# Feature Request

**Is your feature request related to a problem? Please describe.**
OpenTelemetry Collector does not parse the logs when `OTEL_DOTNET_AUTO_LOGS_PARSE_STATE_VALUES` and `OTEL_DOTNET_AUTO_LOGS_INCLUDE_FORMATTED_MESSAGE` are set to `false`.

**Describe the solution you'd like**
Set the default value for  `OTEL_DOTNET_AUTO_LOGS_PARSE_STATE_VALUES` and `OTEL_DOTNET_AUTO_LOGS_INCLUDE_FORMATTED_MESSAGE` to `true` so that Collector will get a formatted logs.

**Comment by pellared** [comment]
Do you know why `false` are default im the SDK?

**Comment by rajkumar-rangaraj** [comment]
`OtlpLogExporter` sets `ParseStateValues` to `true` by default. Ref: https://github.com/open-telemetry/opentelemetry-dotnet/blob/86ee906dcd02c562e85814ca07f2a1a15a83dc98/src/OpenTelemetry.Exporter.OpenTelemetryProtocol.Logs/OtlpLogExporterHelperExtensions.cs#L70

We should remove environment variable `OTEL_DOTNET_AUTO_LOGS_PARSE_STATE_VALUES`. Due to ordering issues in builder parse state settings are honored in auto-instrumentation. This needs a fix.

`OTEL_DOTNET_AUTO_LOGS_INCLUDE_FORMATTED_MESSAGE` default it to false for the reason explained in the issue https://github.com/open-telemetry/opentelemetry-dotnet/issues/2042.

Key takeaway based on this research is to remove environment variable `OTEL_DOTNET_AUTO_LOGS_PARSE_STATE_VALUES` and continue the existing behavior of setting false as default value for `OTEL_DOTNET_AUTO_LOGS_INCLUDE_FORMATTED_MESSAGE `
