### ISSUE TITLE
Null Pointer Exception when using bytecode instrumentation

### ISSUE THREAD

**Issue by muhaook** [open-telemetry/opentelemetry-dotnet-instrumentation#1282]
# Bug Report

## Symptom

**Describe the bug**

I am implementing our own bytecode instrumentation and sometimes hit NPE:

```
[2022-09-27T13:52:14.9181394Z] [Error] Object reference not set to an instance of an object. 
Exception: Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at OpenTelemetry.AutoInstrumentation.Util.ActivityHelper.StartActivityWithTags(ActivitySource activitySource, String operationName, ActivityKind kind, ITags tags)
   at OpenTelemetry.AutoInstrumentation.Instrumentations.Odp.OdpCommon.OnMethodBeginConnection[TTarget](TTarget instance, String spanNamePrefix)
   at OdpOpenConnectionIntegration.OnMethodBegin(OracleConnection )
   at OpenTelemetry.AutoInstrumentation.CallTarget.Handlers.BeginMethodHandler`2.Invoke(TTarget instance)
   at OpenTelemetry.AutoInstrumentation.CallTarget.CallTargetInvoker.BeginMethod[TIntegration,TTarget](TTarget instance)
   at Oracle.ManagedDataAccess.Client.OracleConnection.Open()
```

Looked into source code and I found [this line](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/de45afdb36733468fa2e78a7ba7197d54abc0c73/src/OpenTelemetry.AutoInstrumentation/Util/ActivityHelper.cs#L42) . It is possible that activitySource.StartActivity() returns null. So we'd better check for it in [the following logic](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/de45afdb36733468fa2e78a7ba7197d54abc0c73/src/OpenTelemetry.AutoInstrumentation/Util/ActivityHelper.cs#L49).

**Runtime environment:**

- OpenTelemetry Automatic Instrumentation version: 0.3.1
- OS: Windows 10
- .NET version: .NET Framework 4.6.2

**Comment by RassK** [comment]
@muhaook The ActivitySource.StartActivity() returns null if there is no listener. The null check is going to hide the actual problem.

**Comment by muhaook** [comment]
BTW, I did not get notified by email whenever I got @-ed or my git issue had new comment. Does anyone know how to subscribe for that? Thanks

**Comment by pellared** [comment]
> BTW, I did not get notified by email whenever I got @-ed or my git issue had new comment. Does anyone know how to subscribe for that? Thanks

@muhaook  Check the following:

1. `Settings` -> `Email notifications`. PS. Maybe you use some email for spams 😉 
2. Check the `Watch` settings on this repo. You should at least have `Participating and @mentions`
3. Check if are "Subscribed" to this issue (search for `Notifications`).

**Comment by muhaook** [comment]
Thanks @pellared , I figured it out just now :)

**Comment by RassK** [comment]
I just noticed we also miss some disabled checks. Probably have to double check.

Just found one good example: 
`Instrumentation.TracerSettings.EnabledInstrumentations.Contains(TracerInstrumentation.StackExchangeRedis)`
https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/main/src/OpenTelemetry.AutoInstrumentation/Instrumentations/StackExchangeRedis/StackExchangeRedisInitializer.cs#L28

> I do not quite understand what you said 2. Startup disables the specific instrumentation. Ideally, OnMethodBegin() won't get invoked if no listener exists. But it seems not straight forward to have

I mean if you still have the components but you decide to disable the specific instrumentation. So IL rewrite probably happens but there will be no listeners.
https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/main/docs/config.md#instrumentations
See for example `OTEL_DOTNET_AUTO_TRACES_ENABLED_INSTRUMENTATIONS` and `OTEL_DOTNET_AUTO_TRACES_DISABLED_INSTRUMENTATIONS`

**Comment by RassK** [comment]
Update:
It may be actually bug. 
Managed layer implements `OTEL_DOTNET_AUTO_TRACES_ENABLED_INSTRUMENTATIONS` and `OTEL_DOTNET_AUTO_TRACES_DISABLED_INSTRUMENTATIONS`
Native layer is missing `OTEL_DOTNET_AUTO_TRACES_ENABLED_INSTRUMENTATIONS`

Native layer instead has only `OTEL_DOTNET_AUTO_TRACES_DISABLED_INSTRUMENTATIONS`. So when you explicitly don't enable instrumentation, it will be disabled in managed layer... but native layer doesn't know it.

**Comment by pellared** [comment]
Side note (but somehow related): I also do not like that right now (in `main`) `OTEL_DOTNET_AUTO_TRACES_DISABLED_INSTRUMENTATIONS` can be used for disabling `ILogger` bytecode logging instrumentation 😬 

CC @rajkumar-rangaraj
