### ISSUE TITLE
ActivityKind is always 'internal' for bytecode intrumentation

### ISSUE THREAD

**Issue by muhaook** [open-telemetry/opentelemetry-dotnet-instrumentation#1283]
# Bug Report

## Symptom

**Describe the bug**
[activitySource.StartActivity(operationName)](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/de45afdb36733468fa2e78a7ba7197d54abc0c73/src/OpenTelemetry.AutoInstrumentation/Util/ActivityHelper.cs#L42) will use `internal` as default ActivityKind and it can not be changed after activity is started. 

I tried to add tag with ActivityKind = client, it turned out that there will be 2 `kind` tags in the final activity: one is `internal`; the other is `client`.

So suggest to add input argument ActivityKind to [activitySource.StartActivity()](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/de45afdb36733468fa2e78a7ba7197d54abc0c73/src/OpenTelemetry.AutoInstrumentation/Util/ActivityHelper.cs#L42)

**Runtime environment:**

- OpenTelemetry Automatic Instrumentation version: 0.3.1
- OS: Windows 10
- .NET version: .NET Framework 4.6.2

**Comment by pellared** [comment]
Reference https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry.Api/README.md#activity-creation-options
