### ISSUE TITLE
Refactor to use ICorProfilerInfo7

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-dotnet-instrumentation#1288]
I suppose that we can make further cleanup and replace all usages older than `ICorProfilerInfo6`. Especially in `Initialization` method in `cor_profiler.cpp`.

_Originally posted by @Kielek in https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/issues/1285#issuecomment-1260407033_

**Comment by Kielek** [comment]
ICorProfilerInfo7 can be used. It is available since .NET Framework 4.6.1.
