### ISSUE TITLE
Add ILogger instrumentation for non-host console app

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-dotnet-instrumentation#1292]
Add support for "non-host console app" scenario like here: https://learn.microsoft.com/en-us/dotnet/core/extensions/logging?tabs=command-line#non-host-console-app

Possibly it can be achieved by adding bytecode instrumentation.

CC @rajkumar-rangaraj

**Comment by rajkumar-rangaraj** [comment]
ILogger instrumentation for non-host apps are covered as a part of https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/1262.
Should we add another integration tests for console app with ILogger?

**Comment by pellared** [comment]
I created a test like that and it was not working. I can recreate it tomorrow and create a draft PR for you if it helps.

**Comment by Kielek** [comment]
SIG Note: just extend the Smoke test.

**Comment by rajkumar-rangaraj** [comment]
Exception was throw as `Microsoft.Extensions.Logging.Configuration` is missing in Console based app. We might need to add this as a part of additional deps.

System.IO.FileNotFoundException: 'Could not load file or assembly 'Microsoft.Extensions.Logging.Configuration, Version=3.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.'
