### ISSUE TITLE
IntegrationTests on Linux are sometimes hanging

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-dotnet-instrumentation#1296]
- https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/actions/runs/3140353105/jobs/5101662658
- https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/actions/runs/3141964977/jobs/5105009137
- https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/actions/runs/3143906850/jobs/5109224240

It might be connected with changes introduced here: https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/1276

**Comment by pjanotti** [comment]
@pellared I'm not seeing this happening, but, caveat: querying GH actions doesn't get me an automated count. I looked at the last 5 days failures and didn't see this one. I did see some hanging on Windows, many failures of a Prometheus test (most on Linux), and one or another that seem "random". I will open issues for the mentioned failures, unless we have a repro for this one it seems time to close it - we can always reopen if needed.
