### ISSUE TITLE
Common Language Specification (CLS) compliance

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-dotnet-instrumentation#131]
Per: https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/130#discussion_r614738736

For example `ulong` that is used as type for `SpanId`
https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/0916f0a0f5b2b42ccbe5b5f4fc55485fc19e95f5/src/Datadog.Trace/SpanContext.cs#L107 
is not [CLS Compliant](https://docs.microsoft.com/en-us/dotnet/api/system.clscompliantattribute?view=net-5.0).

Is it not an issue?

Shouldn't we add `[assembly: CLSCompliant(true)]` at least to the Tracer assembly?

**Comment by pjanotti** [comment]
CLS Compliance feels a legacy burden without clear payoff to me. They mostly complain about unsigned numbers like in this case and nowadays even VB.NET supports unsigned and F# always supported those. What real language will benefit from that in the dotnet environment?

My first instinct is to check what is the latest in this regard on dotnet/runtime and unless we have a clear scenario/gain for it to not bother with CLS compliance.

**Comment by nrcventura** [comment]
I think that having it be a ulong is fine for now. In `DiagnosticSource`, `Activity.Id` is type `string` and it may make sense for us to do the same in the future.

**Comment by macrogreg** [comment]
@pellared Please document as discussed and close.

**Comment by macrogreg** [comment]
@pellared Please document as discussed and close.

**Comment by pellared** [comment]
Closing per https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/137
