### ISSUE TITLE
Add the possiiblity to disable Microsoft.Extensions.Logging instrumentation when CLR Profiler is enabled

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-dotnet-instrumentation#1310]
I think we should add support for `OTEL_DOTNET_AUTO_LOGS_DISABLED_INSTRUMENTATIONS` and  `OTEL_DOTNET_AUTO_LOGS_ENABLED_INSTRUMENTATIONS`. It would require changes in native code and `integrations.json` to define the "type" of bytecode instrumentation.

The same could be done to enable metrics bytecode instrumentation.

Side note: Is it possible to have two bytecode instrumentations for the same API? So that we can have e.g. separate bytecode GraphQL instrumentation for metrics and spans.

Moreover, I am not sure if `LoggingBuilder` is a good/"unique" name/id. Maybe `MicrosoftExtensionsLogging` or `ILogger`. The second one is not so unique but I think more obvious than `LoggingBuilder`.

Related changes: https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/1324

**EDITED** (kudos for @RassK)

**Comment by pellared** [comment]
CC @rajkumar-rangaraj

**Comment by RassK** [comment]
There's actually no way to disable it.

**Comment by RassK** [comment]
> Right now, the "hack" to disable Microsoft.Extensions.Logging instrumentation when CLR Profiler is enabled is to set OTEL_DOTNET_AUTO_TRACES_DISABLED_INSTRUMENTATIONS=LoggingBuilder.

There is actually no way to disable it. Native layer is fine to have  `LoggingBuilder` in `OTEL_DOTNET_AUTO_TRACES_DISABLED_INSTRUMENTATIONS`  but managed layer crashes with unsupported option, due `TracerInstrumentation` enum does not contain the value.

**Comment by rajkumar-rangaraj** [comment]
> Moreover, I am not sure if LoggingBuilder is a good/"unique" name/id. Maybe MicrosoftExtensionsLogging or ILogger. The second one is not so unique but I think more obvious than LoggingBuilder.

`LoggingBuilder` is an internal implementation, dotnet users know this feature as `ILogger`. Better apt name would be `ILogger`.
