### ISSUE TITLE
Improve env vars internal logging

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-dotnet-instrumentation#1325]
It would be better to log all env vars having the following prefixes:
- `COR_`
- `CORECLR_`
- `DOTNET_`
- `OTEL_`

_Originally posted by @pellared in https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/1324#discussion_r985612360_

**Comment by Kielek** [comment]
Also: CORECLR_
