### ISSUE TITLE
Build failed on Linux: error: invalid value 'c++17' in '-std=c++17'

### ISSUE THREAD

**Issue by muhaook** [open-telemetry/opentelemetry-dotnet-instrumentation#1327]
# Bug Report

## Symptom

**Describe the bug**
Was trying to make a build (running `dotnet nuke`) on Linux, but hit error:
```
09:42:58 [ERR] warning: unknown warning option '-Wno-macro-redefined'; did you mean '-Wno-builtin-macro-redefined'? [-Wunknown-warning-option]
09:42:58 [ERR] warning: unknown warning option '-Wno-pragmas' [-Wunknown-warning-option]
09:42:58 [ERR] error: invalid value 'c++17' in '-std=c++17'
09:42:58 [ERR] make[2]: *** [CMakeFiles/OpenTelemetry.AutoInstrumentation.Native.static.dir/class_factory.cpp.o] Error 1
09:42:58 [ERR] make[1]: *** [CMakeFiles/OpenTelemetry.AutoInstrumentation.Native.static.dir/all] Error 2
09:42:58 [ERR] make: *** [all] Error 2
09:42:58 [ERR] Target CompileNativeSrcLinux has thrown an exception
```
The versions of cmake/clang/clang++
```
$ cmake --version
cmake3 version 3.17.5
CMake suite maintained and supported by Kitware (kitware.com/cmake).

$ clang --version
clang version 3.4.2 (tags/RELEASE_34/dot2-final)
Target: x86_64-redhat-linux-gnu
Thread model: posix

$ clang++ --version
clang version 3.4.2 (tags/RELEASE_34/dot2-final)
Target: x86_64-redhat-linux-gnu
Thread model: posix
```

**Expected behavior**
Make a successful build on Linux

**Runtime environment:**

- OpenTelemetry Automatic Instrumentation version: 0.3.1
- OS: Oracle Linux Server release 7.6
- .NET version: .NET 6.0

attached please find the full output of the build: [build.log](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/files/9696601/build.log)

**Comment by pellared** [comment]
After a quick look at 

1. Your `clang` version looks old. I would suggest using at least `7.0`.
2. What is your version of `gcc`? I suggest at least `8.3`

This is what is installed on GH runners for reference: https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md#language-and-runtime

Here is our doc what is needed but there is no info regarding version (it should work with the latest versions): https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/main/docs/developing.md#linux-and-macos

Please let me know if it helps or if I need to look deeper.

**Comment by muhaook** [comment]
Thanks @pellared , my gcc version is 4.8.5. Looks old as well. I'll try to update both clang and gcc
```
$ gcc --version
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36.0.1)
```

**Comment by muhaook** [comment]
@pellared , I installed gcc under /opt/rh/devtoolset-8/root/usr/bin and added it to PATH. Can it be used by build script? 
```
$ which gcc
/opt/rh/devtoolset-8/root/usr/bin/gcc
$ gcc --version
gcc (GCC) 8.3.1 20190311 (Red Hat 8.3.1-3.2.0.7)
```
I saw [this](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/96638cd6f5f145cc1e2822afab01091dd3998e59/src/OpenTelemetry.AutoInstrumentation.Native/CMakeLists.txt#L57) in code and was thinking it may use gcc under /usr/bin
```
if (NOT EXISTS /usr/bin/gcc)
    message(FATAL_ERROR "GCC is required to build the project's dependencies")
else()
    message(STATUS "GCC was found")
endif()
```

**Comment by pellared** [comment]
I have no experience in CMake (sic!). Do you have any proposal on how to fix it?

After a quick search, I think we could use [`find_program`](https://cmake.org/cmake/help/latest/command/find_program.html) and `if (NOT DEFINED <VAR>)`.

I also found https://stackoverflow.com/a/20580818/859275 a moment ago.

Do you want to try and contribute?

**Comment by RassK** [comment]
Unfortunately here we don't have good documentation how to setup linux build machine.

You can find Alpine setup here. 
https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/main/build/nuke/docker/alpine.dockerfile

```
RUN apk update \
    && apk upgrade \
    && apk add --no-cache --update \
        clang \
        cmake \
        make \
        bash \
        alpine-sdk \
        protobuf \
        protobuf-dev \
        grpc
```
Most of it is easily portable to different linux distro, except alpine-sdk. 
It definitely hides gcc, currently can't be 100% sure what else is required.
just guessing here: git, gcc, g++, llvm

https://pkgs.alpinelinux.org/package/edge/main/x86_64/alpine-sdk
Herer you can see the dependencies. The whole dependency tree contains important parts.

Some parts are similar within Splunk's distro (specially the native part). Here is Splunk's Debian distro.
https://github.com/signalfx/signalfx-dotnet-tracing/blob/main/tracer/build/_build/docker/debian.dockerfile
I guess important packages here > llvm, gcc, build-essential

**Comment by muhaook** [comment]
Thanks @RassK , I am working on other things now, but will look into this as soon as I have time. 

Can we keep this git issue open for a while? I am also okay if we close this at the moment and open a new one if needed in the future.

**Comment by muhaook** [comment]
Closing this as 2 related git issues have been filed as above
