### ISSUE TITLE
Format native code

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-dotnet-instrumentation#1356]
I propose to use `clang-format` for formatting the native code. I have no preference regarding what style we should use 😉

**Comment by pjanotti** [comment]
Random thought: although they probably are not the latest (or event recent) C++ standard perhaps it is worth to consider the same practices as done in dotnet/runtime for their native code.

**Comment by pjanotti** [comment]
`dotnet/runtime` uses `clang-format` to format their native sources. I like the level of control and automatic formatting capabilities. Here is the commit setting up `clang-format` on `dotnet\runtime`: https://github.com/dotnet/runtime/commit/a526e77b6d5fbf362cd40e442a0ac893e681448f#diff-b9efd307c4085495016f2431900d62c281886557467edb33e4639406c8874477

**Comment by pellared** [comment]
I found some helpful code here as well: https://github.com/dotnet/jitutils
