### ISSUE TITLE
Create convenient PowerShell scripts

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-dotnet-instrumentation#1374]
Create PowerShell scripts that will facilitate installation and instrumentation.

They should primarily target Windows OS.

**Comment by RassK** [comment]
An idea to remove restart requirement when global env is used. (at least for Windows and with PowerShell)

The `install.psm1` module should get it's own global location pointer env, where it installed core files (eg: `OTEL_DOTNET_AUTO_INSTALL_DIR`). **I would not reuse `OTEL_DOTNET_AUTO_HOME`** not to cause mess in UX when manual intervention is required.
PowerShell module can use the new location to setup scoped variables instead. Basically it's a simple service locator.

**Comment by pellared** [comment]
Then the user could use the script in Dockerfile like this:

```docker
# escape=`
FROM mcr.microsoft.com/dotnet/framework/aspnet:4.8-windowsservercore-ltsc2022

# IIS instrumentation:
ADD https://raw.githubusercontent.com/open-telemetry/opentelemetry-dotnet-instrumentation/main/install.psm1 install.psm1
RUN powershell.exe -Command `
    $ErrorActionPreference = 'Stop'; `
    Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope Process; `
    Import-Module install.psm1; `
    Install-OpenTelemetryCore; `
    Register-OpenTelemetryForIIS; `
    & {iisreset}
# config
ENV OTEL_SERVICE_NAME="my-service" # required
# ENV OTEL_EXPORTER_OTLP_ENDPOINT="<your-endpoint-here>"

# existing stuff like (based on https://github.com/microsoft/iis-docker)
RUN powershell -NoProfile -Command Remove-Item -Recurse C:\inetpub\wwwroot\*
WORKDIR /inetpub/wwwroot
COPY content/ .
```
