### ISSUE TITLE
AspNet was disabled but observed HttpRequestIn as Activity.Current 

### ISSUE THREAD

**Issue by muhaook** [open-telemetry/opentelemetry-dotnet-instrumentation#1379]
# Bug Report

## Symptom

**Describe the bug**
I disabled ASPNET instrumentation by setting `OTEL_DOTNET_AUTO_TRACES_ENABLED_INSTRUMENTATIONS` as "`SqlClient`". but when I debugged in, I found "`Microsoft.AspNetCore.Hosting.HttpRequestIn`" was Activity.Current. It seems not correct. 

Also it prevented further span generation because all following activitySource.StartActivity() returned null, although there was at least a listener to my activity (not AspNet).

This happend on .NET core 3.1 only. It looks good on .Net Fx 4.6.2

**Expected behavior**
`Microsoft.AspNetCore.Hosting.HttpRequestIn` should not be Activity.Current any time after ASPNET was disabled

**Screenshots**
![httprequestin_currentActivity](https://user-images.githubusercontent.com/52417764/194560304-d5d7ee9a-daa0-4202-9945-668af9fda2b8.png)

**Runtime environment:**

- OpenTelemetry Automatic Instrumentation version: 0.3.1
- OS: Windows 10, IIS 10
- .NET version: .NET Core 3.1

**Comment by Kielek** [comment]
@muhaook, do you have some sample application where it is easily reproducible?

I can try to play a bit with it myself, but it should reduce time needed to reproduce.

Separate dedicated repo/fork with TestApplication will be great.

**Comment by muhaook** [comment]
[WebApiNetCore31.zip](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/files/9787521/WebApiNetCore31.zip)
@Kielek , attached please find the sample. 

steps to reproduce the issue:
- otel dotnet instrumentation package is installed under c:\tracer-home
- publish the attached sample to IIS using VS 2022
- config C:\Windows\System32\inetsrv\config\applicationHost.config
```
    <system.applicationHost>
        <applicationPools>
            <add name="DefaultAppPool" managedRuntimeVersion="v4.0" managedPipelineMode="Integrated">
                <environmentVariables>
                    <add name="COR_ENABLE_PROFILING" value="1" />
                    <add name="COR_PROFILER" value="{918728DD-259F-4A6A-AC2B-B85E1B658318}" />
                    <add name="CORECLR_ENABLE_PROFILING" value="1" />
                    <add name="CORECLR_PROFILER" value="{918728DD-259F-4A6A-AC2B-B85E1B658318}" />
                    <add name="DOTNET_ADDITIONAL_DEPS" value="c:\tracer-home\AdditionalDeps" />
                    <add name="DOTNET_SHARED_STORE" value="c:\tracer-home\store" />
                    <add name="DOTNET_STARTUP_HOOKS" value="c:\tracer-home\netcoreapp3.1\OpenTelemetry.AutoInstrumentation.StartupHook.dll" />
                    <add name="OTEL_DOTNET_AUTO_HOME" value="c:\tracer-home" />
                    <add name="OTEL_DOTNET_AUTO_INTEGRATIONS_FILE" value="c:\tracer-home\integrations.json" />
                    <add name="COR_PROFILER_PATH_64" value="c:\tracer-home\win-x64\OpenTelemetry.AutoInstrumentation.Native.dll" />
                    <add name="COR_PROFILER_PATH_32" value="c:\tracer-home\win-x86\OpenTelemetry.AutoInstrumentation.Native.dll" />
                    <add name="CORECLR_PROFILER_PATH_64" value="c:\tracer-home\win-x64\OpenTelemetry.AutoInstrumentation.Native.dll" />
                    <add name="CORECLR_PROFILER_PATH_32" value="c:\tracer-home\win-x86\OpenTelemetry.AutoInstrumentation.Native.dll" />
                    <add name="OTEL_DOTNET_AUTO_EXCLUDE_PROCESSES" value="dotnet.exe,dotnet" />
                    <add name="OTEL_DOTNET_AUTO_LOAD_TRACER_AT_STARTUP" value="true" />
                    <add name="OTEL_DOTNET_AUTO_TRACES_ENABLED_INSTRUMENTATIONS" value="SqlClient" />
                    <add name="OTEL_DOTNET_AUTO_METRICS_ENABLED_INSTRUMENTATIONS" value="AspNet,NetRuntime,HttpClient" />
                    <add name="OTEL_SERVICE_NAME" value="waimaidotnet" />
                    <add name="OTEL_TRACES_EXPORTER" value="otlp" />
                    <add name="OTEL_EXPORTER_OTLP_ENDPOINT" value="http://localhost:5678" />
                    <add name="OTEL_METRICS_EXPORTER" value="otlp" />
                    <add name="OTEL_DOTNET_AUTO_DEBUG" value="true" />
                    <add name="OTEL_DOTNET_AUTO_DUMP_ILREWRITE_ENABLED" value="0" />
                </environmentVariables>
            </add>
... ...
```
- use a browser to access http://localhost/webapinetcore31/api/values which returns:
```
Activity.Current.OperationName is Microsoft.AspNetCore.Hosting.HttpRequestIn
```

please let me know if you need more details.

**Comment by pellared** [comment]
@muhaook I am short on time, but I will do my best to help you.

1. Can you check if the same happens without auto-instrumentation if you just use the OTel SDK (and not use `OpenTelemetry.Instrumentation.AspNetCore`)? I guess that is something inside ASP.NET bootstrapping that automatically adds an ActivityListener. See [here](https://github.com/dotnet/runtime/issues/29285#issuecomment-485233176) for reference
2. Are the spans (traces) exported as well? If so are they having the same attributes (tags) as if the ASP.NET instrumentation were enabled? My guess is that they will have non-OTel compliant 

If my guesses are correct then we need to learn the solution to disable it.

**Comment by Kielek** [comment]
Potential workaround: https://github.com/dotnet/aspnetcore/issues/18955
I think it should be recommended way. If you are fine with such solution we could extend our documentation.

**Comment by pellared** [comment]
@muhaook I think we can keep it open as it would be good to describe a workaround in our [`troubleshooting.md](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/main/docs/troubleshooting.md).

**Comment by muhaook** [comment]
Looks like the workaround did not work on my test env. Here is my appsettings.json. After reboot IIS, I can still see `Activity.Current `as `Microsoft.AspNetCore.Hosting.HttpRequestIn `
```
{
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft": "Warning",
      "Microsoft.Hosting.Lifetime": "Information",
      "Microsoft.AspNetCore.Hosting.Diagnostics": "None"
    },
    "EventLog": {
      "LogLevel": {
        "Microsoft.AspNetCore.Hosting.Diagnostics": "None"
      }
    }
  },
  "AllowedHosts": "*"
}
```

**Comment by pjanotti** [comment]
@muhaook I just tested the `appsettings.json` above in a self-hosted AspNetCore and it worked as advertised. Please, check that your IIS test is loading the proper configuration.

**Comment by muhaook** [comment]
@pjanotti , yes, the workaround works as expected.
sorry, in my failed case, although I disabled ASP.NET for traces, I still had it enabled for metrics. That should be why I saw the Acitivity.Current was not null.
```
<add name="OTEL_DOTNET_AUTO_TRACES_ENABLED_INSTRUMENTATIONS" value="SqlClient" />
<add name="OTEL_DOTNET_AUTO_METRICS_ENABLED_INSTRUMENTATIONS" value="AspNet,NetRuntime,HttpClient" />
```

**Comment by pellared** [comment]
> I still had it enabled for metrics.

Is it not an unexpected side effect? Is not `Acitivity.Current` only related to tracing and should not have any relation to metrics?

**Comment by muhaook** [comment]
some details:
- applicationHost.config
```
<add name="OTEL_DOTNET_AUTO_METRICS_ENABLED_INSTRUMENTATIONS" value="AspNet,NetRuntime,HttpClient" />
```
- sample output
```
Activity.Current.OperationName is Microsoft.AspNetCore.Hosting.HttpRequestIn
```
- otel dotnet auto log
```
[2022-10-19T13:47:33.5744922Z] [Information] OpenTelemetry tracer initialized. 
[2022-10-19T13:47:33.6490460Z] [Information] OpenTelemetry meter initialized. 
[2022-10-19T13:47:33.6562866Z] [Information] OpenTracingShim loaded. 
[2022-10-19T13:47:33.8057445Z] [Debug] 'AspNetCoreMetricsInitializer' started 
```
- change applicationHost.config to
```
<add name="OTEL_DOTNET_AUTO_METRICS_ENABLED_INSTRUMENTATIONS" value="NetRuntime,HttpClient" />
```
- sample output
```
Activity.Current is null
```
- otel dotnet auto log
```
[2022-10-19T13:49:28.1565474Z] [Information] OpenTelemetry tracer initialized. 
[2022-10-19T13:49:28.3482801Z] [Information] OpenTelemetry meter initialized. 
[2022-10-19T13:49:28.3632973Z] [Information] OpenTracingShim loaded. 

```

**Comment by pjanotti** [comment]
Thanks @muhaook at first inspection is not clear to me why the activity is being created with your configuration. I will investigate this issue.

**Comment by pjanotti** [comment]
Ok confirmed: this is due to the `OpenTelemetry.Instrumentation.AspNetCore` metrics. It uses the activity to get the duration of the `http.server.duration` metric.

The question is that users may be surprised by that. I think that we should at least document the issue to try to avoid surprises.

**Comment by pjanotti** [comment]
AspNet on Framework only generates the `http.server.duration` is if the trace instrumentation `AspNet` is enabled. This is certainly a bug.

**Comment by pjanotti** [comment]
AspNet requires the tracer to be enabled in order to collect the metrics, see [test comment](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/d9e91a7525cab01467d2e44661195c9ecb086e20/test/OpenTelemetry.Instrumentation.AspNet.Tests/HttpInMetricsListenerTests.cs#L38-L50).

Issue on SDK repo https://github.com/open-telemetry/opentelemetry-dotnet/issues/2994
