### ISSUE TITLE
Recreate /examples

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-dotnet-instrumentation#1388]
I think we should change the `examples` to just contain a client and server app, Dockerfiles, and a docker-compose to run it.

Previously we used it for testing purposes. Right now I think we should make it more .NET devs (users) friendly.

_Originally posted by @pellared in https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/1383#pullrequestreview-1135727555_

**Comment by pjanotti** [comment]
Right now there are two `instrument.sh` scripts on the repo. While refactoring the examples we should look into keeping a single one, see https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/1681#issuecomment-1329908775

**Comment by pellared** [comment]
TODO: Bring back the `AspNetCoreMvc` example.
