### ISSUE TITLE
Drop Jaeger exporter /dev/otel-config.md

### ISSUE THREAD

**Issue by Kielek** [open-telemetry/opentelemetry-dotnet-instrumentation#1389]
Jaeger supports OTLP by default. We should be able to drop jaeger protocol here.

Probably separate PR. Ref: https://www.jaegertracing.io/docs/1.38/apis/#opentelemetry-protocol-stable

_Originally posted by @Kielek in https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/1383#discussion_r990935155_

**Comment by pellared** [comment]
Related PR: https://github.com/open-telemetry/opentelemetry-specification/pull/2858
