### ISSUE TITLE
Add automated release

### ISSUE THREAD

**Issue by dszmigielski** [open-telemetry/opentelemetry-dotnet-instrumentation#140]
**What**
Add trigger in GH actions workflow that will run the build on tag push, and will create GH release.

**Why**
We need to have automated release process.

**Comment by pellared** [comment]
I think that [RELEASING.md ](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/main/docs/RELEASING.md) would need to be updated as part of this issue and a `v0.0.1` released.
