### ISSUE TITLE
Document OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE  environment variable

### ISSUE THREAD

**Issue by pichlermarc** [open-telemetry/opentelemetry-dotnet-instrumentation#1405]
# Feature Request

**Is your feature request related to a problem? Please describe.**
Currently the `OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE` enviornment variable is not used to configure the export temporality ([see here](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/2534ce3a3754648b9f4a10707be19f41393e2221/src/OpenTelemetry.AutoInstrumentation/Configuration/EnvironmentConfigurationMetricHelper.cs#L96)). 

The spec states that:

> If a language provides a mechanism to automatically configure a
[MetricReader](../sdk.md#metricreader) to pair with the associated
Exporter (e.g., using the [`OTEL_METRICS_EXPORTER` environment
variable](../../sdk-environment-variables.md#exporter-selection)),
then by default:
> * The exporter MUST be paired with a [periodic exporting
  MetricReader](../sdk.md#periodic-exporting-metricreader).
> * **The exporter MUST configure the default aggregation temporality on the
  basis of instrument kind using the
  `OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE` variable** as described
  below.
> * The exporter MUST configure the default aggregation on the basis of instrument kind using
  the `OTEL_EXPORTER_OTLP_METRICS_DEFAULT_HISTOGRAM_AGGREGATION` variable as described below if it is implemented.

**Describe the solution you'd like**
Allow configuration of aggregation temporality via `OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE`

**Additional context**
As this is a MUST requirement in the spec, this might also be a bug.

**Comment by pellared** [comment]
Thanks for reporting the issue. I created a similar one in OTel .NET SDK: https://github.com/open-telemetry/opentelemetry-dotnet/issues/3756

**Comment by pichlermarc** [comment]
Hi, @pellared thanks for creating the issue in the core repo. :slightly_smiling_face: 

I was not sure if here is the right place, or if I should open it in the core repo, but as the condition part of this spec
> If a language provides a mechanism to automatically configure a [MetricReader](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/sdk.md#metricreader) to pair with the associated Exporter (e.g., using the OTEL_METRICS_EXPORTER environment variable), then by default

is implemented in this repo, I opted to open the issue here instead. :slightly_smiling_face:

If there's a consensus where this feature belongs then I can also dedicate some time to implement this if necessary. :slightly_smiling_face:

**Comment by Kielek** [comment]
@pichlermarc, we have a plan release 0.4.0-beta shortly. If it is important feature for you we can include it into this code base. If it can wait it should be implemented in the api/sdk repository.

Upgrade path for OTel API/SDK 1.4.0 will be more complicated and it will take more time.

> If there's a consensus where this feature belongs then I can also dedicate some time to implement this if necessary. 🙂

Sounds great!

**Comment by pellared** [comment]
> If there's a consensus where this feature belongs then I can also dedicate some time to implement this if necessary. 🙂

It is fine to implement it here before it is supported via the SDK 👍 We are open to your contribution 🎉

**Comment by pellared** [comment]
@pichlermarc Are you working on it? Do you need any help?

**Comment by pichlermarc** [comment]
@pellared, sorry, I did not get around to doing this yet. :/
I'll comment here when I get to working on it.

**Comment by RassK** [comment]
This PR adds a workaround for a moment missing direct configuration option.
https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/1542

**Comment by pichlermarc** [comment]
Hi, I just went over old issues I created and this seems to be already implemented. 

I just tried this out using the [automatic instrumentation docs on opentelemetry.io](https://opentelemetry.io/docs/languages/net/automatic/getting-started/), switched the exporter to OTLP and set up the environment variable. 

Big thanks to the person who took care of that :slightly_smiling_face:

**Comment by pellared** [comment]
Reopening as the environment variable is not documented.
