### ISSUE TITLE
Explore ILmerge possibility

### ISSUE THREAD

**Issue by Kielek** [open-telemetry/opentelemetry-dotnet-instrumentation#1418]
TBD, @rajkumar-rangaraj, could you please prepare some description?
Created based on last SIG meeting discussion.

**Comment by pellared** [comment]
Leaving a few notes before I forget.

It could be probably applied for all dependencies that could be vendored (like OTel libraries). It does not apply to `System.Diagnostics` and instrumented libraries. It should mitigate a lot of assembly conflicts besides `System.Diagnostics` and other runtime libraries which have static state.

**Comment by rajkumar-rangaraj** [comment]
Closing this issue as we plan to peruse out-of-process auto-instrumentation.
