### ISSUE TITLE
Improve configuration via app/web.config

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-dotnet-instrumentation#1429]
## Current behavior

https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/fa6c733c6ff418f9a6d967bcd1509f65f2150717/src/OpenTelemetry.AutoInstrumentation/Configuration/TracerSettings.cs#L111

This means that only the env vars handled in OTel .NET AutoInstrumentation managed code can configured using `app/web.config`

The user cannot use it e.g. to configure an ASP.NET application deployed on IIS.

The feature is also not documented (which is probably good at this moment

## Proposal

1. Add additional code that would check if any (an allow-list) of OTel SDK configuration env vars are set via `app/web.config` if so then we should set them before bootstrapping the OTel .NET SDK.
2. Document the possibility of configuring via `app/web.config` on .NET Framework. List configuration (.NET Profiler and Runtime env vars, env vars used in our profiler code) that are not supported by `app/web.config` .

**Comment by pellared** [comment]
Changing the milestone as this is important for IIS deployed ASP.NET apps

**Comment by pellared** [comment]
Notice: The config in app/web.config should NOT override a setting which is already set via env var.

**Comment by pellared** [comment]
Probably generalized OTEL_* whitelist should be fine.

**Comment by RassK** [comment]
Native part also doesn't see app / web.config vars... but I think this will become specially important with official OTel config file.

1. Add these vars to the exception list? - will make UX more complex
2. Bridge dictionary from the managed level? - not sure if the execution location is too early for managed bridge?

**Comment by tanaka-takayoshi** [comment]
Do you plan to support configuring [Resource semantic conventions](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/resource/semantic_conventions/README.md#semantic-attributes-with-sdk-provided-default-value) by using Web.config?
This helps the situation that we want to identify the web application names run by a single application pool. Since these applications are run by the same process, env var can't specify different names for these applications.

**Comment by pellared** [comment]
@tanaka-takayoshi Yes. That is the plan 😉 I hope that it will be finished by the end of January.

**Comment by pellared** [comment]
Status after merging https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/2066:

Following settings cannot be configured via `app.config`/`web.config`:

- `OTEL_DOTNET_AUTO_DEBUG` 
- `OTEL_DOTNET_AUTO_INTEGRATIONS_FILE` 
- `OTEL_DOTNET_AUTO_HOME` 
- `OTEL_DOTNET_AUTO_EXCLUDE_PROCESSES` 
- `OTEL_DOTNET_AUTO_LOG_DIRECTORY` is 
- `OTEL_DOTNET_AUTO_CLR_DISABLE_OPTIMIZATIONS
- `OTEL_DOTNET_AUTO_AZURE_APP_SERVICES`
- `OTEL_DOTNET_AUTO_DUMP_ILREWRITE_ENABLED`
- `OTEL_DOTNET_AUTO_CLR_ENABLE_INLINING`
- `OTEL_DOTNET_AUTO_CLR_ENABLE_NGEN`
- `OTEL_DOTNET_AUTO_NETFX_REDIRECT_ENABLED`

Moreover `OTEL_DOTNET_AUTO_METRICS_DISABLED_INSTRUMENTATIONS`, `OTEL_DOTNET_AUTO_LOGS_ENABLED_INSTRUMENTATIONS, `OTEL_DOTNET_AUTO_LOGS_DISABLED_INSTRUMENTATIONS` are not handled for bytecode instrumentation.
