### ISSUE TITLE
Only inject instrumentation assemblies that are going to be used

### ISSUE THREAD

**Issue by pjanotti** [open-telemetry/opentelemetry-dotnet-instrumentation#1437]
We have the goal of automatically enabling all available instrumentations. However, some of the instrumentations have extension methods that perform initialization directly accessing the `TraceProviderSdk` directly using these methods at initialization will inject dependencies on the process that are not used in practice. If the extension method only enables an activity source the cost is expected to be small. That said some of the extension methods can use types and code that comes from the actual dependencies and they may cause the process to load more assemblies and using code that is not needed in practice. This will affect start up time.

This is related to a previous discussion when enabling all instrumentations, see #388 and an issue on the SDK, see https://github.com/open-telemetry/opentelemetry-dotnet/issues/3253

At first it seems to me that we should pursue again having the capability of calling the "add" extension methods after the initial creation of the provider.

Extra exporter or SDK related modules are addressed via #1505.

**Comment by pellared** [comment]
I think we already have this possibility via `LazyInstrumentationLoader` (unless I am missing something). It is used for `MySqlData` and `AspNetCore` instrumentations.

@RassK PTAL

**Comment by pjanotti** [comment]
@pellared and @RassK I want to avoid loading the instrumentations like WCF. The `LazyInstrumentationLoader` is useful for instrumentations that don't require the `builder`, however, some of the instrumentations require that. I didn't look if such instrumentations really need access to the builder or if it is just a bad pattern.

I'm planning to look into this later and if there is a real need to access the builder for some instrumentations we need to go back to the SDK and ask for the capability of adding instrumentations after `Build()`.

**Comment by RassK** [comment]
@pjanotti  I see most of the builder extensions are just for creating the instrumentation instance and subscribing to some source. `LazyInstrumentationLoader` basically does the same thing but separates these 2 parts and invokes those parts in different time frame.

Wcf is a bit exceptional. Instead of creating instrumentation instance, it just creates and assigns global options. It's again nothing that `LazyInstrumentationLoader` can't handle.

**Comment by pjanotti** [comment]
yes, that is the preferred pattern. Although we can use reflection to access the internals of instrumentation packages and use the `LazyInstrumentationLoader` we should move such packages to make related APIs public. This will ensure that they won't break automatic instrumentation in minor releases.

We should review all instrumentations that are being added via extension methods and check which ones can and can't be switched to `LazyInstrumentationLoader`
