### ISSUE TITLE
Remove `OTEL_DOTNET_AUTO_ENABLED`

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-dotnet-instrumentation#1477]
I propose to remove `OTEL_DOTNET_AUTO_ENABLED` as it is redundant with the `CORECLR_ENABLE_PROFILING` and `CLR_ENABLE_PROFILING` env vars (or  all CLR Profiler env vars can be unset).

It is also confusing as if one set it to `false` on .NET (Core) then he/she will still have the source instrumentation enabled. Therefore making as a bug.

**Comment by pjanotti** [comment]
Agreed: I also don't see the value of `OTEL_DOTNET_AUTO_ENABLED`: the profiler is launched but then it returns `E_FAIL` on the initialization call.
