### ISSUE TITLE
Rename `AT_STARTUP` env vars

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-dotnet-instrumentation#1478]
I propose to rename the following env vars accordingly:

- `OTEL_DOTNET_AUTO_LOAD_TRACER_AT_STARTUP` -> `OTEL_DOTNET_AUTO_TRACES_ENABLED`
- `OTEL_DOTNET_AUTO_LOAD_METER_AT_STARTUP` -> `OTEL_DOTNET_AUTO_METRICS_ENABLED`

The reasons are:
- It not only sets the OpenTelemetry .NET SDK's signal providers, but also add source instrumentations
- I think that the names would be more clear 😉 

The only problem that would remain is that the CLR Profiler can do bytecode instrumentation. But I would leave it as it is as it should be a NOOP from the "user perspective" and it could be useful if one would like to use OTel .NET Auto only to get bytecode instrumentations. _I think this use case could be documented._

**Comment by pjanotti** [comment]
I agree @pellared having the capability of adding only bytecode instrumentations and let all the rest be handled by the code in the application seems a good idea.
