### ISSUE TITLE
Add tests for `OTEL_DOTNET_AUTO_*_DISABLED_INSTRUMENTATIONS=[id]`

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-dotnet-instrumentation#1480]
Can you please add a test in `LogTests` that would set `OTEL_DOTNET_AUTO_LOGS_DISABLED_INSTRUMENTATIONS=ILogger` and assert that none logs are send using `collector.AssertEmpty(5.Seconds());`? It can be named  e.g. `Disabled`.

It would test the instrumentation can be disabled using `ILogger` ID. Otherwise we would have not tests that check the instrumentation IDs. 

**Similar tests should be added for ALL ~~instrumentations~~ signals (traces and metrics)** (as a separate PR).

If you want you we can address even this comment in a separate PR.

_Originally posted by @pellared in https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/1475#discussion_r1001539610_

**Comment by pellared** [comment]
@biroj

**Comment by pellared** [comment]
SIG meeting:
@birojnayak will take a look

**Comment by birojnayak** [comment]
working on it...

**Comment by pellared** [comment]
Just to quickly clarify as the description is very unprecise. 

This issue is **orignally** about adding tests that each instrumentation it can be disabled using `OTEL_DOTNET_AUTO_<SIGNAL>_DISABLED_INSTRUMENTATIONS=<ID>`.

But when I think about it know maybe it would be enough if we even have a single test per each signal in `SmokeTests` to check if it is possible to disable an instrumentation library. Adding tests for each instrumentation would increase the duration of the test suite without testing things which is error-prone (I do not expect someone would by mistake change the "instrumentation ID"). The most important think is to have any test to be sure that the  `OTEL_DOTNET_AUTO_*_DISABLED_INSTRUMENTATIONS` are working (with any instrumentation).
