### ISSUE TITLE
Add tests for `OTEL_DOTNET_AUTO_*_ENABLED_INSTRUMENTATIONS=none`

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-dotnet-instrumentation#1481]
Can you please add a test in `SmokeTests` similar to `SubmitLogs` that would set `OTEL_DOTNET_AUTO_LOGS_ENABLED_INSTRUMENTATIONS=none` and assert that none logs are send using `collector.AssertEmpty(5.Seconds());`? 

It would test the `OTEL_DOTNET_AUTO_LOGS_ENABLED_INSTRUMENTATIONS` env var. 

Similar tests should be added for traces and metrics (as a separate PR).

I want to have this smoke test added as part of this PR to have any integration tests verifying the new functionality.

_Originally posted by @pellared in https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/1475#discussion_r1001556498_

**Comment by pellared** [comment]
SIG meeting:
@birojnayak will take a look

**Comment by birojnayak** [comment]
@pellared @Kielek I believe this is already taken care via [this commit](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/commit/a10cd338bf12a1d8b69cf7bae47729711e1c6b9b) . Let me know if my understanding is incorrect.

**Comment by pellared** [comment]
> Similar tests should be added for traces and metrics (as a separate PR).

@birojnayak This issue is about adding a similar test for traces and metrics (e.g.  ` `TracesNoneInstrumentations` and `MetricsNoneInstrumentations`)
