### ISSUE TITLE
Refactor integration loader - native code

### ISSUE THREAD

**Issue by Kielek** [open-telemetry/opentelemetry-dotnet-instrumentation#1482]
This is getting very nasty. I think it is time to refactor and introduce a `Integrations` class so that we can change the signatures to something like:

```
Integrations LoadIntegrationsFrom*(inputs...)
```

or even instead of functions create static methods in `Integrations` class so that the are named e.g. `FromJson` or `LoadJson`

We can do it in a separate PR to make it easier for reviewing.

_Originally posted by @pellared in https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/1475#discussion_r1001553743_

**Comment by pjanotti** [comment]
As pointed in #1825 this work should revisit the skip assemblies code. We just need to keep module data for the assemblies that are going to be instrumented.

**Comment by Kielek** [comment]
When #2280 will be merged there will be no loading instrumention list from json file. Closing.
