### ISSUE TITLE
GraphQL instrumentation adds non-OTel compliant error attributes

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-dotnet-instrumentation#1485]
## Actual

GraphQL (and possibly other bytecode instrumentations) use https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/da42322b088b6d490456e524eaa9ca61b3c5bf9d/src/OpenTelemetry.AutoInstrumentation/Tagging/Tags.cs#L26-L44

## Expected

For setting the status we probably should use: https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.activity.setstatus?view=net-6.0#system-diagnostics-activity-setstatus(system-diagnostics-activitystatuscode-system-string)

For marking the exception we should rather use OTel API: https://github.com/open-telemetry/opentelemetry-dotnet/blob/16e0758c148c6bac26cf4a31a6b405482a798d84/src/OpenTelemetry.Api/Trace/ActivityExtensions.cs#L89

References in spec:
- https://github.com/open-telemetry/opentelemetry-specification/blob/8ed127a403c59e1baa5203c6cdf472ea21df0332/specification/common/mapping-to-non-otlp.md#span-status
- https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/exceptions.md
Most probably https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry.Api/Trace/ActivityExtensions.cs should be used

See also:
- https://github.com/open-telemetry/opentelemetry-dotnet/blob/ded2eefcc20da3b27974a313cc52fc1d0f63e997/src/OpenTelemetry.Api/Internal/SemanticConventions.cs#L106-L109
- https://github.com/open-telemetry/opentelemetry-dotnet/blob/ded2eefcc20da3b27974a313cc52fc1d0f63e997/src/OpenTelemetry.Api/Internal/SpanAttributeConstants.cs#L24-L25

**Comment by RassK** [comment]
SIG: we can just remove these validation messages. They should or could be in the logs instead. While logs injection works, everything will be great.
