### ISSUE TITLE
How to handle multiple versions of the same assembly into the instrumented app

### ISSUE THREAD

**Issue by pjanotti** [open-telemetry/opentelemetry-dotnet-instrumentation#15]
This issue is to collect information per discussion on the SIG meeting on 08/26/2020

- We need to capture how the profiler should handle this scenario.

- ~~@Mikhail-msft to provide some information on this topic.~~

**Comment by pjanotti** [comment]
@macrogreg with the approach in your prototype I don't think that we will have this scenario or multiple versions into the instrumented app. (see https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/18)

cc @open-telemetry/dotnet-instrumentation-approvers

**Comment by macrogreg** [comment]
All details about the planned solution to this problem are described here: https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/issues/13
I do not think we need to keep this open. Closing for now. Please feel free to re-open if you disagree.
