### ISSUE TITLE
RegistryKey.SetValue does not support arrays of type 'Object[]'

### ISSUE THREAD

**Issue by surdaft** [open-telemetry/opentelemetry-dotnet-instrumentation#1510]
# Bug Report

## Symptom

**Describe the bug**
When executing the function Register-OpenTelemetryForIIS we encounter the error:
```
Set-ItemProperty: RegistryKey.SetValue does not support arrays of type 'Object[]'. Only Byte[] and String[] are supported.
```

This occurs on line 121 of this file: https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/main/OpenTelemetry.DotNet.Auto.psm1#L121

**Expected behavior**
It is able to register the environment variables.

**Screenshots**
![image](https://user-images.githubusercontent.com/8268249/198282156-4febc4f3-3c14-4f85-aaeb-b540c5633ee8.png)

![image](https://user-images.githubusercontent.com/8268249/198282688-525cf989-af87-40df-9b92-cbadde0b884c.png)

**Runtime environment (please complete the following information):**

- OpenTelemetry Automatic Instrumentation version: [e.g. 1.0.0]
  v0.4.0-beta1

- OS: [e.g. Windows Server 2012 R2 ]
  Windows Server 2016

- .NET version: [e.g. .NET Framework 4.6.2, .NET Core 2.1]
  4.8

**Additional context**
Also tried with PowerShell v5.1

## Reproduce

1. Open powershell
2. Run install commands (eg $module_url, download_path etc..)
3. Register-OpenTelemetryForIIS

**Comment by RassK** [comment]
I can confirm. Seems WS 2016 related only, as WS 2019 and later work without explicit definition.

**Comment by surdaft** [comment]
We are giving it a test now, thanks @pellared

**Comment by surdaft** [comment]
That looked successful, we received no error messages. Thanks for the extremely quick fix :)

**Comment by pellared** [comment]
Kudos goes to @RassK 🎉
