### ISSUE TITLE
Distribute as a NuGet package

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-dotnet-instrumentation#1541]
We got information that there are developers who would prefer to deploy using a NuGet package similarly to https://github.com/DataDog/dd-trace-dotnet/blob/master/docs/Datadog.Trace.Bundle/README.md

**Comment by pellared** [comment]
This issue is about "packaging the distribution" for the end user.

**Comment by pjanotti** [comment]
@rajkumar-rangaraj the current package adds the native files, but, they are not marked as content files. The end result is that adding a `PackageReference` doesn't automatically adds the native bits to the application.

There are a few ways that we can do this. If using the nuspec file [NuGet provides an example](https://github.com/NuGet/Samples/tree/main/ContentFilesExample/authoring). Upstream uses [a csproj](https://github.com/DataDog/dd-trace-dotnet/blob/87ed4f65414bcb80b8dada3cf1fcdeafe1f82ce5/tracer/src/Datadog.Trace.Bundle/Datadog.Trace.Bundle.csproj#L21).

The current package has the all the instrumentation and SDK dependencies so a direct approach of simply packing the `bin/tracer-home` ends up with some redundant content. Anyway, this can be considered an optimization.

**Comment by pellared** [comment]
Based on the SIG meeting I think we need two NuGet packages:

- first for "distributing" the binaries (native, store, additional deps...). I think it should be via content files as it is more usable
- second for "dependencies" so that it can be used for plugin development as well as for solving package version conflicts

**Comment by pjanotti** [comment]
Having NuGet packages also affects redirection on the .NET Fx. It doesn't remove the need for something like #1646, but, it greats reduces the possibility of runtime conflicts.

**Comment by pjanotti** [comment]
Obs.:
> first for "distributing" the binaries (native, store, additional deps...)

If the application can add packages at build time there is no reason for the additional deps or store.

**Comment by Kielek** [comment]
Based on conversation with @rajkumar-rangaraj and @pjanotti we have two scenarios to cover.
1. @rajkumar-rangaraj requirement
Possibility to sync all our dependencies to be able to build plugins executed by extenstion points without manually syncing package dependencies.
2. @pjanotti requirement:
Distribute all files as nuget package. When you add it to the project output should be extended by _tracer-home_ and after adding few env. vars published folder should be instrumented.

Guys, could you please check if I do not missed anything?
