### ISSUE TITLE
Disable / Remove config autoloading

### ISSUE THREAD

**Issue by RassK** [open-telemetry/opentelemetry-dotnet-instrumentation#160]
### Background

`GlobalSettings` introduces some automatic config loading. This could lead to serious security issues and also hardens bug tracking. 
We should either disable (make it optional) or remove completely that feature. See discussion at https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/129#pullrequestreview-647515612

See "datadog.json" part:
```
            var configurationFileName = configurationSource.GetString(ConfigurationKeys.ConfigurationFileName) ??
                                        configurationSource.GetString("OTEL_DOTNET_TRACER_CONFIG_FILE") ??
                                        Path.Combine(GetCurrentDirectory(), "datadog.json");
```

**Comment by pellared** [comment]
Orginal discussion: https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/129#discussion_r622504615

**Comment by RassK** [comment]
As decided in SIG autoload json configs will be removed. (Either environment scoping or web / app.configs can be used)
