### ISSUE TITLE
Refine SDK guidance for instrumentation libraries

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-dotnet-instrumentation#1601]
When using manual instrumentation it makes sense for instrumentation libraries to add only the builder extension method to perform any initialization they may require. However, for zero-touch instrumentation, this is not ideal. While we delay loading the instrumentation until the proper assembly is loaded many times we have to use internals to actually enable the instrumentation. This exposes the zero-touch instrumentation to bugs/breaks in minor upgrades of the instrumentation libraries. In order to minimize this problem we should consider updating the recommendations on the SDK side to advise instrumentation libraries to make public any member required to enable the instrumentation.

**Comment by pjanotti** [comment]
SDK doc with the guidance for instrumentation library developers https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/docs/trace/extending-the-sdk/README.md#writing-a-custom-instrumentation-library

**Comment by lachmatt** [comment]
Related issue: https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/issues/896

**Comment by Kielek** [comment]
SIG notes: Existing notes is not followed by library authors. Refinement will not help this.
