### ISSUE TITLE
Tests shell script with CI artifacts

### ISSUE THREAD

**Issue by Kielek** [open-telemetry/opentelemetry-dotnet-instrumentation#1604]
> https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/issues/1602 created to update instrument.sh script when we will ready to release.

I think that as part of a separate PR (issue) we could:
1. copy the existing `shell-scripts` and `powershell-scripts` jobs from `ci.yml` to `release.yml` (we could then change `${{ github.sha }}/` to  `${{ github.ref_name }}`)
2. change the existing `shell-scripts` and `powershell-scripts` jobs from `ci.yml` to test the instrumentation on the "build" artifacts (so without downloading and with `OTEL_DOTNET_AUTO_HOME` and `OTEL_DOTNET_AUTO_INSTALL_DIR` set to the bin output)

_Originally posted by @pellared in https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/issues/1603#issuecomment-1309186462_

**Comment by pellared** [comment]
I just realized that point 1. will not work before the artifacts are released... We would need to first tackle https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/issues/1508 or think of some other way (e.g. manually triggered workflow after the release is published).

**Comment by pellared** [comment]
The current approach also influences the release downloads. See: https://cloud-native.slack.com/archives/C01NR1YLSE7/p1669227566496719
