### ISSUE TITLE
SmokeTests for `OTEL_DOTNET_AUTO_*_ENABLED=false`

### ISSUE THREAD

**Issue by Kielek** [open-telemetry/opentelemetry-dotnet-instrumentation#1630]
We should add a SmokeTests for `OTEL_DOTNET_AUTO_*_ENABLED=false` (can be as a separate PR). It should be very easy (based on https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/1613).

_Originally posted by @pellared in https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/1629#pullrequestreview-1184131679_

**Comment by pellared** [comment]
@birojnayak
