### ISSUE TITLE
MacOS (and possibly other .zip) doesn't contain net6.0 folder at root of download like suggested by DOTNET_STARTUP_HOOKS in readme

### ISSUE THREAD

**Issue by RyanAwareHQ** [open-telemetry/opentelemetry-dotnet-instrumentation#1635]
> The macos .zip [download](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/releases/tag/v0.4.0-beta.1) on v0.4.0-beta.1 is evidently now outdated as it still contains the previous path this commit changes. Please advise.

_Originally posted by @RyanAwareHQ in https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/1603#discussion_r1025938154_

**Comment by Kielek** [comment]
You are trying to use documentation in dev.
Please check: https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/043563346872c949024dd072ab2d8d35d5b26548/docs/README.md?plain=1#L10

Settings for 0.4.0-beta.1 release is under https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/v0.4.0-beta.1/docs/config.md#net-runtime

I expect more mistakes like this in the future. Do you see any better option how to communicate it?

**Comment by pjanotti** [comment]
No guarantees that it will be visible enough, but, adding a link to the corresponding docs on the release itself may be helpful.
