### ISSUE TITLE
Tracking subscription difference in Http instrumentation

### ISSUE THREAD

**Issue by RassK** [open-telemetry/opentelemetry-dotnet-instrumentation#1637]
_Comment from @pjanotti at https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/1628#discussion_r1025783364_

### What

There is a difference how SDK subscribes to the source. SDK is checking the version of `System.Net.Http` package, if it's >= 7.0.0 then  `System.Net.Http` is subscribed.

For auto instrumentation this behaviour will trigger `System.Net.Http` assembly load. Instead, we hope, that `System.Net.Http` namespace did not exist previously, so subscribing to the source anyway doesn't hurt.

Auto VS SDK
```csharp
#if NETFRAMEWORK
            builder.AddSource("OpenTelemetry.Instrumentation.Http.HttpWebRequest");
#else
            builder.AddSource("OpenTelemetry.Instrumentation.Http.HttpClient");
            builder.AddSource("System.Net.Http"); // This works only System.Net.Http >= 7.0.0
            builder.AddLegacySource("System.Net.Http.HttpRequestOut");
#endif
```

```csharp

internal sealed class HttpHandlerDiagnosticListener : ListenerHandler
{
    // https://github.com/dotnet/runtime/blob/7d034ddbbbe1f2f40c264b323b3ed3d6b3d45e9a/src/libraries/System.Net.Http/src/System/Net/Http/DiagnosticsHandler.cs#L19
    internal static readonly string HttpClientActivitySourceName = "System.Net.Http";

    // ...

    static HttpHandlerDiagnosticListener()
    {
        try
        {
            IsNet7OrGreater = typeof(HttpClient).Assembly.GetName().Version.Major >= 7;
        }
        catch (Exception)
        {
            IsNet7OrGreater = false;
        }
    }
}

// ...

if (HttpHandlerDiagnosticListener.IsNet7OrGreater)
{
    builder.AddSource(HttpHandlerDiagnosticListener.HttpClientActivitySourceName);
}
else
{
    builder.AddSource(HttpHandlerDiagnosticListener.ActivitySourceName);
    builder.AddLegacySource("System.Net.Http.HttpRequestOut");
}
```

**Comment by pellared** [comment]
SIG meeting:
- double check after OTel SDK bump and if it is possible to have duplicate spans (e.g. if it is possible to refernce HttpClient 7.0.0 in .NET 6.0)

**Comment by pellared** [comment]
Done https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/b00be6926926d289de784246d1dc8d513bce940b/test/IntegrationTests/HttpTests.cs#L45-L47
