### ISSUE TITLE
.NET Core 3.1/.NET 5.0 app crashes with auto-instrumentation

### ISSUE THREAD

**Issue by rajkumar-rangaraj** [open-telemetry/opentelemetry-dotnet-instrumentation#1644]
Usage of auto-instrumentation with .NET Core 3.1/.NET 5.0 crashes the app on start-up with below exception.

```
Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
File name: 'System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at System.Reflection.RuntimeAssembly.GetType(QCallAssembly assembly, String name, Boolean throwOnError, Boolean ignoreCase, ObjectHandleOnStack type, ObjectHandleOnStack keepAlive, ObjectHandleOnStack assemblyLoadContext)
   at System.Reflection.RuntimeAssembly.GetType(String name, Boolean throwOnError, Boolean ignoreCase)
   at System.Reflection.Assembly.GetType(String name, Boolean throwOnError)
   at System.StartupHookProvider.CallStartupHook(StartupHookNameOrPath startupHook)
   at System.StartupHookProvider.ProcessStartupHooks()
```

.NET Core 3.1 and .NET 5.0 has reached end of life, but using auto-instrumentation should not crash the process. Rather it should backoff the instrumentation,

Only option left for us is to target the `OpenTelemetry.AutoInstrumentation.StartupHook` project version as `netcoreapp3.1`. We could modify a folder in `tracer-home` as `netcore` or `net` instead of `netcoreapp3.1` or `net6.0`.

**Comment by pjanotti** [comment]
@rajkumar-rangaraj is the goal to handle the failure graceful or to fully support `netcoreapp3.1` and `net50`?

**Comment by Kielek** [comment]
See https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/c44723ae202bd908e978d2ff861228091cbe2037/CHANGELOG.md?plain=1#L19 for current main version

**Comment by rajkumar-rangaraj** [comment]
> @rajkumar-rangaraj is the goal to handle the failure graceful or to fully support `netcoreapp3.1` and `net50`?

@pjanotti goal is to fail gracefully instead of crashing the process.

**Comment by pellared** [comment]
@rajkumar-rangaraj What do you mean by " fail gracefully"?

1. human readable failure message and crash the application
2. log failure and continue without instrumentation

Currently we decided to:

> Initialization errors, usually caused by invalid configuration, are logged and crash the application.

From: https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/main/docs/design.md#error-handling

**Comment by rajkumar-rangaraj** [comment]
From the exception stack, user won't be able to identify that the issue was caused by auto-instrumentation. Additionally, we won't be able to log an error, as the startup was not initialized. So we should consider adding a failure message and continue without instrumentation.

**Comment by pellared** [comment]
SIG meeting: We will try to address it even in `0.5.0` release. We will also try to rename the directory names used in startuphook/store from `net6.0` to `net`
