### ISSUE TITLE
Remove unused references from AdditionalDeps

### ISSUE THREAD

**Issue by rajkumar-rangaraj** [open-telemetry/opentelemetry-dotnet-instrumentation#1645]
.NET Core 3.1 and .NET 5.0 support had been removed. We need to evaluate and check if below package reference are needed for .NET 6.0/7.0. Removing these will reduce the package size with a reduction in `store` folders.

```
<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="6.0.2" />
<PackageReference Include="Microsoft.Extensions.Logging.Configuration" Version="6.0.0" />
```

**Comment by Kielek** [comment]
@rajkumar-rangaraj, could you please check #1647?
Especially following commits
https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/1647/commits/60f149b87eeae75d84a8a53c1b216e5add05efe3
https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/1647/commits/5324fc864f7888bb7f3e2f5d05c5fa023f707071
https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/1647/commits/e650835193fff12cf59f2c7c8c4ae1e3ae7e6d6f

**Comment by Kielek** [comment]
Handled by #1647.
