### ISSUE TITLE
Add support for ElasticsearchClient instrumentation

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-dotnet-instrumentation#1688]
Use https://github.com/open-telemetry/opentelemetry-dotnet-contrib/tree/main/src/OpenTelemetry.Instrumentation.ElasticsearchClient

**Comment by Kielek** [comment]
Please check if there is native Otel support in 8.0 version.

**Comment by Kielek** [comment]
There are 2 types of ElasticClient
Old one: https://www.nuget.org/packages/NEST
New one: https://www.nuget.org/packages/Elastic.Clients.Elasticsearch

The new one has native support for OpenTelemetry by ActivitySource: https://github.com/elastic/elasticsearch-net/blob/8.0.0/src/Elastic.Clients.Elasticsearch/Client/ElasticsearchClient.cs#L25

Old one requires manual registration. I think we should support (for now) only 8.0.0+ version and do not bring any new dependency to the code.

**Comment by Kielek** [comment]
Ref: https://github.com/open-telemetry/opentelemetry-dotnet-contrib/issues/865
