### ISSUE TITLE
Add a badge for CI status and CodeCov

### ISSUE THREAD

**Issue by KKelvinLo** [open-telemetry/opentelemetry-dotnet-instrumentation#169]
**Is your feature request related to a problem?**
Most of the existing OpenTelemetry repositories display a badge for CI status and code coverage. In an effort to have the dotnet-instrumentation repository to be up to date and consistent with the other established SDKs and repositories, there should be a status tracking badge in the main README.md file.

**Describe the solution you'd like.**
As a developer contributing to OpenTelemetry, I recommend adding a CI status and code coverage percentage badge at the top of the README document of the dotnet-instrumentation repository. Code coverage and CI badges are a common feature of many modern open source projects, which improves readability and convenience to developers. By adding CI and code coverage badges to the README.md, with a quick scan, any observer will be able to know the status of the repository.

cc: @alolita

**Comment by pellared** [comment]
## CI status badge

We have Azure Pipelines and GitHub actions. Not sure if we can make a single badge that would combine it. Is the commit status not good enought?

![image](https://user-images.githubusercontent.com/5067549/119041831-62a3fc80-b9b7-11eb-9984-d798471eea1b.png)


## Code Coverage badge

This repository is mostly tested using integration tests that do not capture code coverage. It is not possible to reliably test .NET auto-instrumentation with unit tests. I guess the same story is for: https://github.com/open-telemetry/opentelemetry-java-instrumentation

**Comment by pellared** [comment]
Closing per SIG meeting agreeement.
