### ISSUE TITLE
Update Examples.AspNetCoreMvc and Examples.Vendor.Distro project with plugin's ConfigureOptions

### ISSUE THREAD

**Issue by rajkumar-rangaraj** [open-telemetry/opentelemetry-dotnet-instrumentation#1691]
Both `Examples.AspNetCoreMvc` and `Examples.Vendor.Distro` projects demonstrate the plugin. It would be apt to update these examples to show the usage of `ConfigureOptions`. We could also update the `/docs/plugins.md` to show an example link to one of these projects.

**Comment by Kielek** [comment]
@pellared, as I remember you have a plan to rework most of the examples.

**Comment by pellared** [comment]
https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/issues/1388 

I want to start working on it tomorrow 😉 
I hope to finish it by end of this week.

**Comment by pellared** [comment]
I decided just to have `Initializing` in https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/main/examples/playground/AspNetCoreMvc/OtelSdkPlugin.cs to decrease the maintainability burden. Do you think it is good enough?

**Comment by Kielek** [comment]
It is good enough. Closing.
