### ISSUE TITLE
Error executing automatic instrumentation shell scripts inside a slim docker image

### ISSUE THREAD

**Issue by lucasoares** [open-telemetry/opentelemetry-dotnet-instrumentation#1694]
Hello. I'm trying to test the automatic instrumentation inside a docker image but the instrument.sh contains invalid string comparison and can't be interpreted by the shell in a bullseye-slim image.

![image](https://user-images.githubusercontent.com/10624972/204684689-a30999ab-242b-4121-be0d-4ce489b9dae8.png)

There is any workaround?

Thank you.

**Comment by lucasoares** [comment]
I just changed to use bash instead of dot annotation :eyes:

**Comment by pellared** [comment]
Yeah `RUN . [...]` does not seem to make sense 😉

**Comment by lucasoares** [comment]
> `RUN . [...]` does not seem to make sense wink

It actually makes sense, but it will use the /bin/sh instead of /bin/bash to execute the script and the equality operators will fail

**Comment by pellared** [comment]
`instrument.sh` sets the env vars in the current shell session. Each `RUN` creates a new "layer" and is executed in a new session. That is why it does not make sense 😉
