### ISSUE TITLE
WCF instrumentation does not work with release 0.5.0

### ISSUE THREAD

**Issue by muhaook** [open-telemetry/opentelemetry-dotnet-instrumentation#1704]
# Bug Report

## Symptom

**Describe the bug**
WCF instrumentation does not work with release 0.5.0. I noticed lazy instrumentation was applied to WCF in this release, and the required assembly is [System.ServiceModel.Primitives](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/c7781798ac34d38f1e4f98e0e163ed1a7d1470a3/src/OpenTelemetry.AutoInstrumentation/Loading/Initializers/WcfInitializer.cs#L28). 
in my WCF sample, that assembly didnot get loaded (attached please find a screenshot). Can we make change to the WCF required assembly, or make the assembly name configurable using an env variable to override the default value?
![wcf_lazy_instr](https://user-images.githubusercontent.com/52417764/205276318-69ca13b1-1de4-4b62-a2f5-4d70c78fc6f3.png)

**Expected behavior**
WCF instrumentation should work

**Runtime environment:**

- OpenTelemetry Automatic Instrumentation version: 0.5.0
- OS: Windows 10
- .NET version: .NET Framework 4.6.2

**Comment by pellared** [comment]
@RassK PTAL. Maybe it should be `System.ServiceModel` instead?

**Comment by dszmigielski** [comment]
I was not able to reproduce that. Integration tests for WCF pass successfully. I tested manual installation of 0.5.0 version as well with our sample applications and it works as well - spans were created and sent to collector correclty.

![image](https://user-images.githubusercontent.com/77062266/207561001-815bf5f0-e059-495a-8deb-eae78ed8c1b0.png)

**Comment by dszmigielski** [comment]
I will proceed to try it on other app 😬
