### ISSUE TITLE
AspNetCore instrumentation under .NET Framework 4.6.2

### ISSUE THREAD

**Issue by Kielek** [open-telemetry/opentelemetry-dotnet-instrumentation#1727]
# Feature Request

**Are you requesting automatic instrumentation for a framework or library? Please describe.**

Support AspNetCore instrumentation under .NET Framework 4.6.2.

**Additional context**
We have lazy loading implemented, so it should works.
Manual tests while working on GraphQL passed.

Notes: Consider to separate configuration value for AspNet and AspNetCore.

**Comment by pjanotti** [comment]
SIG: evaluate if we should really support this, related comment on #1646

**Comment by RassK** [comment]
Such extreme cases could be left for manual instrumentation (use SDK directly), then there is much higher chance it will work.

**Comment by Kielek** [comment]
Discussed with @pellared, I agree that it is to extreme. Closing.
