### ISSUE TITLE
GraphQL - extend set of supported versions

### ISSUE THREAD

**Issue by Kielek** [open-telemetry/opentelemetry-dotnet-instrumentation#1741]
# Feature Request

**Are you requesting automatic instrumentation for a framework or library? Please describe.**

Extend set of supported version for GraphQL.
For now, supported versions are [2.3.0-3.0.0).
There is bunch of newer versions, up to 7.2.1 https://www.nuget.org/packages/GraphQL

**Comment by pellared** [comment]
How about creating an issue in https://github.com/graphql-dotnet/graphql-dotnet that would ask for creating activities and metrics compliant with OTel semantic conventions?

**Comment by Kielek** [comment]
Created https://github.com/graphql-dotnet/graphql-dotnet/issues/3448

**Comment by Kielek** [comment]
GraphQL has native support for OTel from 7.5.0+. Closing this issue.
