### ISSUE TITLE
Add C# and C++ Scanning to CodeQL workflow

### ISSUE THREAD

**Issue by KKelvinLo** [open-telemetry/opentelemetry-dotnet-instrumentation#178]
**Issue**

The current code scanning for CodeQL only scans the C# portion of the code. As the repository also has C++ code, it would be necessary to add a C++ code scan.

[Relevant Pull Request](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/170)

**Comment by pellared** [comment]
We have noticed that there are problems with C# analysis.

**Comment by pellared** [comment]
@alolita Is this a requirement from OTel specs?
