### ISSUE TITLE
Tagging - make properties non-nullable

### ISSUE THREAD

**Issue by Kielek** [open-telemetry/opentelemetry-dotnet-instrumentation#1862]
seems a good candidate for refactor. If we leave properties / tags out that have `null` value, then there will be less calls that do nothing.

_Originally posted by @RassK in https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/1861#discussion_r1054301950_

**Comment by RassK** [comment]
Update: Seems that the nullable is still in the right place, due the `IProperty` must reflect the getter of the actual property. If actual property is nullable, then getter must also reflect nullable. Empty values are filtered out at the last moment before the export happens. 

Closing currently, as I don't see any benefits in refactor.
