### ISSUE TITLE
Add Log support to StartupHook and AspNetCoreBootstrapper

### ISSUE THREAD

**Issue by rajkumar-rangaraj** [open-telemetry/opentelemetry-dotnet-instrumentation#1864]
Both `OpenTelemetry.AutoInstrumentation.StartupHook` and `OpenTelemetry.AutoInstrumentation.AspNetCoreBootstrapper` writes the status to `EventSource`. Additional tools like `logman`, `dotnet-trace`, `Perfview`, etc., are needed to capture these event source logs.

We have an in-built file-based logging in [`OpenTelemetry.AutoInstrumentation`](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/tree/main/src/OpenTelemetry.AutoInstrumentation/Logging) project. We should extend this feature to StartupHook and AspNetCoreBootstrapper to write the logs to file system for easier debugging.

**Comment by pellared** [comment]
Maybe we can move https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/173be32ae159360f41d411fc9a81216d8beeede6/src/OpenTelemetry.AutoInstrumentation/Instrumentation.cs#L104-L105 sooner?
