### ISSUE TITLE
Add arm64 build for native components

### ISSUE THREAD

**Issue by pjanotti** [open-telemetry/opentelemetry-dotnet-instrumentation#1865]
We removed this quite some time ago since the CI used at the time didn't support arm64. As time goes by arm64 is getting more popular and we should build our native components to support arm64.

**Comment by pjanotti** [comment]
https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/1869

**Comment by DerrickMartinez** [comment]
Is there any guidance on how to build it with arm64 support?

**Comment by baterja** [comment]
https://github.blog/changelog/2023-10-30-accelerate-your-ci-cd-with-arm-based-hosted-runners-in-github-actions/

arm64 runners are there. What about reviving this thread? :)

**Comment by RassK** [comment]
@baterja we just got some from actuated, see https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/3277
