### ISSUE TITLE
Move OpenTelemetry.AutoInstrumentation.Native.so / OpenTelemetry.AutoInstrumentation.Native.dylib to a directory

### ISSUE THREAD

**Issue by rajkumar-rangaraj** [open-telemetry/opentelemetry-dotnet-instrumentation#1866]
Currently, `OpenTelemetry.AutoInstrumentation.Native.dylib` and `OpenTelemetry.AutoInstrumentation.Native.so` are placed in `tracer-home`. Proposal is to move this to a new directory in `tracer-home`.

For example, we could create a folder named `misl` and place `OpenTelemetry.AutoInstrumentation.Native.so` in it.  Conceptually this will make it easier to pack with Nuget.

**Comment by RassK** [comment]
Had exactly the same idea, but I was thinking of reusing current logic as done for windows.
Alpine: alpine-x64
MacOS: macos-x64

Just the general linux naming might be more tricky, if we use ubuntu-x64 it might confuse as too restrictive for others (debian etc)

**Comment by pellared** [comment]
How about `linux-glibc` and `linux-musl` instead of ubuntu/alpine?

**Comment by RassK** [comment]
just the difference is that win has architectural naming but linux would have package based naming, consistency seems to be broken.

**Comment by pellared** [comment]
We  can have `linux-glibc-x64` and `linux-musl-x64` 😉 I was more concerned about using Alpine and Ubuntu in names.

**Comment by pjanotti** [comment]
Although is not a requirement for these folders it will be good to use the dotnet [RIDs](https://learn.microsoft.com/en-us/dotnet/core/rid-catalog). This way we leverage users familiarity with the RIDs and help it align with our future NuGet packages.
