### ISSUE TITLE
Document the latest release in opentelemetry.io

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-dotnet-instrumentation#1876]
Once we have `0.5.0` as our production-quality release we should copy/move/sync the documentation under https://opentelemetry.io/docs/instrumentation/net/automatic/.

Take notice that pre-releases (e.g. beta and RC releases) should not be documented under opentelemetry.io.

**Comment by pellared** [comment]
This could be implemented as submodules: https://github.com/open-telemetry/opentelemetry.io/tree/main/content-modules

**Comment by pellared** [comment]
@open-telemetry/docs-maintainers do you have any preference on how to implement it?

**Comment by cartermp** [comment]
We prefer not do do submodules if possible - we're going to propose to the Go SIG in the new year to move away from them. Only the spec will remain as a submodule.

We can also set up a bot that automatically bumps the latest version, which we have for the Java agent and collector now too.

**Comment by Kielek** [comment]
See also https://github.com/open-telemetry/opentelemetry.io/issues/3150

**Comment by rajkumar-rangaraj** [comment]
Should we also update - https://opentelemetry.io/docs/instrumentation/net/automatic/?

**Comment by Kielek** [comment]
Done in scope of https://github.com/open-telemetry/opentelemetry.io/pull/3222
