### ISSUE TITLE
Get rid of wrapper.action in bytecode instrumentation

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-dotnet-instrumentation#1883]
Do we want to support any other type of action? AFAIK this is the only one we support. See https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/345beca02a83639c82487828eec59c8100c9afdf/src/OpenTelemetry.AutoInstrumentation.Native/integration_loader.cpp#L203

_Originally posted by @pellared in https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/1881#discussion_r1060158057_

**Comment by RassK** [comment]
Since replacing call target got removed and nothing better is in sight, I guess a cleanup is a good idea.
