### ISSUE TITLE
Restore proper support for custom SDK

### ISSUE THREAD

**Issue by pjanotti** [open-telemetry/opentelemetry-dotnet-instrumentation#1887]
This is one of our [supported scenarios](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/main/docs/design.md#supported-scenarios) and right now it is mixed up with enabling instrumentations via, e.g.: `OTEL_DOTNET_AUTO_TRACES_ENABLED`.

In the past we had dedicated env vars for that, it seems that we should return to that. We may need to track/document which env vars will not have an effect when a custom SDK is used. This should be supported for all signals.

The old env vars supporting the scenario were removed in release v0.5.0, see the [release notes](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/releases/tag/v0.5.0).

**Comment by pellared** [comment]
Slack thread for reference: https://cloud-native.slack.com/archives/C01NR1YLSE7/p1672653250224899

It might be possible that this can be hacked by setting

```
OTEL_TRACES_EXPORTER=none
OTEL_METRICSS_EXPORTER=none
OTEL_LOGSS_EXPORTER=none
```

This should disable the exporters created by auto-instrumentation while it should still add automatically some instrumentation libraries

**Comment by pjanotti** [comment]
SIG: add test to ensure that we don't break it again.
