### ISSUE TITLE
Auto-Instrumentation deployed via k8s operator is not working

### ISSUE THREAD

**Issue by pjanotti** [open-telemetry/opentelemetry-dotnet-instrumentation#1888]
Reported via slack, see https://cloud-native.slack.com/archives/C01NR1YLSE7/p1671814612167889

```
Unhandled exception. System.ArgumentException: Startup hook assembly '/otel-auto-instrumentation/net/OpenTelemetry.AutoInstrumentation.StartupHook.dll' failed to load. See inner exception for details.
 ---> System.IO.FileNotFoundException: Could not load file or assembly '/otel-auto-instrumentation/net/OpenTelemetry.AutoInstrumentation.StartupHook.dll'. The system cannot find the file specified.
File name: '/otel-auto-instrumentation/net/OpenTelemetry.AutoInstrumentation.StartupHook.dll'
   at System.Runtime.Loader.AssemblyLoadContext.<LoadFromPath>g____PInvoke|5_0(IntPtr ptrNativeAssemblyBinder, UInt16* ilPath, UInt16* niPath, ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at System.StartupHookProvider.CallStartupHook(StartupHookNameOrPath startupHook)
   --- End of inner exception stack trace ---
   at System.StartupHookProvider.CallStartupHook(StartupHookNameOrPath startupHook)
   at System.StartupHookProvider.ProcessStartupHooks()
```

On one hand this exception indicates that `DOTNET_STARTUP_HOOKS` is pointing to the wrong folder, OTOH the user is reporting that it works correctly with different runtime version. It may be related to the k8s operator, but, let's investigate via this issue before deciding on the best action here.

**Comment by avadhut123pisal** [comment]
Looks like auto-instrumentation related files are not present on the given location in application container. Need to check if the init container got injected in the pod properly. So, init container and volume mount related information from app pod definition would be helpful.

**Comment by Kielek** [comment]
I agree with @avadhut123pisal, it will be great to have more information about repro steps.
I was able to create simple application based on .NET 6 hosted in docker based on mcr.microsoft.com/dotnet/sdk:6.0-jammy.

It is working as expected with opentelemetry-collector 0.66.0 (and autoinstrumentation image v 0.5.0).

Is there any chance to prepare minimal repro steps https://stackoverflow.com/help/minimal-reproducible-example?

**Comment by Kielek** [comment]
Information from Blake Romano:
  [1 day ago](https://cloud-native.slack.com/archives/C01NR1YLSE7/p1675690909606069?thread_ts=1671814612.167889&cid=C01NR1YLSE7)
I wanted to follow up on this. This issue seems to be isolated to the .NET versions of 0.3.0-beta and 0.5.0. When I upgraded the instrumentation CRD to 0.5.0 from 0.3.0-beta no longer did we notice this issue.
