### ISSUE TITLE
Support for monitoring sharepoint

### ISSUE THREAD

**Issue by nrcventura** [open-telemetry/opentelemetry-dotnet-instrumentation#190]
**Are you requesting automatic instrumentation for a framework or library? Please describe.**
- Framework or library name : Sharepoint

**Is your feature request related to a problem? Please describe.**
This feature request is meant to explore how we could support monitoring a system like Sharepoint.

**Describe the solution you'd like**
Sharepoint allows you to extend its functionality by adding additional WCF services. To support Sharepoint we would need to be able instrument WCF services, and Asp.Net requests. We need to find out if Sharepoint already includes a dependency on System.Diagnostics.DiagnosticSource. If it does include that dependency, is there a way to configure a binding redirect so that we can use an appropriate version of that dependency? If someone extends Sharepoint, and includes that dependency, how can we ensure that a binding redirect gets configured.

**Comment by pellared** [comment]
This is about supporting the scenario where the customer does not have access to the build.

**Comment by Kielek** [comment]
After discussion with @nrcventura we can close it for now.
We do not have exact data how many customer would like to use it. What is more, for now we do not have access for testing env.
It can be reopened if any customer directly needs it.
Probably support provided by the WCF instrumentation should be sufficient to handle this scenario.
