### ISSUE TITLE
GAC - install and uninstall clarification 

### ISSUE THREAD

**Issue by Kielek** [open-telemetry/opentelemetry-dotnet-instrumentation#1906]
Hi @Kielek @pellared , with [v0.5.1-beta.3](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/releases/tag/v0.5.1-beta.3), I can not reproduce this issue, even without registering netfx assemblies in GAC. 

I have 2 quick questions about registering / unregistering assemblies in GAC:
- Some assemblies below did not get added to GAC. is it because they are not strong named? any impact if they are not showing up in GAC?
  - netstandard.dll
  - grpc_csharp_ext.x64.dll
  - grpc_csharp_ext.x86.dll
- if I have an assembly already in GAC before installing dotnet auto-instrumentation, and this assembly is duplicated with an assembly under tracer-home/netfx/ folder. what will happen to it after installing dotnet auto-instrumentation? and what will happen to it after `uninstalling` auto-instrumentation? will it be removed from GAC by auto-instrumentation uninstall?

for info, I used this command to register assemblies in GAC:
```
        # Register .NET Framweworks dlls in GAC
        [System.Reflection.Assembly]::Load("System.EnterpriseServices, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a") | Out-Null
        $publish = New-Object System.EnterpriseServices.Internal.Publish 
        $dlls = Get-ChildItem -Path .\netfx\ -Filter *.dll -File
        foreach ($dll in $dlls) {
            $publish.GacInstall($dll.FullName)
        }
```
and I used command below to unregister assemblies from GAC:
```
    [System.Reflection.Assembly]::Load("System.EnterpriseServices, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a") | Out-Null
    $publish = New-Object System.EnterpriseServices.Internal.Publish 
    $dlls = Get-ChildItem -Path .\netfx\ -Filter *.dll -File
    foreach ($dll in $dlls) {
        $publish.GacRemove($dll.FullName)
    }
```
before auto-instrument install, my GAC: 
[gac.1.txt](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/files/10355048/gac.1.txt)
after auto-instrument install, my GAC:
[gac.2.txt](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/files/10355052/gac.2.txt)

_Originally posted by @muhaook in https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/issues/1858#issuecomment-1372619180_

**Comment by muhaook** [comment]
Thanks @Kielek , I tested 0.5.1-beta3 without registering to GAC and it seemed working well. I wonder anything/featue we will lose if we do not register to GAC?

**Comment by pjanotti** [comment]
Hi @muhaook,

>I wonder anything (new features/bug fixes) we will lose if we do not register to GAC?

1. If there is an assembly that is instrumented via [__monkey patching__](https://en.wikipedia.org/wiki/Monkey_patch#:~:text=Monkey%20patching%20is%20a%20technique,Python%2C%20Groovy%2C%20etc.)) and that assembly is loaded as domain-neutral we need the instrumentation assembly to be in the GAC so we can also load it as domain-neutral. Notice that you can load assemblies as domain-neutral directly into your app without registering them in the GAC, however, for injecting code it would be much harder. You can see the effect of lacking the registration by removing this [line](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/e43f28363d6988882430d6c3a11901ab52eab7dc/test/IntegrationTests/DomainNeutralTests.cs#L52) in the `DomainNeutralTests` class.
2. For strong-named apps if they ship some version of an assembly used by OTel Auto-Instrumentation the automatic version redirect will fail if the version that we are redirecting to, the one that we ship, is not in the GAC. In other words, redirection in this case is only possible for assemblies that are registered in the GAC.

> Some assemblies below did not get added to GAC. is it because they are not strong named? any impact if they are not showing up in GAC?
netstandard.dll
grpc_csharp_ext.x64.dll
grpc_csharp_ext.x86.dll

The `grpc_cshart_*.dll` ones are native DLLs and can't be registered on the GAC. The `netstandard.dll` is only a redirector itself and it is shipped with any app that needs it. Perhaps we should skip those silently to avoid any confusion about them.

> if I have an assembly already in GAC before installing dotnet auto-instrumentation, and this assembly is duplicated with an assembly under tracer-home/netfx/ folder. what will happen to it after installing dotnet auto-instrumentation? and what will happen to it after uninstalling auto-instrumentation? will it be removed from GAC by auto-instrumentation uninstall?

I'm actually not sure in this case, see [here](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/1884#discussion_r1060767393). We need to confirm this and address as appropriate.

Let's know if you still have questions about it.

**Comment by muhaook** [comment]
Thanks @pjanotti , very helpful! 
Closing this issue..

**Comment by pjanotti** [comment]
@muhaook I did an edit to my earlier comment to clarify what happens when auto-instrumentation removes the assemblies from the GAC.

I'm keeping this open for now to track some pending doc updates.
