### ISSUE TITLE
Centralize dependency package versions

### ISSUE THREAD

**Issue by xiang17** [open-telemetry/opentelemetry-dotnet-instrumentation#1974]
# Feature Request

**Describe the solution you'd like**

Centralize the package versions like [opentelemetry repository](https://github.com/open-telemetry/opentelemetry-dotnet/blob/f98f8fe166d59de008309e6e1ea3afaa5379afd5/build/Common.props#L24-L56).

**Additional context**
The dependency packages' versions are scattered around in the repository. When upgrading OTel versions (#1967), multiple edits are needed for each dependency package.

**Comment by RassK** [comment]
OpenTelemetry dotnet way seems to drop dependabot support. It will be specially important with #1824

**Comment by pellared** [comment]
The edits are: nuspec, csproj, docs, native code. Probably we could make some something to "merge" nuspec and csproj. But, like @RassK mentioned, we need dependabot working to make sure that we are notified in this repository about possible bumps.
