### ISSUE TITLE
Avoid benign GAC warnings logged by install/uninstall

### ISSUE THREAD

**Issue by pjanotti** [open-telemetry/opentelemetry-dotnet-instrumentation#1984]
Running the PowerShell install/uninstall ends up logging warning events to the Windows Event Logger that are benign and not actionable by the user:

![image](https://user-images.githubusercontent.com/5600755/212187243-3603c5f7-6d8e-4acd-a040-7ed674587f6d.png)

This issue is a follow-up to #1906

**Comment by pellared** [comment]
Do you have any preference on how to implement it?
I see two possibilities:

1. Use https://learn.microsoft.com/en-us/dotnet/standard/assembly/identify#using-the-pereader-class.

    Pros:
    - should not require a lot of maintenance in future

    Cons:
    - would probably not cover `netstandard.dll`. I guess this one would need special handling.
    - Would require using https://www.nuget.org/packages/System.Reflection.Metadata/ inside the powershell module

2. Have a "exclude list" which would currently be the 3 assemblies.

    Pros:
    - no dependencies and possibly best performance
    
    Cons:
    - would require more maintaince (updating the exclude list)

We could consider also writing a PowerShell unit test to check if after using the module there are no new errors or warnings in the Windows Event Log.

**Comment by rajkumar-rangaraj** [comment]
It's worth exploring option 1, at a different it could help in different places too.

**Comment by pellared** [comment]
I spend a few hours trying the option 1, but there are too many obstacles to make it worth in my opinion. Example problems:

- we would have to download all needed packages (together with dependencies) and then remove them at the end. See: https://github.com/OneGet/oneget/issues/475
- We would have to `Register-PackageSource` and later remove it.
- For some reasons I have failed to have a working `Install-Package` which worked fine and downloaded exactly what I wanted.

Notable article: https://endjin.com/blog/2020/12/how-to-consume-a-nuget-package-in-powershell Maybe someone else would have more luck...
