### ISSUE TITLE
Potential small optimization to StartupLogger

### ISSUE THREAD

**Issue by pjanotti** [open-telemetry/opentelemetry-dotnet-instrumentation#1997]
Per @pellared [comment](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/1972#discussion_r1071908111) we should benchmark and consider if it is worth changing the code. The benchmark should include the time to create and insert the data into the type used to clean up the invalid chars.

**Comment by xiang17** [comment]
I'm working on adding a Benchmark for this. Can you assign this to me?
