### ISSUE TITLE
Split AspNet and AspNetCore instrumentation

### ISSUE THREAD

**Issue by Kielek** [open-telemetry/opentelemetry-dotnet-instrumentation#1999]
Current configuration can be misleading. We should split AspNet  to AspNet and AspNetCore

https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/aea9a0dbe70d5deb4aa9e65731e2c9d65587646c/src/OpenTelemetry.AutoInstrumentation/Configuration/TracerInstrumentation.cs#L32
Check if it should be done also for Metrics.

**Comment by pellared** [comment]
We can also add test  ASP.NET Core on .NET Framework 😉 

Related to: https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/issues/1727

**Comment by pjanotti** [comment]
SIG: closing, if we have demand will re-open it.

**Comment by pellared** [comment]
SIG meeting notes:
We decided to close it as the scenario of hosting ASP.NET Core is not supported for some time. This is a popular scenario and it could even bring trouble if it would happen to not work at all in future. Also the ASP.NET vs ASP.NET Core distinction is not intuitive for users (even for .NET devs, not mentioning SRE's not familiar with .NET).

**Comment by pellared** [comment]
Related https://github.com/open-telemetry/opentelemetry-dotnet/issues/4126#issue-1564957775

Looks like ASP.NET Core 2.1 is still supported on .NET Framework. Reference: https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core

Reopening for sake of having a conversation during the SIG meeting.
