### ISSUE TITLE
Add  `.NET Auto` to Compliance of Implementations with Specification

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-dotnet-instrumentation#2000]
Add `.NET Auto` to [Compliance of Implementations with Specification](https://github.com/open-telemetry/opentelemetry-specification/blob/main/spec-compliance-matrix.md) before going GA.

**Comment by carlosalberto** [comment]
That's correct, the spec compliance is more about the API/SDK. Is there any of this functionality in the auto-instrumentation package instead of the SDK? e.g. environment variables support? Otherwise, yes, we can close this.
