### ISSUE TITLE
Add a manifest to the Powershell module

### ISSUE THREAD

**Issue by pjanotti** [open-telemetry/opentelemetry-dotnet-instrumentation#2003]
This will help track the exact version being used by the user and so on.

**Comment by RassK** [comment]
I was also researching to add a manifest, but until manifest cannot be embedded to the main module, there is no point - I guess nobody is going to download the manifest separately. 

I can see one workaround, so we actually publish this module to PowerShell Gallery, I guess then behind the scenes PowerShell downloads the manifest also.

**Comment by pjanotti** [comment]
SIG: tracking via #2079
