### ISSUE TITLE
Document non-stable references

### ISSUE THREAD

**Issue by Kielek** [open-telemetry/opentelemetry-dotnet-instrumentation#2007]
Document non-stable references.

Consider to disable non-stable features by default.

Inform that as main functionalities are stable, but some of them are experimental (most of the instrumentations).

**Comment by pellared** [comment]
We should additionally mark which of our functionalities and configuration is not stable. I would say that all settungs which has `OTEL_DOTNET_AUTO_*` prefix can be marked as not-stable as these things are:
- not defined by the OTel spec (e.g. `OTEL_DOTNET_AUTO_TRACES_ENABLED`)
- related to settings not exposed by OTel .NET SDK (e.g. `OTEL_DOTNET_AUTO_LOGS_INCLUDE_FORMATTED_MESSAGE`)
- internal details that may change (e.g. `OTEL_DOTNET_AUTO_INTEGRATIONS_FILE`)

Probably we should only mark the configuration and functionality defined in OTel Spec as stable.
