### ISSUE TITLE
GAC operations don't work with pwsh shell

### ISSUE THREAD

**Issue by pjanotti** [open-telemetry/opentelemetry-dotnet-instrumentation#2018]
My default shell on Windows is `pwsh` that by default runs on .NET, not on .NET Framework like the `Windows Powershell`. Due to this, it fails to correctly install assemblies on the GAC since it can't find a native file needed for the operation: `fusion.dll`. This is the error message:

```PowerShell
Install-OpenTelemetryCore: Could not setup OpenTelemetry .NET Automatic Instrumentation! Exception calling "GacInstall" with "1" argument(s): "C:\Program Files\WindowsApps\Microsoft.PowerShell_7.3.1.0_x64__8wekyb3d8bbwe\fusion.dll"
```

I don't think there is much that we can do besides document the issue and make clear that the user should use `Windows Powershell` not the newer versions. Anyway, let's take a quick look when we have a chance to see if it is possible to cheaply workaround or not.

**Comment by pjanotti** [comment]
At a minimum, we could use a test like `$PSVersionTable.CLRVersion -eq $null` to determine if the module is running on the proper shell or not and give the message instead of erroring out.

**Comment by pellared** [comment]
We could also use `$PSVersionTable.PSEdition` which should be `Desktop`. Probable the best would be to check it using the module manifest: https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_powershell_editions?view=powershell-7.3#the-compatiblepseditions-module-manifest-field

However, I feel that having it just documented could be good enough.

**Comment by pellared** [comment]
Fixed per https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/2078

**Comment by mrwensveen** [comment]
I stumbled on this while following https://opentelemetry.io/docs/zero-code/net/getting-started/. There is no mention of Windows PowerShell, which I feel would have been useful.

**Comment by Kielek** [comment]
@mrwensveen, would you like to corbibute to the documentation? I will be happy to review

**Comment by martincostello** [comment]
Just ran into this myself. Have opened a docs PR to try and make it so fewer users fall into the pit of failure with this here: https://github.com/open-telemetry/opentelemetry.io/pull/7140
