### ISSUE TITLE
Clearer setup instructions

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-dotnet-instrumentation#2076]
### Discussed in https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/discussions/2075

<div type='discussions-op-text'>

<sup>Originally posted by **ramanjaneyagupta** January 24, 2023</sup>
I am new to the dotnet and trying to follow the instructions provided here 

https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation

for windows, it is so confusing and steps are not clear to me. and lets say i have very basic sample application it have the follwong lines code 

Console.WriteLine("Hello, World!");

var httpClient = new HttpClient();
var response = await httpClient.GetAsync("https://google.com/");
Console.WriteLine($"Response Status: {response.StatusCode}");

so if i want to add auto instrumentation could someone help with the proper steps that users(like me) can understand easily. 

I did for java and python and it is so clear for the auto instrumentation but for dotnet i am fidning hardtime to setup.

Help would be appreciated.</div>

**Comment by pellared** [comment]
We should probably make the `README.md` more user-friendly.

I think the https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation#shell-scripts needs some more comments regarding the used commands. Also the example uses `dotnet run` which is not currently working (sic!).

Probably in https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation#powershell-module-windows should have a minimal example for a CLI app. Maybe also more comments?

@ramanjaneyagupta @theletterf We are open for any suggestions.

**Comment by pjanotti** [comment]
The main thing is that right now we are not working well with `dotnet` CLI and this is the typical and straightforward path for someone new to .NET. At this moment we have to break this flow and do things like exclude `dotnet` CLI ask for a `dotnet` build and then set up all env vars and directly run the executable.

**Comment by pjanotti** [comment]
As a temporary and short workaround, the instructions should tell to use a separate shell to run the `dotnet` CLI and build the application and a separate one to run the instrumented version.

**Comment by pjanotti** [comment]
Related https://cloud-native.slack.com/archives/C01NR1YLSE7/p1674763012675559
