### ISSUE TITLE
Support Systems with glibc 2.17-2.29

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-dotnet-instrumentation#2083]
Red Hat Linux and CentOS 7 has `glibc` version `2.17`.
Red Hat Linux and CentOS 8 has `glibc` version `2.28`.

`pthread_cond_clockwait` was introduced in version `2.30`. Reference: https://lwn.net/Articles/795127/

We should probably support this distro as .NET supports it: https://github.com/dotnet/core/blob/main/release-notes/6.0/supported-os.md

Slack thread: https://cloud-native.slack.com/archives/C01NR1YLSE7/p1674679829575859

**Comment by RassK** [comment]
I'm not sure we can say that we support RHEL at all before we have infrastructure to run integration tests on top of that platform.
I can be in the "soft support" list, is known to work but not verified / monitored.

**Comment by muhaook** [comment]
for info, I run auto-instrumentation on glibc 2.17, Oracle Linux 7.6, it is working well
```
$ ldd --version
ldd (GNU libc) 2.17
Copyright (C) 2012 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.

$ lsb_release -a
LSB Version:    :core-4.1-amd64:core-4.1-ia32:core-4.1-noarch:cxx-4.1-amd64:cxx-                                   4.1-ia32:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-ia32:desktop-4.1-noarch:la                                   nguages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID: OracleServer
Description:    Oracle Linux Server release 7.6
Release:        7.6
Codename:       n/a
```

**Comment by pellared** [comment]
> I'm not sure we can say that we support RHEL at all before we have infrastructure to run integration tests on top of that platform. It can be in the "soft support" list, is known to work but not verified / monitored.

We can run tests on CentOS. It should be good enough.

**Comment by pjanotti** [comment]
Related issue #703
