### ISSUE TITLE
Env.vars. boolean - support only true/false case insensitive

### ISSUE THREAD

**Issue by Kielek** [open-telemetry/opentelemetry-dotnet-instrumentation#2089]
See https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/sdk-environment-variables.md#boolean-value

We should stop support `0` and `1`. For sure it is handled on native code part.

**Comment by pjanotti** [comment]
The minor issue in this is that CLR Profiler environment variables from `dotnet` do support `0` and `1`. Just an observation that we may need to add a notice about it somewhere in the docs.

**Comment by Kielek** [comment]
`COR_ENABLE_PROFILING` and `CORECLR_ENABLE_PROFILING` are strictly described in documentation than `1` is required value. Nothing to update.
