### ISSUE TITLE
Make instrumentation env. vars. fully caps-locked

### ISSUE THREAD

**Issue by Kielek** [open-telemetry/opentelemetry-dotnet-instrumentation#2094]
Can we do keys in all caps? this format is very unfriendly in UX wise, specially in Linux where a key's case sensitivity matters.

_Originally posted by @RassK in https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/2088#discussion_r1088857693_

**Comment by pjanotti** [comment]
Just the usual not about the Java precedent in this regard.
