### ISSUE TITLE
Build flakiness (at least in CI)

### ISSUE THREAD

**Issue by pjanotti** [open-telemetry/opentelemetry-dotnet-instrumentation#2097]
```terminal
GenerateNetFxTransientDependencies        Failed          0:20   // CommandValidationException: Unable to process the project `D:\a\opentelemetry-dotnet-instrumentation\opentelemetry-dotnet-instrumentation\src\OpenTelemetry.AutoInstrumentation\OpenTelemetry.AutoInstrumentation.csproj. Are you sure this is a valid .NET Core or .NET Standard project type?
```

Two occurrences of it:

https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/actions/runs/4027322476/jobs/6922907536#step:5:60

https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/actions/runs/4026372140/jobs/6920798432#step:5:60

It didn't repro locally but this may be a non-deterministic build.

**Comment by RassK** [comment]
Managed to catch failing sample. At the first sight nothing odd 🤔 

```
DotNetRunner - WorkingDirectory: D:\a\opentelemetry-dotnet-instrumentation\opentelemetry-dotnet-instrumentation\src\OpenTelemetry.AutoInstrumentation
DotNetRunner - Arguments: msbuild "D:\a\opentelemetry-dotnet-instrumentation\opentelemetry-dotnet-instrumentation\src\OpenTelemetry.AutoInstrumentation\OpenTelemetry.AutoInstrumentation.csproj" /t:Restore,GenerateRestoreGraphFile /p:RestoreGraphOutputPath="C:\Users\runneradmin\AppData\Local\Temp\tmp9122.tmp"
```

**Comment by pellared** [comment]
Looks like bad ordering of `GenerateNetFxAssemblyRedirectionSource`.

**Comment by RassK** [comment]
I have a branch to run it just after the Clean target, no difference.
Seems MSBuild restore is stuck. `Determining projects to restore...`

**Comment by pjanotti** [comment]
`GenerateNetFxAssemblyRedirectionSource` should run before `Restore`, but, it seems that the very first one should be `Clean` instead. Anyway, we may have to disable the target for the time being until we figure it out what is the issue.

**Comment by RassK** [comment]
Related issue: Dependabot cannot bump related packages.

**Comment by RassK** [comment]
Moving the target after `Restore` seems to do the trick, but I'm afraid that `--no-restore` ruins testing if CI adds some dependency to the list and instead crashes with the need to run restore. It's just a theory currently...

**Comment by RassK** [comment]
Seems no issues followed, closing.
