### ISSUE TITLE
Reduce Windows CI time

### ISSUE THREAD

**Issue by pjanotti** [open-telemetry/opentelemetry-dotnet-instrumentation#2127]
The build of Windows CI is almost doubling the time to run CI. It is expected for it to be a longer than other OSes because it includes the .NET Framework in build and tests. That said we should consider if it worth separating, at least the tests, in multiple runners to reduce the CI duration: currently around ~26 minutes, based on the other OSes we could have it ~15 minutes.

**Comment by rajkumar-rangaraj** [comment]
CI duration in Windows has increased to ~37 minutes. We might need to consider this on priority.
