### ISSUE TITLE
Sync production and integration tests environment for .NET Framework

### ISSUE THREAD

**Issue by RassK** [open-telemetry/opentelemetry-dotnet-instrumentation#2155]
### What

Currently .NET Framework integration tests are not using GAC but the PowerShell module is installing netfx dlls to GAC. 
This fixes some assembly versioning conflicts.

example dependabot PR: https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/2122

**Comment by pjanotti** [comment]
For the .NET Framework instrumentation to work properly with the version bump we need the assemblies installed in the GAC.
