### ISSUE TITLE
Download clang tools possible flakiness

### ISSUE THREAD

**Issue by RassK** [open-telemetry/opentelemetry-dotnet-instrumentation#2156]
### What

This issue is tracking possible failures of download-clang-tools.sh (Install Clang tools step).

`curl: (56) Recv failure: Connection was reset`

### Possible Solution

Hash and cache installed tools. 

### Tracking failures
https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/actions/runs/4074961771/jobs/7020745381

_(please update this list if there are new occurrences)_

**Comment by pellared** [comment]
It is unfortunate as we are already using `retry` to avoid such problems 😞 

https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/8f5fab811b5d71be5f432cc5ec777659143b0c9a/scripts/download-clang-tools.sh#L53

**Comment by RassK** [comment]
but we can still global cache the result? ... so need to hit rerun only if cache building fails.

**Comment by pjanotti** [comment]
Waiting for repros until 02/15

**Comment by zacharycmontoya** [comment]
Closing via SIG meeting
