### ISSUE TITLE
Treat paths for metrics and ActivitySource as namespaces that can be shortcutted

### ISSUE THREAD

**Issue by samsp-msft** [open-telemetry/opentelemetry-dotnet-instrumentation#2158]
When you use Open Telemetry to listen for metrics or activities, you need to specify the name of the provider. This means that there has to be a tight coupling between the monitoring tool and the application being monitored, in a way that is likely to be hard to discover, prone to errors, and a source of frustration as to why newly created ones don't show up.

Logging has taken the approach that it recommends using namespace style `a.b.c` for the naming, but then used that aspect to simplify specifying log levels so `System` will apply to all namespaces that start with the system prefix.

We should probably take the same approach with Metrics and ActivitySource.

So if you are developing a complex multi-project service, you don't need to enumerate the name of every Metric or ActivitySource that is used in the service as part of the root registration. It can be specified using a wildcard or prefix such as `ACME.Rocket` that will apply to all of the components involved in Wile E. Coyote's latest attempt to catch the Road Runner. 
 
Linking to https://github.com/dotnet/runtime/issues/81574 for the runtime and dotnet-counters

**Comment by Kielek** [comment]
Wildcards are supported
Please check for traces: 
https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/8feb82b96a0dafa8269933d2815d84c9c7db05c3/docs/manual-instrumentation.md?plain=1#L32-L35

The same behavior is for `OTEL_DOTNET_AUTO_METRICS_ADDITIONAL_SOURCES` (we plan to document it better #2132).

Does it cover your needs?

**Comment by samsp-msft** [comment]
Sweet. Yes, OTEL_DOTNET_AUTO_TRACES_ADDITIONAL_SOURCES probably covers the needs. 

But this brings up a further question about factoring, and docs/samples.
To be honest, I am not a big fan of auto-injecting assemblies into processes at runtime. There is too high a chance of conflicts between what the developer has used and what is being injected into the process. However I do think from an app developer perspective, you should be able to include OTEL with pretty minimal code and then use configuration to supply details like which metrics/counters and activities need to be collected. I was under the impression that this repo was just for the auto-injection. (I can't remember if I opened this issue here or there).

Should this ability to wildcard be part of the core assemblies or is it just for auto-injection?

Should it be used as part of the main docs on how to do custom metrics and tracing, rather than explicitly specifying the names of metrics/activity sources to include as part of the startup code?

**Comment by Kielek** [comment]
@samsp-msft, you can do it without auto-instrumentation package. Is it a https://github.com/open-telemetry/opentelemetry-dotnet feature.
What we are doing here we read env. variable, split by separator and inject into metrics/traces builder:
https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/dea5226f7a381760be2dd096cb056050a84cf494/src/OpenTelemetry.AutoInstrumentation/Configurations/EnvironmentConfigurationMetricHelper.cs#L55-L58 

In general you can type something like `builder.AddMeter("SampleNamespace.*)`

Ref link to main documentation https://github.com/open-telemetry/opentelemetry-dotnet/blob/d0829fff2f229b67c884526cb4943b99f6c75f29/docs/metrics/customizing-the-sdk/README.md?plain=1#L88-L100

**Comment by samsp-msft** [comment]
perfect.
