### ISSUE TITLE
An assembly specified in the application dependencies manifest was not found

### ISSUE THREAD

**Issue by d-aguilera** [open-telemetry/opentelemetry-dotnet-instrumentation#2167]
# Bug Report
## Symptom
When starting the "demo" Docker example, the Client and Server containers immediately stop with the following error:

```
An assembly specified in the application dependencies manifest (OpenTelemetry.AutoInstrumentation.AdditionalDeps.deps.json) was not found
  package: 'DnsClient', version: '1.4.0'
  path: 'lib/netstandard2.1/DnsClient.dll'
```
**Expected behavior**
All containers should start successfully.

**Screenshots**
<img width="1512" alt="Screen Shot 2023-02-04 at 14 19 48" src="https://user-images.githubusercontent.com/12613495/216781190-8d718ed3-11a5-4337-8ded-5719dbb9b837.png">

<img width="1418" alt="Screen Shot 2023-02-04 at 14 21 38" src="https://user-images.githubusercontent.com/12613495/216781911-1320ea98-47fc-45c0-87b7-9cf06586bfc3.png">

**Runtime environment:**

- OpenTelemetry Automatic Instrumentation version: 0.5.0
- OS: Mac OS Monterey 12.6.2, M1 Pro, 32 GB RAM
- Docker Desktop 4.16.2 (95914)
- .NET version: defined by the Docker image

**Additional context**
In addition to getting this error with the Docker example running on my Mac, I also got this very same error on a Windows 11 Home VM running on Parallels on the Mac. In that case I used the Powershell script as instructed, and got the error after launching the app's exe.
During this attempt in Windows, I was able to workaround the issue by manually copying each and every DLL from `C:\Program Files\OpenTelemetry .NET AutoInstrumentation\store\x64\net6.0` to the directory where the .exe was. So maybe this is just some environment variable missing? Because it seems it cannot resolve the location of these assemblies in the shared store (just guessing).

## Reproduce

1. Enter `make` command
2. Wait until `docker-compose` downloads all images and starts all containers
3. Soon after that, 3 containers stop:
* `sqlserver-1` ==> The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
* `service-1` & `client-1` ==> showing the error above.

I understand the SQL Server image error can be fixed by using a different image maybe. It's the .NET error that I'm concerned about.
Also I didn't found any OpenTelemetry log files in /var/log/opentelemetry/dotnet/

**Comment by d-aguilera** [comment]
About the SQL Server issue, I tried with [Azure SQL Edge](https://azure.microsoft.com/en-us/products/azure-sql/edge/) and it seems to work. Not sure if the app will be able to connect to it though but at least the container is up and running.

**Comment by d-aguilera** [comment]
I also tried with `6.0-jammy-arm64v8` for Client and Server, but it made no difference.

**Comment by d-aguilera** [comment]
More info:
When I remove
```
    env_file:
      - otel-dotnet.env # enables OpenTelemetry .NET Automatic Instrumentation
```
from `docker-compose.yaml`, both client and service start up and work correctly.
I know, these env vars are the whole purpose of the demo, but I just wanted to confirm the apps were able to run without instrumentation.

**Comment by d-aguilera** [comment]
<table><tr><td valign="top"><img src="https://user-images.githubusercontent.com/12613495/216837444-490f47db-43d5-4db7-93a3-2e94a6d4b6a7.png"></td><td valign="top"><img src="https://user-images.githubusercontent.com/12613495/216837451-73bc3444-ca25-4f15-9167-ca85cd47bf8f.png"></td></tr></table>

**Comment by d-aguilera** [comment]
The readme says  self-contained deployments are incompatible with automatic instrumentation, but I wanted to give it a try anyway to see if at least I could solve the missing dependencies problem this way. So I tried
`dotnet publish -c Release -o out -r linux-arm64`
and, as expected, it produced working Client and Service apps.

However, to my surprise, I'm seeing SQL traces in Grafana now, which I understand are automatically generated traces, correct?
Does this mean it was able to instrument a self-contained build?

<img src="https://user-images.githubusercontent.com/12613495/216848176-e37e8d79-ef26-48a9-b78f-39c90555c85c.png">

**Comment by pellared** [comment]
> I also tried with `6.0-jammy-arm64v8` for Client and Server, but it made no difference.

ARM is not supported. We tried it but we failed https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/1869

**Comment by pellared** [comment]
Thanks for reporting the problems that you have. Probably this issue has the same root cause as https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/issues/1744#issuecomment-1416421540

**Comment by pellared** [comment]
> The readme says self-contained deployments are incompatible with automatic instrumentation, but I wanted to give it a try anyway to see if at least I could solve the missing dependencies problem this way. So I tried `dotnet publish -c Release -o out -r linux-arm64` and, as expected, it produced working Client and Service apps.
> 
> However, to my surprise, I'm seeing SQL traces in Grafana now, which I understand are automatically generated traces, correct? Does this mean it was able to instrument a self-contained build?

You are correct. Self-contained apps should be working. It is some other issue that we are trying to identify. See https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/2131#issuecomment-1414147056

**Comment by pellared** [comment]
Just a note that I was unable to reproduce the issue locally. I even tried 

```
	docker-compose build --no-cache
	docker-compose up -d
```

I think this issue is not deterministic.

**Comment by rajkumar-rangaraj** [comment]
[d-aguilera](https://github.com/d-aguilera) Could you please provide the following, it will help in troubleshooting an issue.

1. Get the complete list of environment variables from the problematic environment. e.g.,: `printenv`
2. Directory listing of OpenTelemetry Automatic Instrumentation package from the environment where the failure happens. e.g.,: `tree opentelemetry-dotnet-instrumentation-linux-glibc` or `ls -R`

**Comment by d-aguilera** [comment]
Here's the requested information:

Client:
* [printenv](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/files/10671067/client-env.txt)
* [cd /app; tree .](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/files/10671069/client-tree-app.txt)

Service
* [printenv](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/files/10671071/service-env.txt)
* [cd /app; tree .](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/files/10671074/service-tree.txt)

Common (both apps identical output):
* [cd $OTEL_DOTNET_AUTO_HOME; tree .](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/files/10671075/common-tree-otel-dotnet-auto.txt)

**Comment by pjanotti** [comment]
> I think this issue is not deterministic.

Perhaps, because of [this](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/issues/1744#issuecomment-1420120518).

**Comment by d-aguilera** [comment]
Got it @pjanotti, here's the log file:

[corehost_verbose_tracing.log](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/files/10679292/corehost_verbose_tracing.log)

**Comment by d-aguilera** [comment]
I see the following at line 115 of corehost_verbose_tracing.log:
```
-- arguments_t: env shared store: '/otel-dotnet-auto/store/arm64/net6.0'
```
This directory doesn't exist in the container.
Only `x64/net6.0` and `x86/net6.0` exist within `/otel-dotnet-auto/store`.
Maybe this is the reason why it fails to find the assemblies?

**Comment by pjanotti** [comment]
Well observed @d-aguilera this seems a good candidate for the issue. The `arch/tfm` are added by the host so as a cheap validation could you please rename `/otel-dotnet-auto/store/x64/net6.0` to `/otel-dotnet-auto/store/arm64/net6.0`? The assemblies under the folder are MSIL so this shouldn't be a problem.

**Comment by d-aguilera** [comment]
That worked @pjanotti !

<img src="https://user-images.githubusercontent.com/12613495/217553899-72d97554-e4f2-4337-8371-56189fea020d.png">

**Comment by d-aguilera** [comment]
and I'm seeing both manual and automatic traces in Grafana.

**Comment by d-aguilera** [comment]
This is the log file now in demo-service-1 :

[corehost_verbose_tracing.log](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/files/10686590/corehost_verbose_tracing.log)

**Comment by d-aguilera** [comment]
> these env vars are documented [here](https://github.com/dotnet/runtime/blob/edd23fcb1b350cb1a53fa409200da55e9c33e99e/docs/design/features/host-tracing.md#trace-routing).

Maybe this should be mentioned in the [troubleshooting](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/3fd02e17a1aa88fde93a207d9c32c7cf95ba13ab/docs/troubleshooting.md) doc. Or in the main readme perhaps.

**Comment by pjanotti** [comment]
This issue combines two distinct problems:

1. The lack of native ARM binaries prevents any bytecode instrumentation on any ARM architecture, including Apple M1 boxes. This will be tracked via #1865 
2. The shared store doesn't build for the arm64 architecture. Currently we only cover x86 and x64 architectures but the list in the [dotnet/runtime](https://github.com/dotnet/runtime/blob/42ef1970047ace8972e22b13e5b05a7e2be656d2/src/native/corehost/hostmisc/utils.cpp#LL201-LL209) is much larger. Opened #2181

I will keep this open until we added the related information to the troubleshooting doc.

**Comment by d-aguilera** [comment]
Awesome guys. Thank you all very much. 

> 1. The lack of native ARM binaries prevents any bytecode instrumentation on any ARM architecture

Does this mean a different kind of instrumentation was used in my case? Cause I'm seeing the traces

**Comment by pellared** [comment]
> Awesome guys. Thank you all very much.
> 
> > 1. The lack of native ARM binaries prevents any bytecode instrumentation on any ARM architecture
> 
> Does this mean a different kind of instrumentation was used in my case? Cause I'm seeing the traces

The "source instrumentation type" is what is working in your scenario.

References: 
- https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/main/docs/design.md#library-instrumentations
- https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/main/docs/config.md#instrumentations
