### ISSUE TITLE
Option to disable the System.Net.Http.SocketsHttpHandler.Http2UnencryptedSupport

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-dotnet-instrumentation#217]
Per: https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/211#discussion_r689874809

The user should be able to set some configuration that will make sure that the following code will not be executed:

https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/3876971f102c9150a996aed7b6909a1ce493e7e3/src/OpenTelemetry.ClrProfiler.Managed/Configuration/EnvironmentConfigurationHelper.cs#L89

**Comment by pellared** [comment]
@nrcventura What do you think of moving it post-beta? I think it is important for RC/GA, but I do not find it critical for the beta. Especially that .NET Core 3.1 is planned to be supported only until the end of 2022: https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core.

**Comment by nrcventura** [comment]
> @nrcventura What do you think of moving it post-beta? I think it is important for RC/GA, but I do not find it critical for the beta. Especially that .NET Core 3.1 is planned to be supported only until the end of 2022: https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core.

I'm still nervous about us making a "security" related setting change on behalf of someone else without their consent. Even if this setting only applies to .NET Core 3.1, I think that we should have it. I believe that the bulk of .NET Core usage is still .NET Core 3.1, with people starting to migrate to .NET 6 now.

As an alternative, I'd rather drop "unencrypted" support for .NET Core 3.1 by removing that switch. In theory, someone could create an additional startup hook that only sets that setting, and have that startup hook be the first one in the startup hooks environment variable. Although, it would probably be less code to have an environment variable to control that setting.

**Comment by pellared** [comment]
Let's keep it in the scope then. It is so easy to implement it that I find it is not worth any further discussion 😉

**Comment by Kielek** [comment]
Please check if the second part of the condition is still needed here https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/0fb8f2851b3bbd013bd4a5a9c8128fc1d1f86ad1/src/OpenTelemetry.AutoInstrumentation/Configuration/Settings.cs#L165-L168
