### ISSUE TITLE
Document supported metrics

### ISSUE THREAD

**Issue by soulmate1314** [open-telemetry/opentelemetry-dotnet-instrumentation#2292]
### My question
I want to ask if there is a description document for each metric code currently supported

### These are currently exported

- process.runtime.dotnet.gc.collections.count
- process.runtime.dotnet.gc.objects.size
- process.runtime.dotnet.gc.allocations.size
- process.runtime.dotnet.gc.committed_memory.size
- process.runtime.dotnet.gc.heap.size
- process.runtime.dotnet.gc.heap.fragmentation.size
- process.runtime.dotnet.jit.il_compiled.size
- process.runtime.dotnet.jit.methods_compiled.count
- process.runtime.dotnet.jit.compilation_time
- process.runtime.dotnet.monitor.lock_contention.count
- process.runtime.dotnet.thread_pool.threads.count
- process.runtime.dotnet.thread_pool.completed_items.count
- process.runtime.dotnet.thread_pool.queue.length
- process.runtime.dotnet.timer.count
- process.runtime.dotnet.assemblies.count
- process.runtime.dotnet.exceptions.count
- process.memory.usage
- process.memory.virtual
- process.cpu.time
- process.threads
- http.server.duration

### At present, I only see the metric document description
https://learn.microsoft.com/zh-cn/dotnet/core/diagnostics/available-counters

**Comment by Kielek** [comment]
We do not have (yet) documentation in this repository. I am not sure if it will be easy to maintain.
You can find descriptions in the libraries used to generate it (I cannot find full list for ASP.NET, ASP.NET Core and HTTP Client. All of them are generated by libraries.
`ASPNET` - ?
`ASPNETCORE` - ?
`HTTPCLIENT` - ?
`NETRUNTIME` https://github.com/open-telemetry/opentelemetry-dotnet-contrib/tree/main/src/OpenTelemetry.Instrumentation.Runtime#metrics
`PROCESS` https://github.com/open-telemetry/opentelemetry-dotnet-contrib/tree/main/src/OpenTelemetry.Instrumentation.Process#metrics
`NSERVICEBUS`` https://docs.particular.net/samples/open-telemetry/prometheus-grafana/#reporting-metric-values

Comprehensive list is also available in Splunk distribution https://docs.splunk.com/Observability/gdi/get-data-in/application/otel-dotnet/configuration/dotnet-metrics-attributes.html#nav-Metrics-and-attributes

**Comment by Kielek** [comment]
SIG meeting notes: update our documentation with links of the SDK/Contrib/NServiceBus/MS documetnation with list of reported metrics.

**Comment by Kielek** [comment]
Done in scope of #1098
