### ISSUE TITLE
Validate if `OpenTelemetry.AutoInstrumentation` can be loaded from native profiler without the help of StartupHook.

### ISSUE THREAD

**Issue by Kielek** [open-telemetry/opentelemetry-dotnet-instrumentation#2295]
Not related to this PR, need to validate if `OpenTelemetry.AutoInstrumentation` can be loaded from native profiler without the help of StartupHook.

_Originally posted by @rajkumar-rangaraj in https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/2286#discussion_r1128320663_

**Comment by pjanotti** [comment]
See https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/2286#discussion_r1128392668

In short: not at this time we opted to require the StartupHook for .NET applications. The CLR Profiler won't attach and will log an error if the StartupHook is not configured.

**Comment by lumbans** [comment]
I have relate problem, with err message:
Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Extensions.Logging.Abstractions, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.

File name: 'Microsoft.Extensions.Logging.Abstractions, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
   at Microsoft.Extensions.DependencyInjection.LoggingServiceCollectionExtensions.AddLogging(IServiceCollection services, Action`1 configure)
   at Microsoft.Extensions.DependencyInjection.LoggingServiceCollectionExtensions.AddLogging(IServiceCollection services)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()

**Comment by Kielek** [comment]
@lumbans, I do not think that you question is related. Please lets go to #2296

**Comment by nrcventura** [comment]
One of the reasons we switched to the startup hook to bootstrap everything is that we noticed that many aspnetcore apps that relied on the profiler to bootstrap everything appeared to bootstrap things too early. We did not see the same problem with the startup hook solution. If we decide to follow this approach, we will need to do additional testing to ensure that we are bootstrapping things at an appropriate time.

**Comment by lumbans** [comment]
@Kielek can sql call query detected in dotnet auto instrumentation?
on my configuration not show the query statement

**Comment by Kielek** [comment]
@lumbans, it depends what type of library you are using for it. For v0.6.0 there is a support for SqlClient both from [Microsoft.Data.SqlClient](https://www.nuget.org/packages/Microsoft.Data.SqlClient) and [System.Data.SqlClient](https://www.nuget.org/packages/System.Data.SqlClient). Ref: https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/v0.6.0/docs/config.md#traces-instrumentations

Could you please rise new issues for each independent topic? It is a lot of easier to manage one topic per issue.

**Comment by Kielek** [comment]
@rajkumar-rangaraj, please check if current state is enough from your perspective.

**Comment by rajkumar-rangaraj** [comment]
As discussed in SIG, we need to clean-up code in StartupHook as the native layer also uses startuphook to instrument.
