### ISSUE TITLE
Remove unnecessary subdirectories in tracer home

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-dotnet-instrumentation#232]
Right now we have managed DLL's under the following directories:
- net45
- net461
- netcoreapp3.1
- netstandard2.0

Yet I believe that we only need:
- net461 (for .NET Framework => 4.6.1)
- netcoreapp3.1 (for .NET Core 3,1 and .NET >= 5.0)

We should also document the supported versions. Probably by simply  "copy-pasting" https://github.com/open-telemetry/opentelemetry-dotnet#supported-net-versions

**Comment by RassK** [comment]
@pellared I guess this is done now?

**Comment by pellared** [comment]
@RassK You are right.  Closing.

I will try to make doc PRs next week.
