### ISSUE TITLE
Proposal: Add Rule Engine to StartupHook

### ISSUE THREAD

**Issue by rajkumar-rangaraj** [open-telemetry/opentelemetry-dotnet-instrumentation#2392]
## Overview
Add a rule engine to the StartupHook. This rule engine will validate all OpenTelemetry Auto-Instrumentation assemblies for conflicts and ensure that it backs off in unsupported scenarios instead of crashing. The feature should provide a way for vendors to use this rule engine to validate their custom logic. It should validate all the rules and log to an event source/logger. Each rule will return a Boolean value, and even a single rule failure should back off the auto-instrumentation.  This feature could be extended to solve other issues apart from assembly load as well. The .NET event handler or delegate could be used to implement this feature.

## Feature Details
- The rule engine will be implemented in the StartupHook to validate all OpenTelemetry Auto-Instrumentation assemblies for conflicts and ensure that it backs off in unsupported scenarios instead of crashing.
- The feature should provide an extension for vendors to use this rule engine to validate their custom logic.
- The rule engine will be designed to validate all the rules and log to an event source or logger.
- Each rule will return a Boolean value, and even a single rule failure should back off the auto-instrumentation.
- The .NET event handler or delegate could be used to implement this feature.

## Motivation
Currently, the OpenTelemetry .NET Auto-Instrumentation lacks a mechanism to validate for conflicts and unsupported scenarios, which can lead to crashes during runtime. This feature will ensure that the Auto-Instrumentation is more robust and stable.

**Comment by pjanotti** [comment]
I __think__ that at least one kind of error can happen before the `StartupHook` gets executed. That said, the `StartupHook` can help with other situations, and having a way to perform custom validation is useful.

**Comment by RassK** [comment]
Could be a bit conflicting with https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/issues/2307 
Specially if we need to analyse modules that are not yet loaded to the context.

**Comment by pjanotti** [comment]
SIG: work for making plugins for this feature should be kept internal for the time being.

**Comment by RassK** [comment]
> Could be a bit conflicting with #2307 Specially if we need to analyse modules that are not yet loaded to the context.

⬇️ 

> SIG: work for making plugins for this feature should be kept internal for the time being.

Release environment could turn off the feature. I think if it's once validated, it doesn't need to be done again when application restarts. That kind of eliminates 2nd+ startup performance issues.

**Comment by rajkumar-rangaraj** [comment]
@RassK #2407 addresses  2nd+ startup performance issues, please review.
