### ISSUE TITLE
Proposal: Support well known resource detectors

### ISSUE THREAD

**Issue by RassK** [open-telemetry/opentelemetry-dotnet-instrumentation#2395]
### What

Support well known resource detectors automatically. 

List:
* [x] [Docker](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/tree/main/src/OpenTelemetry.Extensions.Docker)
* [x] [Azure](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/tree/main/src/OpenTelemetry.ResourceDetectors.Azure)
* [ ] [AWS](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/tree/main/src/OpenTelemetry.Contrib.Instrumentation.AWS)[^1]
* [ ] Kubernetes
* _(Add your thought here...)_

[^1]: Seems this package has mixed up instrumentations and resources? Could be worth checking before implementing.

**Comment by pellared** [comment]
I think that the user can get these resources using the OTel Collector. I am not sure if we need to have it in auto-instrumentation (more dependencies, bigger package, more maintenance).

**Comment by Kielek** [comment]
AWS packages are subject to change under contrib repository (including renaming).
If we need only part of this, we could probably extract resource package.

**Comment by pjanotti** [comment]
SIG meeting:

- Needs to be configurable similar to what is done for instrumentations (fine and coarse level control)
- Short run: add "low dependencies" detector: docker first and AZ when package is ready
- Medium term: decide about how to support more complex packages (e.g.: AWS)

**Comment by Kielek** [comment]
For now, we supporting following resource detectors:
* `AZUREAPPSERVICE`
* `CONTAINER`
* `HOST`
* `PROCESS`
* `PROCESSRUNTIME`.

If there is a needs for others, please create separate issue/PR. Closing.
