### ISSUE TITLE
[Discussion] How to manage dependencies

### ISSUE THREAD

**Issue by Kielek** [open-telemetry/opentelemetry-dotnet-instrumentation#2397]
We have several options to bring instrumentation dependencies including transitive dependencies to OpenTelemetry AutoInstrumentation:

- Additional Store
  - Currently used
  - Supported only by .NET (Core)
  - Information from Raj: There is a chance that the support will be dropped by further .NET releases
  - Different approach than we are using for other (OpenTelemetry.Instrumentation.*) libraries
  - Manual cleanup for transitive should be done to avoid shipping not-needed additional libraries.
    Deny list of packages needs to be (semi) manually maintained. PR prepared: [#2294](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/2294)
  - Additional risks:
    - Removing too many libs - integration tests should indicate as soon as that happens.
    - Removing too few libs - we will just continue bloating deployment size, like currently.
    - Matching ranges to ranges - complexity will increase even more.
- Direct reference to external package from OpenTelemetry.AutoInstrumentation
  - As in Additional Store, brings tons of not needed dependencies. Deny list has to be manually created or code similar to [#2294](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/2294) has to be created to mark transitive dependencies as `ExcludeAssets="all"`.
  - Risk of _dependency hell_ while solving dependencies for OpenTelemetry.AutoInstrumentation.
  - Reference will be added to `OpenTelemetry.AutoInstrumentation.Runtime.Managed` automatically
  - Works both for .NET Framework and .NET (Core): [#2390](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/2390) and [potential follow up](https://github.com/Kielek/opentelemetry-dotnet-instrumentation/commit/4cf165e4279cda25b264674677065f0337dbf0dc)
- Manually copy library library to the nuget package to `bin\tracer-home\netfx`
  - Works with .NET Framework
  - Status of support for .NET (Core) - TBD. If not work. .NET Core should be handled by Additional Store or Direct reference to external package.
  - Script to manual copy has to be created and maintained.
  - No risk for library version conflicts while resolving dependencies
  - Need a special way to add nuget reference to `OpenTelemetry.AutoInstrumentation.Runtime.Managed` nuget package (automatically produced from OpenTelemetry.AutoInstrumentation.csproj)
  - semi-auto analyzer similar to [#2294](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/2294) needed to ensure that we do not miss any new required dependency in case of library update.

Important notes:
Except .NET Framework redirect system, there is no way to upgrade dependencies referenced by libraries, eg. System.Diagnostics.DiagnosticSoruce.

**Comment by Kielek** [comment]
#2384 is replaced by #2390. Please check when you have some time.

**Comment by pjanotti** [comment]
Closing the issue, but, of course, the conversation can be restarted if appropriate.
