### ISSUE TITLE
Proposal: Change defaults for `OTEL_DOTNET_AUTO_[TRACES|METRICS|LOGS]_[ENABLED|DISABLED]_INSTRUMENTATIONS`

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-dotnet-instrumentation#2416]
Currently the default for `OTEL_DOTNET_AUTO_[TRACES|METRICS|LOGS]_[ENABLED|DISABLED]_INSTRUMENTATIONS` is `true`.

Maybe we should default it to `true` for Stable instrumentations and to `false` for Experimental instrumentation?

In order to enable all instrumentation the user would simply have to set `OTEL_DOTNET_AUTO_INSTRUMENTATION=true`.
Or `OTEL_DOTNET_AUTO_INSTRUMENTATION=false` to disable everything.

I think that the `1.0.0` release should by default should not enable experimental features.

**Comment by nrcventura** [comment]
What do we mean by "stable" instrumentation? Does that mean the code and it's configuration is stable? Does it mean that it generates data respecting a "stable" semantic convention?

**Comment by pellared** [comment]
> Does that mean the code and it's configuration is stable? Does it mean that it generates data respecting a "stable" semantic convention?

Good question. I think that both the instrumentation library (code) and semantic conventions are stable. The instrumentation library has to be stable to make sure that it is "maintained". The semantic conventions IMO should be stable even to make a stable release of an instrumentation library.

**Comment by Kielek** [comment]
I do not think that it is good idea. As I remember, only HTTP will _shortly_ have stabled specification.
Enabling only this one instrumentation is not good experience for our users.

**Comment by pellared** [comment]
After some thinking and retrospection my own work here: https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/1707

I think that we could enable all experimental instrumentations by default and in future add `OTEL_DOTNET_AUTO_EXPERIMENTAL` which defaults to `true` so that we do not introduce a "breaking configuration change".

I just want to be sure that we have a common agreement on this as I remember I had seen some discussions recently that some users want to only use "stable" components and I just want to make sure that we have an option to handle such scenario if there would be a big demand for it.

**Comment by pellared** [comment]
Closing per https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/issues/2439
