### ISSUE TITLE
Native code - enable by ref by default

### ISSUE THREAD

**Issue by Kielek** [open-telemetry/opentelemetry-dotnet-instrumentation#2427]
Probably separate GH issue:
Can it be enabled by default? I do not see any condition when it should be disabled.

_Originally posted by @Kielek in https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/2280#discussion_r1156999071_

**Comment by zacharycmontoya** [comment]
Fixed by #2495
