### ISSUE TITLE
Update OTel SDK

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-dotnet-instrumentation#243]
1. Update OTel .NET SDK package
2. Consider adding documentation on how to bump the OTel SDK dependencies.
3. Make sure to document the new environment variables that can be used.

**Comment by zacharycmontoya** [comment]
OTEL .NET SDK package updated in https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/258
