### ISSUE TITLE
RuleEngine: Improve performance for rules

### ISSUE THREAD

**Issue by rajkumar-rangaraj** [open-telemetry/opentelemetry-dotnet-instrumentation#2430]
https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/2419#issuecomment-1503111878 - This should cover all three rules where information is read from the file.

**Comment by RassK** [comment]
Discovered a conflict: the json is generated based on `TracerHomeDirectory / "net"` which is available after publish. This information is not easily available in compile time.

If there are no better ideas, I suggest to close it.

**Comment by pjanotti** [comment]
SIG: @rajkumar-rangaraj per Rasmus comment that this is not worth the trouble. Any reason to not close it?
