### ISSUE TITLE
Document why did System.Diagnostics.DiagnosticSource version diverged for OpenTelemetry.AutoInstrumentation and AdditionalDeps

### ISSUE THREAD

**Issue by xiang17** [open-telemetry/opentelemetry-dotnet-instrumentation#2431]
https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/2411#discussion_r1162226229:

> This leads to a question unrelated to this PR: why S.D.DS version for OpenTelemetry.AutoInstrumentation .NET Framework and AdditionalDeps diverged?

**Comment by RassK** [comment]
Shortly:
* We upgrade all .NET framework dependencies to the latest version to fix some internal bindings. 
* We keep the lowest possible version for the .NET Core, so an application can upgrade it.

**Comment by Kielek** [comment]
Closing base on @RassK exmplanation.

**Comment by pellared** [comment]
I think it may be good to describe it in the docs. E.g. in https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/main/docs/design.md
