### ISSUE TITLE
Possibility to disable Env. Variable and Telemetry SDK resource detectors

### ISSUE THREAD

**Issue by Kielek** [open-telemetry/opentelemetry-dotnet-instrumentation#2442]
Follow up to #2415

We need to decide if we should allow to disable required attributes by end-users.
For now Env. Variable and Telemetry SDK resource detectors are mandatory.

Telemetry SDK attributes are marked as required: https://github.com/open-telemetry/opentelemetry-specification/blob/25f513dbea2810be1c6f94d314d1a8d7e7b592c9/specification/resource/semantic_conventions/README.md#telemetry-sdk

**Comment by Kielek** [comment]
@carlosalberto, can it be disabled by enduser to reduce dimensions?

**Comment by pellared** [comment]
Related to https://github.com/open-telemetry/opentelemetry-specification/issues/3382

**Comment by Kielek** [comment]
The overall recommendation is to keep it always enabled. We should not allow easily remove this resources. Always plugin option is possible. Closing.
