### ISSUE TITLE
Add MongoDB CI integration test for .NET Framework.

### ISSUE THREAD

**Issue by pjanotti** [open-telemetry/opentelemetry-dotnet-instrumentation#2451]
A desirable follow-up to #2390

MongoDB can be hosted on Windows containers, see [`mongo:windowsservercore-ltsc2022`](https://hub.docker.com/layers/library/mongo/windowsservercore-ltsc2022/images/sha256-84dfac76c86f710c8f73b7e1cf41b48f7ffe53b042fc2232ee02790418f5c7c3?context=explore).

So it is possible to run the integration test on current GH Windows runners like done to ASP.NET integration tests.

Related [comment](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/2390#issuecomment-1487476950) on PR #2390.

**Comment by Kielek** [comment]
Probably blocked by https://github.com/testcontainers/moby-ryuk/issues/35
