### ISSUE TITLE
After native code update, remove race condition for OnModuleLoadFinished ReJIT request

### ISSUE THREAD

**Issue by zacharycmontoya** [open-telemetry/opentelemetry-dotnet-instrumentation#2452]
From this native code update, this seems like we are once again susceptible to a race condition with instrumentation when a new assembly is loaded. Let me explain where and how we issue ReJIT requests:
1. At startup we invoke `CorProfiler::InternalAddInstrumentation`, which will initialize the complete list of enabled bytecode instrumentations. We iterate through all loaded modules and do a _blocking_ ReJIT request for instrumentations whose assemblies have been loaded by calling `EnqueueRequestRejitForLoadedModules` with a [promise](https://github.com/zacharycmontoya/opentelemetry-dotnet-instrumentation/blob/c232661aba13dd5ef85468a9504adcff5ff1c673/src/OpenTelemetry.AutoInstrumentation.Native/cor_profiler.cpp#L1155-L1156).
2. When a new assembly is loaded we invoke `CorProfiler::ModuleLoadFinished`, which will see if the assembly contains instrumentation(s) and if so it will issue _nonblocking_ ReJIT requests by calling `RequestRejitForLoadedModules` with parameter `enqueueInSameThread=false` (this is required since we can't call ReJIT from the CorProfiler thread).

So number 1 is fine, but number 2 needs to be fixed. All we have to do is call the same API as number 1 and we can block with a certain timeout. I'll create an issue to track this and we can resolve this after this PR is merged.

_Originally posted by @zacharycmontoya in https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/2280#discussion_r1166155533_

**Comment by Kielek** [comment]
@zacharycmontoya I suppose that this issue is related to NServiceBus test failures.

ReJIT is not finished before NServiceBus calls are done.
