### ISSUE TITLE
MongoDB Instrumentation - use direct references instead of reflection

### ISSUE THREAD

**Issue by Kielek** [open-telemetry/opentelemetry-dotnet-instrumentation#2454]
Can take direct reference now.
(other occurrences also below)

_Originally posted by @RassK in https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/2390#discussion_r1165578472_

**Comment by RassK** [comment]
```
[ERR] CompileManagedSrc: CSC : error CS8002: Referenced assembly 'MongoDB.Driver.Core.Extensions.DiagnosticSources, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have a stro
ng name. [...\opentelemetry-dotnet-instrumentation\src\OpenTelemetry.AutoInstrumentation\OpenTelemetry.AutoInstrumentation.csproj::TargetFramework=net462]```

Seems it's not possible due the lib (`MongoDB.Driver.Core.Extensions.DiagnosticSources`) is not strong named.

**Comment by RassK** [comment]
2nd issue why I would actually suggest to close it - without taking direct reference to `MongoDb.Driver.Core` there is not much of optimisations available. I could redo only 3 lines of code. 2 instantiations + 1 property.

**Comment by pjanotti** [comment]
SIG: too small benefit for the trouble of handling the strong name, keeping the code as it is.
