### ISSUE TITLE
Revisit WCF instrumentation

### ISSUE THREAD

**Issue by Kielek** [open-telemetry/opentelemetry-dotnet-instrumentation#2463]
# Feature Request

**Are you requesting automatic instrumentation for a framework or library? Please describe.**

Make WCF instrumentation more user-friendly.

**Is your feature request related to a problem? Please describe.**

For now, usage requires a lot of manual modification either - xml configuration (.NET Framework) or even compilation for .NET.
For details see https://github.com/Kielek/opentelemetry-dotnet-instrumentation/blob/75b3c1f768cdbbcd1b9f97a29ced0199259cf2a4/docs/wcf-config.md#L3.

**Describe the solution you'd like**

Fully bytecode instrumentation for WCF communication both on the .NET Framework and .NET side (server and client).
It should fully remove configuration steps.

**Describe alternatives you've considered**

Current instrumentation. Which kills most of the benefits from Automatic Instrumentation usage.

**Additional context**

Server side on .NET can be handled as a separate step.
Should we have separate configs to enable particular instrumentations, such us: `WCFCLIENT`, `WCFSERVIER`, `WCFCORECLIENT` and `WCFCORESERVER`?

**Comment by pellared** [comment]
> Should we have separate configs to enable particular instrumentations, 

I think this is nice to have.

We could also consider having having byte code an source code WCF instrumentations if a user would not be able to set the .NET Profiler.

**Comment by Kielek** [comment]
Tasks needed for 1.0.0-rc.1/GA are done.

Some follow ups post GA:
* #2673 
* #2672 
* #2671 
* #2665 
* #2664 
* #2663
* #2662
