### ISSUE TITLE
GraphQL - instrumentation for 7.5.0+ versions

### ISSUE THREAD

**Issue by Kielek** [open-telemetry/opentelemetry-dotnet-instrumentation#2464]
# Feature Request

**Are you requesting automatic instrumentation for a framework or library? Please describe.**

GraphQL added native support for DiagnosticSource with OTel AutoInstrumentation friendly way in 7.5.0+ versions.
https://github.com/graphql-dotnet/graphql-dotnet/pull/3467

Support for this version should be added to this distribution.

**Additional context**

Still we Will have huge gap 3.0.*-7.3.*. It can be covered separately.

**Comment by RassK** [comment]
Detected multiple paths to resolve this, @open-telemetry/dotnet-maintainers any preferences?

```csharp
public void ConfigureServices(IServiceCollection services)
{
    services.AddGraphQL(b => b
        ... // General setup here
        .UseTelemetry(options => // <-- not very auto instrumentation friendly
        {
            options.RecordDocument = false; // must come from OTEL_DOTNET_AUTO_GRAPHQL_SET_DOCUMENT
        }));
}
```

1. Let user call `.UseTelemetry()`
P: safe, no double service registrations
N: cannot be called as "auto instrumentation", requires manual code modifications
N:  not reusing GraphQL env vars

2. Use bytecode instrumentation to tap into `.AddGraphQL()` and register `.UseTelemetry()` automatically.
N: Makes source code instrumentation to byte code instrumentation dependent
N: Could cause double `IServiceCollection` registration (and crash?)

3. Reuse `OpenTelemetry.AutoInstrumentation.AspNetCoreBootstrapper` and call internals of `.UseTelemetry()` with reflection.
N: Complicated reflection
N: Could cause double `IServiceCollection` registration (and crash?)
N: `.UseTelemetry()` can change

4. ???

I definitely see, it's much better than MongoDB instrumentation, no additional dependencies needed. In the same time I think we need to workout auto instrumentation friendly way, how to set service to publish activities with simple code and consume these. (At least consuming part is quite good if it works like this only -> `services.AddOpenTelemetry().WithTracing(b => b           .AddSource("GraphQL"))`

**Comment by RassK** [comment]
Detected multiple paths to resolve this, @open-telemetry/dotnet-instrumentation-maintainers any preferences?

```csharp
public void ConfigureServices(IServiceCollection services)
{
    services.AddGraphQL(b => b
        ... // General setup here
        .UseTelemetry(options => // <-- not very auto instrumentation friendly
        {
            options.RecordDocument = false; // must come from OTEL_DOTNET_AUTO_GRAPHQL_SET_DOCUMENT
        }));
}
```

1. Let user call `.UseTelemetry()`
P: safe, no double service registrations
N: cannot be called as "auto instrumentation", requires manual code modifications
N:  not reusing GraphQL env vars

2. Use bytecode instrumentation to tap into `.AddGraphQL()` and register `.UseTelemetry()` automatically.
N: Makes source code instrumentation to byte code instrumentation dependent
N: Could cause double `IServiceCollection` registration (and crash?)

3. Reuse `OpenTelemetry.AutoInstrumentation.AspNetCoreBootstrapper` and call internals of `.UseTelemetry()` with reflection.
N: Complicated reflection
N: Could cause double `IServiceCollection` registration (and crash?)
N: `.UseTelemetry()` can change

4. ???

I definitely see, it's much better than MongoDB instrumentation, no additional dependencies needed. In the same time I think we need to workout auto instrumentation friendly way, how to set service to publish activities with simple code and consume these. (At least consuming part is quite good if it works like this only -> `services.AddOpenTelemetry().WithTracing(b => b           .AddSource("GraphQL"))`

**Comment by nrcventura** [comment]
> 2\. Use bytecode instrumentation to tap into `.AddGraphQL()` and register `.UseTelemetry()` automatically.
>     N: Makes source code instrumentation to byte code instrumentation dependent
>     N: Could cause double `IServiceCollection` registration (and crash?)

Would it be possible to modify this approach to also "instrument" `.UseTelemetry` to potentially remove things so that we prevent the double registration?
