### ISSUE TITLE
Configuration to control fail fast behavior during application startup

### ISSUE THREAD

**Issue by nrcventura** [open-telemetry/opentelemetry-dotnet-instrumentation#2480]
# Feature Request

**Are you requesting automatic instrumentation for a framework or library? Please describe.**
No

**Is your feature request related to a problem? Please describe.**
The Rules Engine is useful for detecting issue that we are aware of. However, there may be some edge cases that we are not aware of that could cause a crash during application startup. 

**Describe the solution you'd like**
We should provide a configuration that allows the application to handle errors more gracefully during application startup and prevent the application from crashing. For example, it may be useful to fail quickly and crash in a dev or test environment, but in production we do not want to cause the application to crash.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by pellared** [comment]
Related: 
- https://github.com/open-telemetry/opentelemetry-specification/issues/2817
- https://github.com/open-telemetry/opentelemetry-specification/issues/2005

**Comment by Kielek** [comment]
@nrcventura,
I start looking into possible implementations of fail fast scenarios.
1. Support only things related to Rules Engine - just fail process instead of silently continue.
2. Unknown issues like https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/a4116522f43115bea6692205502541c98ffbc46e/src/OpenTelemetry.AutoInstrumentation.StartupHook/StartupHook.cs#L65-L69
3. Issues related to paring not supported configuration  - like passing to `OTEL_LOG_LEVEL` `SomeNotSupportedValue`.

I think we could introduce `OTEL_DOTNET_AUTO_FAIL_FAST_ENABLED` to cover all 3 cases, but before implementing this I would like to know your opinion.

**Comment by nrcventura** [comment]
Those are the things that I am aware of, and I think that having a single setting like you described to cover all of those scenarios makes sense to me. I do not think that it will be helpful to have separate settings for each of those scenarios.

When someone is testing things, I think they will want to enable fail fast to make it easier to diagnose problems without having to read through log files. However, in production environments they will want fail fast to be disabled. To be safe, we may want the default setting for fail fast to be "false/off".

**Comment by Kielek** [comment]
One more thing. Part of the parsing is done on the SDK/libraries side. I do not think that we will be able to introduce such feature in our RC timeframe/1.5.0 of OTel SDK/API release. I will implement and document that not all cases are handled by this.

**Comment by nrcventura** [comment]
Even if some of the parsing is done on the SDK/libraries side, is that type of error something that we can catch on our side?

**Comment by Kielek** [comment]
Usually, it is silently ignored and default value is used. It is recommended/mandatory by OTEL spec

**Comment by pellared** [comment]
> Even if some of the parsing is done on the SDK/libraries side, is that type of error something that we can catch on our side?

Maybe wer could catch the events like: https://github.com/open-telemetry/opentelemetry-dotnet/blob/b9908d14f84abd437ad91aad7b3f5e364bc5ad1c/src/OpenTelemetry/Internal/Options/ConfigurationExtensions.cs#L69 and crash the app?

> Usually, it is silently ignored and default value is used. It is recommended/mandatory by OTEL spec

The specification is not great here as I do not think the places where it is "mandatory" is correct

**Comment by nrcventura** [comment]
> Maybe wer could catch the events like: https://github.com/open-telemetry/opentelemetry-dotnet/blob/b9908d14f84abd437ad91aad7b3f5e364bc5ad1c/src/OpenTelemetry/Internal/Options/ConfigurationExtensions.cs#L69 and crash the app?

That is an interesting idea, but I do not think that it is necessary. If there are settings outside of our direct control that have an invalid configuration, then I do not think we should go out of our way to raise an error. I am more concerned about preventing crashes at startup, than I am about introducing failures for things that we do not control.
