### ISSUE TITLE
Document that AoT scenario is not supported

### ISSUE THREAD

**Issue by Kielek** [open-telemetry/opentelemetry-dotnet-instrumentation#2496]
We have to extend documentation with information that AoT is not supported.

**Comment by rajkumar-rangaraj** [comment]
It is documented in https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/main/docs/design.md#unsupported-scenarios. Do you want to expand on this document or move this section to a different place?

**Comment by Kielek** [comment]
I have missed this part of documentation. It is enough. Closing:

https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/85554850537066da5c0a4d320b14d47c5b2e8ad7/docs/design.md#unsupported-scenarios
