### ISSUE TITLE
Proposal: Instructions for 3rd party libraries to be Auto Instrumentation friendly

### ISSUE THREAD

**Issue by RassK** [open-telemetry/opentelemetry-dotnet-instrumentation#2520]
## What

Regarding to issue #2464, some libraries may choose the path to add additional bootstrapping. I think we may need to standardize how the bootstrapping process should look like, otherwise we collect and have to maintain many different patterns. I guess most of these patterns need a unique IL rewrite to hook us into the right place.

Currently there are 2 ways in my mind:

###  Activity creation ON by default (Preferred)

A library should always try to create activities by default. If there is no listener, no activities are created (this is S.D.DS behaviour).
I'm not sure if this is going to introduce overhead if there are no listeners attached. 
Examples: ASP.NET Core, HttpClient

### Activity creation ON by calling initializer

In any case if library authors do not want to create activities by default, it is the backup behaviour how Auto Instrumentation can still easily wire up activity creation. 

A library should contain specialized type for bootstrapping Auto Instrumentation:

```csharp
namespace OpenTelemetry.AutoInstrumentation;

internal class Initializer
{
    public static void EnableAutoInstrumentation()
    {
         // Library owner implements bootstrapping
    }
}
```
The Auto Instrumentation side just calls:

```csharp
// Initializes or enables auto instrumentation
Type.GetType("OpenTelemetry.AutoInstrumentation.Initializer, The.Instrumented.Dll")
   .GetMethod("EnableAutoInstrumentation", BindingFlags.Static | BindingFlags.NonPublic);
   .Invoke(null, null);
```

## Action

* Our final instructions must be clearly documented. 
* We could open some issues in the repos to get some feedback / beta testing.

**Comment by pjanotti** [comment]
SIG: unfortunately is not actionable on our side, we should submit PRs to instrumentation packages when appropriate. The best that we can do is make it clear on SDK docs.

**Comment by RassK** [comment]
Linking here > https://github.com/graphql-dotnet/graphql-dotnet/issues/3626

**Comment by RassK** [comment]
Linking here > https://github.com/mysql-net/MySqlConnector/issues/1323

**Comment by RassK** [comment]
Linking here > https://www.mongodb.com/community/forums/t/better-compatibility-with-opentelemetry-autoinstrumentation/228456
