### ISSUE TITLE
Feature: automate TelemetryHttpModule injection in IIS

### ISSUE THREAD

**Issue by pjanotti** [open-telemetry/opentelemetry-dotnet-instrumentation#2526]
[[EDIT00](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/issues/2526#issuecomment-1550650654): updated the description to reflect the desired outcome, not the implementation]

# Feature Request

Automatic instrumentation for .NET Framework apps on IIS should not require manual configuration to inject `TelemetryHttpModule`. This can be done either via bytecode instrumentation or following the steps to [Add TelemetryHttpModule ASP.NET HTTP module](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/a290429994c7fbed04b03dfe264e946d69b82fec/docs/iis-instrumentation.md?plain=1#L22) via the [`OpenTelemetry.DotNet.Auto.psm1`](OpenTelemetry.DotNet.Auto.psm1). 

This feature makes the automatic instrumentation of ASP.NET HTTP apps much easier.

**Comment by pellared** [comment]
This is needed only for .NET Framework, I think we could add the HTTP module using bytecode instrumentation.

_As far as I remember this is what most .NET (Datadog/New Relic/SignalFx) Agents are doing._

**Comment by pdelewski** [comment]
@pjanotti @pellared Just to be sure, we are talking about these manual changes in `web.config`/ applicationHost.config?

**Comment by pellared** [comment]
> @pjanotti @pellared Just to be sure, we are talking about these manual changes in `web.config`/ applicationHost.config?

Yes.

**Comment by Kielek** [comment]
Alternate solution - introduce bytecode instrumentation to register this telemetry module.

**Comment by pdelewski** [comment]
Cool. I was thinking about something similar to simplify user experience, however I wanted to go even further with that and simplify auto instrumentation usage to bare minimum, e.g. do everything with one command that will check some preconditions and ask few questions, for instance what do you want to instrument? 1) IIS app 2) Windows service and based on that will do required steps and at end check post conditions. Recently I had a discussion about that with @Kielek  and planned to open issue, but we can discuss it here. 
I'm wondering what do you think about it? Is it make sense?, maybe someone already was thinking about it and it's not worth it (it's good enough what we have so far).

**Comment by RassK** [comment]
The setup script (PowerShell) already contains methods to do IIS, Windows Service and shell session setup, but asking the question in setup might be interesting way to improve setup UX 🤔

**Comment by pjanotti** [comment]
@pdelewski a "wizard" like approach is good: perhaps combine it with the script.

The preferable solution is to have it done via bytecode instrumentation: fewer things to set up and clean up. That said, we can probably quickly implement the feature via a call to `appcmd` on the PowerShell script and later switch to bytecode instrumentation.

**Comment by pjanotti** [comment]
Just made EDIT00 on the top description to reflect the desired outcome, not the implementation.

**Comment by pjanotti** [comment]
@pdelewski yes, please.
