### ISSUE TITLE
Rewrite MySql.Data instrumentation to bytecode instrumenation

### ISSUE THREAD

**Issue by Kielek** [open-telemetry/opentelemetry-dotnet-instrumentation#2542]
MySql.Data v 8.0.33 introduced breaking changes.
It is not feasible to longer use sourcecode instrumentation without some other magic (like Harmony https://github.com/open-telemetry/opentelemetry-dotnet-contrib/issues/1157).

Issue detected by #2478

The goal is to rewrite it to bytecode instrumentation.

**Comment by bgrainger** [comment]
IMO the effort would be better spent integrating with MySqlConnector (disclaimer: I am the lead author): https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/issues/2636.

MySqlConnector natively supports the System.Diagnostics APIs (currently `Activity` for tracing; metrics coming soon). It's also more highly tuned for performance (which I would assume is important for anyone who's instrumenting their application to track performance).

**Comment by Kielek** [comment]
Adding support for MySqlConnector is IMO good idea, but we still should have support for MySql.Data.

Based on our research it was one of the most important instrumentation for already existing Tracers.

**Comment by zacharycmontoya** [comment]
I started a draft PR for this work item, but I may need someone to finish it because of the following personal situations:
- I'll likely be out-of-office for the rest of the week to take care of a personal emergency
- I have scheduled vacation for the first half of July

**Comment by Kielek** [comment]
SIG meetings: lets postpone to rc.2 version. For rc.1 ensure that we have known issue statement.

**Comment by muhaook** [comment]
For info, MySQL connector/NET supports OTel tracing starting 8.1.0: https://dev.mysql.com/doc/connector-net/en/connector-net-programming-telemetry.html It is for .NET 5 and later.

Also, starting 8.1.0, MySQL Enterprise Edition generates OTel trace data on Linux platforms: https://dev.mysql.com/doc/refman/8.1/en/telemetry-trace.html

I did not get a chance to test it, but we may expect the correlation between traces generated by connector/NET and traces generated by MySQL Enterprise Edition

**Comment by muhaook** [comment]
> Looks interesting, especially builder extension: https://github.com/mysql/mysql-connector-net/blob/1341887fc28fc3181e9bf65a8dc6534e82b84284/MySQL.Data.OpenTelemetry/src/TraceProviderBuilderExtension.cs#L7-L12

It does not even require code change and can be enabled with config change `OTEL_DOTNET_AUTO_TRACES_ADDITIONAL_SOURCES=connector-net`
