### ISSUE TITLE
Support essential OpenTelemetry Environmental Variables

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-dotnet-instrumentation#255]
For sake of beta release, we should support the following environment variables to make the auto-instrumentation usable and aligned to OTel specification. The environment variables should be implemented in SDK and reused in this repository

| Environment variable | Supported |
| --- | --- |
| OTEL_RESOURCE_ATTRIBUTES | ✔️ |
| OTEL_SERVICE_NAME | ✔️ |
| OTEL_BSP_* | ✔️ |
| OTEL_TRACES_EXPORTER | ✔️ (not via SDK, possible values are: `none`, `otlp`, `jaeger`, `zipkin`) |
| OTEL_EXPORTER_OTLP_* | ✔️ |
| OTEL_EXPORTER_ZIPKIN_* | ✔️ |
| OTEL_EXPORTER_JAEGER_* | ✔️ |

**Comment by pellared** [comment]
I propose to work on supporting `OTEL_PROPAGATORS` and `OTEL_TRACES_EXPORTER` after the beta release. As getting it implemented in SDK would probably take months and users can always use the "plugins/customization" to set it in code.

The only thing we would do before beta release would be to set `otlp` as the exporter and `tracecontext,baggage` as the propagators in the initialization code. This would also require solving https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/issues/274.

**Comment by nrcventura** [comment]
> I propose to work on supporting `OTEL_PROPAGATORS` and `OTEL_TRACES_EXPORTER` after the beta release. As getting it implemented in SDK would probably take months and users can always use the "plugins/customization" to set it in code.

That seems like an acceptable short-term workaround. If our defaults are good enough, there might not be anything for users to configure manually for these early releases.

> The only thing we would do before beta release would be to set `otlp` (grpc) as the exporter and `tracecontext,baggage` as the propagators in the initialization code. This would also require solving #274.

I think enabling `otlp` (grpc) out of the box is a good idea, because then data can be sent to a local collector in a more loss-less fashion, where they can then do any customizations that they need before sending the data to another destination.

**Comment by pellared** [comment]
Next step: Implement as described ☝️

**Comment by pellared** [comment]
@open-telemetry/dotnet-maintainers 
I updated this issue description. Do you think we close this issue? I tried to create a few concrete follow-up issues under the https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/milestone/1 milestone.

**Comment by nrcventura** [comment]
I think that we can close it, and just focus on the follow-up issues.

**Comment by pellared** [comment]
@zacharycmontoya @pjanotti @rajkumar-rangaraj: Any objections to closing it?

**Comment by rajkumar-rangaraj** [comment]
We could close it, no objections.

**Comment by zacharycmontoya** [comment]
Yes you may go ahead and close it
