### ISSUE TITLE
Integration tests not reflecting real use case

### ISSUE THREAD

**Issue by RassK** [open-telemetry/opentelemetry-dotnet-instrumentation#256]
Adding an old issue here. Some of the old samples reference ClrProfiler.Managed directly. Instead in real use case, where managed libraries are loaded indirectly via specialized loader. 
Currently it can cause misunderstanding when native layer is not loading but application shows that full managed layer is loaded.

I think we should change the build process and either copy or reference the full package directory built by Nuke.

**Comment by RassK** [comment]
> Could you please list the samples that do that?

Should be all of them, cause the reference is added via Directory.Build.props

**Comment by pellared** [comment]
@RassK Why have you closed it?

**Comment by RassK** [comment]
> @RassK Why have you closed it?

Seems reference to this PR was missing
https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/263
