### ISSUE TITLE
Diagnostic Source assembly versioning Issue

### ISSUE THREAD

**Issue by rajkumar-rangaraj** [open-telemetry/opentelemetry-dotnet-instrumentation#260]
<H3>Dotnet Assembly Load Explained</H3>

Dotnet core runtime automatically load assemblies with a higher version at runtime. Below is an example of loading  `System.Diagnostics.DiagnosticSource` assembly. 

* Framework - `System.Diagnostics.DiagnosticSource.dll` is automatically referenced from framework.
* PackageReference  -  `System.Diagnostics.DiagnosticSource.dll` is referenced from NuGet package.

| Scenario                                  | Framework | PackageReference |
|-------------------------------------------|:---------:|:-------:|
| No PackageReference in project           | ✔️        |         |
| PackageReference <= Framework | ✔️        |         |
| PackageReference > Framework |           | ✔️      |

Dynamically loading `System.Diagnostics.DiagnosticSource.dll` with a higher version than the one from framework/package will crash the process. The  table below covers the scenario.

| Dynamic Load Scenario                               | Status |
|---------------------------------------------|--------|
| Dynamic Load <= Framework/PackageReference  | ✔️     |
| Dynamic Load > Framework/PackageReference    | ❌      |

✔️ 🠮 Success | ❌ 🠮 Crashes an application

<H3>Demo</H3>

* This console app is built using .NET Core 3.1 and does **not** have any package reference. 
* At build time, .NET creates a Trusted Platform Assembly (TPA) list. This list has an entry to load DiagnosticSource from the framework (`C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.20\System.Diagnostics.DiagnosticSource.dll, Version: System.Diagnostics.DiagnosticSource, Version=4.0.5.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51`). 
* Dynamically loading higher version of `System.Diagnostics.DiagnosticSource` will crash an app. Executing this app will exhibit the behavior.
* The behavior is same if we try to load with Startup Hook or CLR Profiler.

```xml

<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

</Project>

```

```csharp
static void Main(string[] args)
{
    try
    {
        string path = @"C:\Users\userprofile\.nuget\packages\system.diagnostics.diagnosticsource\5.0.1\lib\netstandard1.3\System.Diagnostics.DiagnosticSource.dll";
        Debug.Assert(File.Exists(path));
        Assembly.LoadFrom(path);
    }
    catch (Exception e)
    {
        Console.WriteLine($"Exception: {e}");
    }
}

```

```
Exception: System.IO.FileLoadException: Could not load file or assembly 'System.Diagnostics.DiagnosticSource, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at consoleappdiag.Program.Main(String[] args) in D:\temp\consoleappdiag\Program.cs:line 16
```

<H3>Workaround</H3>

* Use dotnet [Additional-deps](https://github.com/dotnet/runtime/blob/main/docs/design/features/additional-deps.md) to provide the reference to `System.Diagnostics.DiagnosticSource` used by the OpenTelemetry SDK. 
* This approach will work if the app does not have a direct or indirect package reference to `System.Diagnostics.DiagnosticSource`. 
* Dotnet supports Framework Dependent apps and Self-Contained apps. Additional-deps will work
only for Framework Dependent apps.

<H3>Proposal</H3>

Load OpenTelemetry referenced `System.Diagnostics.DiagnosticSource.dll` in a different assembly context using `Assembly.LoadFile`. Create a proxy to listen to `Activity`s emitted by a lower version of `DiagnosticSource` and create a clone of the same `Activity` in the OpenTelemetry supported `DiagnosticSource`.  

Enable the proxy feature when an application uses a lower version of `DiagnosticSource` than the OpenTelemetry referenced DiagnosticSource.

Use `Additional-deps` in supported environments.

```text
+--------------------+             +-------------------+    
| DS (Lower Version) |             | DS (OTel Version) |---------
+--------------------+             +-------------------+         |
        |                                 ^                      | OTel supported Activity
        | Activity                        |                      v
        |                +-------+        |             +----------------------+
         --------------> | Proxy | -------              | Otel Instrumentation |
                         +-------+                      +----------------------+
				 
```

**Comment by pellared** [comment]
How about creating some byte-code instrumentation for `DiagnosticSource` that would ensure that we are using a single version of `DiagnosticSource` via some proxy?

**Comment by nrcventura** [comment]
> How about creating some byte-code instrumentation for `DiagnosticSource` that would ensure that we are using a single version of `DiagnosticSource` by using some proxy?

One downside to that type of approach is that if someone didn't need any other byte-code instrumentation, they will lose the performance benefits of just being able to use the startup hook to bootstrap the SDK.

@macrogreg got a slightly different approach working using just managed code that does something similar.

**Comment by rajkumar-rangaraj** [comment]
This will be covered through #633
