### ISSUE TITLE
MySqlConnector support - traces

### ISSUE THREAD

**Issue by bgrainger** [open-telemetry/opentelemetry-dotnet-instrumentation#2636]
# Feature Request

- Library name : MySqlConnector
- Library type: ADO.NET connector for MySQL, MariaDB, etc.
- Library version: >= 2.0.0

I'm the lead developer of MySqlConnector. It's currently the most popular NuGet package for MySQL (by download count), and IMHO the most advanced (first to support async, first to support new .NET 6.0 and .NET 7.0 ADO.NET APIs, first to add support for tracing, etc.)

Since [v2.0.0](https://github.com/mysql-net/MySqlConnector/releases/tag/2.0.0), it's supported tracing via the `System.Diagnostics.Activity` API, using the [OpenTelemetry Semantic Conventions](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/database.md). For v2.3.0, I'm planning to add metrics support (again, following the [OpenTelemetry Semantic Conventions](https://github.com/open-telemetry/semantic-conventions/blob/main/specification/metrics/semantic_conventions/database-metrics.md)) using `System.Diagnostics.Metrics`: https://github.com/mysql-net/MySqlConnector/pull/1328.

Does use of `Activity` in the MySqlConnector library mean that "Yes" can be put in the Tracing column next to MySqlConnector in https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/main/docs/internal/instrumentation-libraries.md#databases? Or is some glue code still necessary to hook up an `ActivityListener`?

**Comment by Kielek** [comment]
It should be pretty straightforward to add instrumentation for MySqlConnector. The only risk I see is the dependency on System.Diagnostics.DiagnosticsSource lower than 5.0. To make it work, during the compilation, the author of the application ahs to update it manually to 7.0.0 or newer.

If you would like to test it before implementation, you can just use `OTEL_DOTNET_AUTO_TRACES_ADDITIONAL_SOURCES` env. variable and put there `MySqlConnector`.

The most similar instrumentation in the existing code base should be MassTransit. Full search text will help to find all places to modify/exted.

Would you like to contribute PR?

**Comment by bgrainger** [comment]
FWIW, the next version (prerelease) is already using System.Diagnostics.DiagnosticSource v7.0.0:

* https://www.nuget.org/packages/MySqlConnector/2.3.0-beta.2#dependencies-body-tab
* https://github.com/mysql-net/MySqlConnector/blob/master/src/MySqlConnector/MySqlConnector.csproj#L35

**Comment by bgrainger** [comment]
> The most similar instrumentation in the existing code base should be MassTransit. Full search text will help to find all places to modify/exted.
> 
> Would you like to contribute PR?

Thanks for the pointer; I'll take a look and see if I can put something together.

**Comment by Kielek** [comment]
@bgrainger, we have assigned to post-1.0.0. It means that we will not focus on this before 1.0.0 GA, but if you are able to prepare PR for us we will accept it.
