### ISSUE TITLE
Update fmtlib to 10.0.0 release or newer.

### ISSUE THREAD

**Issue by Kielek** [open-telemetry/opentelemetry-dotnet-instrumentation#2638]
Update fmtlib to 10.0.0 release or newer.

It can be separate issue.

_Originally posted by @Kielek in https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/2635#discussion_r1226347697_

**Comment by Kielek** [comment]
Remember both
* linux: https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/7ed9021cd0f946ae0bab690c7ca282a3a1340857/src/OpenTelemetry.AutoInstrumentation.Native/CMakeLists.txt#L107-L111
* windows: https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/tree/7ed9021cd0f946ae0bab690c7ca282a3a1340857/src/OpenTelemetry.AutoInstrumentation.Native/lib

**Comment by RassK** [comment]
Can be re-opened if fmt 10.0 is supported. https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/2685#issuecomment-1611139396
