### ISSUE TITLE
please provide a command that will allow me to run the sample in windows

### ISSUE THREAD

**Issue by tydhot** [open-telemetry/opentelemetry-dotnet-instrumentation#271]
Hi, I am founding a way to auto instrument the dotnet app in winodws. But I am new to windows and dotnet and I find the command in [DEVELOPING](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/main/docs/DEVELOPING.md) can't work well in windows. Can you give me a command to help me run the sample in windows?

**Comment by pellared** [comment]
What commands are not working? What error are you getting?

**Comment by pellared** [comment]
@tydhot Any progress? Let us know please :-)

**Comment by tydhot** [comment]
@pellared sry about the late reply. I have met some problem about my env while I am running the `dotnet nuke`. 

<img width="571" alt="屏幕截图 2021-11-17 195335" src="https://user-images.githubusercontent.com/27889201/142195954-92916368-bf5f-41e5-817c-1ce890ca54f6.png">
I am tring to solve this.
and it seemed that the command `./dev/instrument.sh dotnet run -f netcoreapp3.1 -p ./samples/ConsoleApp/ConsoleApp.csproj` cant work well in my windows pc.
<img width="651" alt="屏幕截图 2021-11-17 195537" src="https://user-images.githubusercontent.com/27889201/142196147-b71fe237-6e0e-430d-9f2f-31c90be84e99.png">
I am tring to solve them.

**Comment by pellared** [comment]
Looks like `msbuild` is not in your PATH.

Personally I have added `PATH="$PATH:/c/Program Files (x86)/Microsoft Visual Studio/2019/Professional/MSBuild/Current/Bin"` line to my `$HOME/.bashrc` file.

You can also try running `dotnet nuke` in `Developer Command Prompt for VS 2019`

**Comment by pellared** [comment]
Regarding the issue with ``./dev/instrument.sh dotnet run -f netcoreapp3.1 -p ./samples/ConsoleApp/ConsoleApp.csproj`` - you are not running it in Bash 😉

**Comment by tydhot** [comment]
> Regarding the issue with `./dev/instrument.sh dotnet run -f netcoreapp3.1 -p ./samples/ConsoleApp/ConsoleApp.csproj` - you are not running it in Bash 😉

hah, of cource.  That is wny I open the issue, I am new to windows and bash, it is a challenge for me to write the bash. It would be great if you could provide it, and it would be convenient for future users to use it

**Comment by pellared** [comment]
Git for Bash is included in https://gitforwindows.org/

<img width="131" alt="image" src="https://user-images.githubusercontent.com/5067549/142237968-af46a201-35cf-4357-9610-16a6b4dee28b.png">

**Comment by tydhot** [comment]
@pellared wow amazing. Thank you so much!
