### ISSUE TITLE
Tests - MongoDB executed on Docker Windows with Linux is hanging 

### ISSUE THREAD

**Issue by Kielek** [open-telemetry/opentelemetry-dotnet-instrumentation#2715]
# Steps to reproduce
Either `nuke Workflow` on Docker Windows with Linux or just execute IntegrationTests.MongoDBTests from VS on same environemt.

Tests are hangign.

Workaround, but if we commit this then the tests will be failing on CI.
```diff
diff --git a/test/IntegrationTests/MongoDBCollection.cs b/test/IntegrationTests/MongoDBCollection.cs
index 77b98706..34380b2d 100644
--- a/test/IntegrationTests/MongoDBCollection.cs
+++ b/test/IntegrationTests/MongoDBCollection.cs
@@ -58,7 +58,8 @@ public class MongoDBFixture : IAsyncLifetime
     {
         var waitForOs =
 #if _WINDOWS
-         Wait.ForWindowsContainer();
+         Wait.ForUnixContainer();
 #else
          Wait.ForUnixContainer();
 #endif
```

Needed a way to detect Docker (Linux/Windows) versions and execute method correctly.

**Comment by nrcventura** [comment]
Even though the testcontainers library does not make [its GetIsWindowsEngineEnabled method](https://github.com/testcontainers/testcontainers-dotnet/blob/d3f09da08f0709225e254c0b39e6b187fdc0bb75/src/Testcontainers/Clients/DockerSystemOperations.cs#L18-L23) public we might be able to leverage similar code to perform the necessary check.
