### ISSUE TITLE
No OTEL Traces/Metrics for HTTP API Calls for .Net Windows Server Service

### ISSUE THREAD

**Issue by ritesh-harry** [open-telemetry/opentelemetry-dotnet-instrumentation#2733]
# Bug Report

## Symptom

**Describe the bug**
Hello,

I have instrumented our .NET applications automatically (applications are on Windows Server running as a Windows service) by implementing the solution coming from OpenTelemetry-dotNet. I believe all the libraries shipped with the OpenTelemetry-dotNet (https://github.com/open-telemetry/opentelemetry-dotnet) repository support all the officially supported versions of .NET Core and .NET framework with an except for .NET Framework 3.5 SP1.

The process I have used to implement this solution is as per below,

1. Download and import the PowerShell module on Windows Server which has the .Net application Windows service running (https://raw.githubusercontent.com/open-telemetry/opentelemetry-dotnet-instrumentation/v0.7.0/OpenTelemetry.DotNet.Auto.psm1")

2. Run the PowerShell command to install core files:
Install-OpenTelemetryCore

3. Add the OTEL environment variables to the .Net Windows service application configuration file. The only OTEL environment variables defined in the configuration file is as per below:

add key="OTEL_SERVICE_NAME" value="API.Service"
add key="OTEL_EXPORTER_OTLP_ENDPOINT" value="https://collectors.au.sumologic.com/receiver/v1/trace/<id_here>"
add key="OTEL_DOTNET_AUTO_INSTRUMENTATION_ENABLED" value="true"
add key="OTEL_EXPORTER_OTLP_PROTOCOL" value="http/protobuf"
add key="OTEL_RESOURCE_ATTRIBUTES" value="application=services,deployment.environment=test"

4. Run the PowerShell command to register the .Net application Windows service for OTEL:
Register-OpenTelemetryForWindowsService -WindowsServiceName ""API.Service" -OTelServiceName "API.Service"

The above process seems to be working well for most of our .Net application Windows services. However, we do not seem to be getting any telemetry data for our services that receive HTTP API calls, I would have thought we would have been able to see this data.

I wanted to confirm the below,

1. Are there any additional application settings that need to be added in order to see this kind of data (HTTP API call traces/metrics)?
2. Can OTEL get metrics from OWIN webserver on .Net?
3. Are there any dependencies that need to be installed on Windows Server to get this to work?

Any help in trying to sort out this issue would be greatly appreciated.

Thank you.

**Expected behavior**
I expect to see traces for API calls.

**Screenshots**

**Runtime environment (please complete the following information):**

opentelemetry-dotnet-instrumentation v0.7.0

 .NET Framework 4.6.2

OS Version:
Windows Server 2019/2022

Runtimes:
Microsoft ASP.NET Core 6.0.19 - Shared Framework (x84)
Microsoft ASP.NET Core 6.0.19 - Shared Framework (x64)
Microsoft .NET Runtime - 6.0.19 (x86)
Microsoft .NET Runtime - 6.0.19 (x64)
Microsoft .NET Runtime 6.0.19 - Windows Server Hosting

**Additional context**

## Reproduce

Follow steps 1 through to 4 in the Describe the bug section.

<!--
NOTE: If possible, also include the log files found (by default) in:
Windows: %ProgramData%\OpenTelemetry .NET AutoInstrumentation\logs\
Linux and macOS: /var/log/opentelemetry/dotnet/
--!>

[otel-dotnet-auto-EML.Api.Account.exe-10440-Loader-20230704.log](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/files/11962758/otel-dotnet-auto-EML.Api.Account.exe-10440-Loader-20230704.log)
[otel-dotnet-auto-native-EML.Api.Account-10440.log](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/files/11962759/otel-dotnet-auto-native-EML.Api.Account-10440.log)
[otel-dotnet-auto-EML.Api.Account.exe-10440-20230704.log](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/files/11962760/otel-dotnet-auto-EML.Api.Account.exe-10440-20230704.log)

**Comment by RassK** [comment]
@ritesh-harry It's best to try with small sample app using manual instrumentation ([opentelemetry-dotnet](https://github.com/open-telemetry/opentelemetry-dotnet))

Component responsible for HTTP in calls:
- [OpenTelemetry.Instrumentation.AspNetCore](https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/src/OpenTelemetry.Instrumentation.AspNetCore)
- [OpenTelemetry.Instrumentation.AspNet](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/tree/main/src/OpenTelemetry.Instrumentation.AspNet)

Component responsible for HTTP out calls:
- [OpenTelemetry.Instrumentation.Http](https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/src/OpenTelemetry.Instrumentation.Http)

If these output all the necessary, then it's definitely the issue in OpenTelemetry AutoInstrumentation.

**Comment by pellared** [comment]
On .NET Framework we just use [OpenTelemetry.Instrumentation.Http](https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/src/OpenTelemetry.Instrumentation.Http) to instrument incoming HTTP requests. So it clearly won't work for 
out-of-the-box.

I have found out that there is a way to instrument OWIN using https://github.com/open-telemetry/opentelemetry-dotnet-contrib/tree/main/src/OpenTelemetry.Instrumentation.Owin. You can try using it by following the document instructions. 

Just the "Step 3" needs to be done differently by using a "plugin approach" .

The plugin should look probably like:

```csharp
namespace API.Service

using OpenTelemetry.Instrumentation.Owin;
using OpenTelemetry.Trace;

public class OTelPlugin 
{
    public TracerProviderBuilder ConfigureTracerProvider(TracerProviderBuilder builder)
    {
        return builder.AddOwinInstrumentation();
    }
}   
```

And you would need to set it via `OTEL_DOTNET_AUTO_PLUGINS` e.g. by setting `API.Service.OtelSdkPlugin, API.Service, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null`

References:

- https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/main/docs/config.md#additional-settings
- https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/main/docs/plugins.md
- https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/36dd368fc186c165e7e2a36ec0455aef99ad01a7/examples/playground/run.sh#L16

The alternative way would be to add OWIN bytecode instrumentation. However, we cannot say when it could be implemented unless you are willing to contribute. You can create an issue for adding instrumentation for [OWIN/Katana](https://github.com/aspnet/AspNetKatana/).

**Comment by pjanotti** [comment]
SIG: we will evaluate post-GA if we want to provide this out-of-the-box or not.

**Comment by Kielek** [comment]
Closing. #2832 is a correct issue to track this feature.
