### ISSUE TITLE
OpenTelemetry.AutoInstrumentation NuGet Installation Fails on .NET Framework 4.7.2

### ISSUE THREAD

**Issue by kaftw-nexient** [open-telemetry/opentelemetry-dotnet-instrumentation#2735]
# Bug Report

## Symptom

**Describe the bug**
When installing the OpenTelemetry.AutoInstrumentation NuGet package (version 1.0.0-rc.1) through NuGet Package Manager or through PowerShell fails for a .NET Framework 4.7.2 project with the following error:
Could not install package 'OpenTelemetry.AutoInstrumentation.Runtime.Native 1.0.0-rc.1'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.7.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.				

**Expected behavior**
The package and its dependencies should install without error on supported versions of .NET Framework.

**Screenshots**
![image](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/assets/128085964/80b1d050-df8a-4ea7-a16b-08c861acb273)
![image](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/assets/128085964/c70f12e2-409e-4108-9f82-a9b38a94980e)
![image](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/assets/128085964/722a2105-aeaf-4c51-a2ed-56038dd9cda9)

**Runtime environment (please complete the following information):**

- OpenTelemetry Automatic Instrumentation version: 1.0.0.-rc.1
- OS: Windows Server 2016 Standard
- .NET version: .NET Framework 4.7.2

**Additional context**
I tried creating a .NET Framework 4.7.2 console app and got the same error. Also the same error for .NET 4.8. Works fine in .NET 6.

## Reproduce

 1. Open .NET Framework 4.7.2 solution in Visual Studio 2022 Professional
 2. Open NuGet Package Manager
 3. Try to install OpenTelemetry.AutoInstrumentation prerelease version 1.0.0.-rc.1
 4. Notice error message in Error List window

**Comment by pjanotti** [comment]
Hi @kaftw-nexient, the issue is that the NuGet packages don't support old style `csproj`. They work if you target `net472` using the SDK style `csproj` files. I'm not sure if we can improve the error message. For the time being I'm going to add a note to the troubleshooting doc.

**Comment by RassK** [comment]
The good side is that .NET Framework should work fine without the Nuget package, maximum you may need to adjust some assembly binding rules. .NET (Core) in the other hand already has the newer style `csproj`.
