### ISSUE TITLE
Usage of MockZipkinCollector in integration tests

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-dotnet-instrumentation#274]
Currently, the integration tests are using [`MockZipkinCollector`](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/main/test/integration-tests/IntegrationTests.Helpers/MockZipkinCollector.cs).

1. Should we test against OTLP instead of Zipkin and create a `MockOtlpCollector`?
2. Should we test against all supported exporters in the integration tests?
3. Is it needed for the beta release?

**Comment by pellared** [comment]
My opinion

ad. 1. Yes. OTLP exporter does not do any [transformations](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk_exporters/zipkin.md) so the assertions would be more trustworthy.
ad. 2. We can have only some integration tests to test all of the exporters. However, we should not run all the tests against all possible exporteres.
ad. 3. No. It would postpone getting initial feedback.

**Comment by nrcventura** [comment]
@pellared I agree with your opinions. 
For 1. We'll eventually need to decide if we want the tests to be grpc based, or http based.
For 2. I think that we just need end to end tests just so that we have some confidence that we are bootstrapping all of the correct dependencies.

**Comment by pellared** [comment]
> We'll eventually need to decide if we want the tests to be grpc based, or http based.

I strongly prefer to use `grpc` as this is the default in https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/src/OpenTelemetry.Exporter.OpenTelemetryProtocol

This issue may be required for beta if we agree on: https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/issues/255#issuecomment-970116850

**Comment by pellared** [comment]
We ended up in `http/protobuf` per https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/issues/325

**Comment by RassK** [comment]
@pellared this seems done now?

**Comment by pellared** [comment]
@RassK Yes. Thanks.
