### ISSUE TITLE
[plugin] Add trace processor before exporter

### ISSUE THREAD

**Issue by muhaook** [open-telemetry/opentelemetry-dotnet-instrumentation#2750]
By adding a customized trace processor before the exporter in SDK, we can have a chance to check each Activity and decide if it is going to be exported. However, currently plugin is handled after [UseEnvironmentVariables()](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/36dd368fc186c165e7e2a36ec0455aef99ad01a7/src/OpenTelemetry.AutoInstrumentation/Instrumentation.cs#L119), so the processor added as below is always after the exporter. 
```
public class Plugin
{
    public TracerProviderBuilder ConfigureTracerProvider(TracerProviderBuilder builder)
    {
        return builder.AddProcessor(new MyProcessor());
    }
}
```
can we do sth in plugin at the very beginning of CreateTracerProviderBuilder ?
Discussions can be found in slack: https://cloud-native.slack.com/archives/C01NR1YLSE7/p1689279656814439

Another request is can we do sth in plugin after [TracerProvider ](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/36dd368fc186c165e7e2a36ec0455aef99ad01a7/src/OpenTelemetry.AutoInstrumentation/Instrumentation.cs#L122C1-L122C1) got build or at the end of [Initialize()](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/36dd368fc186c165e7e2a36ec0455aef99ad01a7/src/OpenTelemetry.AutoInstrumentation/Instrumentation.cs#L66C4-L66C4). Sth similar to [_pluginManager.Initializing()](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/36dd368fc186c165e7e2a36ec0455aef99ad01a7/src/OpenTelemetry.AutoInstrumentation/Instrumentation.cs#L96), but it is `_pluginManager.Initialized()`. We may start to collect some metrics that are related to the TracerProvider etc

**Comment by pellared** [comment]
The proposal is to change the plugin contract to have `Before*` and `After*` methods.

**Comment by RassK** [comment]
Ordering processors should be now fixed

> Another request is can we do sth in plugin after [TracerProvider ](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/36dd368fc186c165e7e2a36ec0455aef99ad01a7/src/OpenTelemetry.AutoInstrumentation/Instrumentation.cs#L122C1-L122C1) got build or at the end of [Initialize()](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/36dd368fc186c165e7e2a36ec0455aef99ad01a7/src/OpenTelemetry.AutoInstrumentation/Instrumentation.cs#L66C4-L66C4). Sth similar to [_pluginManager.Initializing()](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/36dd368fc186c165e7e2a36ec0455aef99ad01a7/src/OpenTelemetry.AutoInstrumentation/Instrumentation.cs#L96), but it is `_pluginManager.Initialized()`. We may start to collect some metrics that are related to the TracerProvider etc

I think this could be combined with passing the built provider reference as well. Currently we don't pass the provider to a plugin.

**Comment by muhaook** [comment]
Thanks, yes, passing _tracerProvider and _meterProvider in would be great; otherwise, I can use reflection to get the private ones:
```
    private static TracerProvider? _tracerProvider;
    private static MeterProvider? _meterProvider;
```

**Comment by RassK** [comment]
@muhaook could you check #2760 if that adds all the initialization callbacks you need?

**Comment by muhaook** [comment]
Looks perfect to me, Thanks @RassK !
