### ISSUE TITLE
Smoke tests for `OTEL_DOTNET_AUTO_EXCLUDE_PROCESSES` when profiler disabled

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-dotnet-instrumentation#2771]
Am I correct that there are no tests for the changed code? All existing tests involving `OTEL_DOTNET_AUTO_EXCLUDE_PROCESSES` work with .NET Profiler therefore the applications would be excluded on native code layer.

See https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/2754#pullrequestreview-1532601427

_Originally posted by @pellared in https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/2765#discussion_r1270575214_

**Comment by RassK** [comment]
Tests overview:

- [x] StartupHook (managed) only tests
- [ ] CLR Profiler (native) only tests
- [ ] StartupHook + CLR Profiler tests [^1]

[^1]: Could be derived from the separate test results also. Could be considered for just in case.
