### ISSUE TITLE
Log Events for Lazy Loaded Instrumentations in OpenTelemetry .NET Auto-Instrumentation

### ISSUE THREAD

**Issue by rajkumar-rangaraj** [open-telemetry/opentelemetry-dotnet-instrumentation#2809]
The OpenTelemetry .NET SDK logs verbose messages, such as when instrumentations are added (e.g., 'HttpClientInstrumentation'). 

```
OpenTelemetry-Sdk - Level: [Verbose], EventId: [46], EventName: [TracerProviderSdkEvent], Message: [TracerProviderSdk event: 'Instrumentations added = "HttpClientInstrumentation".']
```
However, the OpenTelemetry .NET Auto-Instrumentation, which utilizes lazy loading, does not currently log these types of events. I propose we include logging for such events, as this information is valuable for understanding which instruments are enabled and can ease troubleshooting.

**Comment by RassK** [comment]
This seems to be the feature of `TracerProviderBuilder`. `LazyInstrumentationLoader` has no reference to `TracerProviderBuilder` and also could operate outside of the `TracerProviderBuilder` scope (when `TracerProviderBuilder` is already built) - so could not be referenced anyway.

`LazyInstrumentationLoader` utilizes `"InstrumentationInitializer.Name started"` (Debug) and in case of a failure `"InstrumentationInitializer.Name failed"` (Error).

We can kind of replicate the message, I think this is our best option.

**Comment by pjanotti** [comment]
SIG: no action: use @RassK 's suggestion.
