### ISSUE TITLE
Support Alpine

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-dotnet-instrumentation#282]
1. Update the GH workflow to additionally run integration tests in an Alpine container.
2. Start releasing binaries for Alpine.
3. Fix issues if there are any.

**Comment by nrcventura** [comment]
I think that it's a good idea to at least run a subset of the integration tests on Alpine. Most of the bugs that I've encountered when supporting native profiler code surfaced only when running on Alpine.
