### ISSUE TITLE
Add tests for Rule Engine classes

### ISSUE THREAD

**Issue by Kielek** [open-telemetry/opentelemetry-dotnet-instrumentation#2826]
>> Good catch! Is there a way to add a test for this?

> There are currently no tests for any of the rules. We definitely need to add them. Thanks for pointing it out!

_Originally posted by @rajkumar-rangaraj in https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/issues/2825#issuecomment-1673743017_

**Comment by nrcventura** [comment]
Closing per SIG discussion.
