### ISSUE TITLE
Add OWIN bytecode instrumentation for .NET Framework

### ISSUE THREAD

**Issue by matt-hensley** [open-telemetry/opentelemetry-dotnet-instrumentation#2832]
# Feature Request

**Are you requesting automatic instrumentation for a framework or library? Please describe.**

- Framework or library name: Microsoft.Owin
- Library type: web framework
- Library version: 4.2.2

**Is your feature request related to a problem? Please describe.**
It is not possible to automatically collect signals from applications using OWIN.

**Describe the solution you'd like**
Out of the box support for collecting signals from applications using OWIN. Ideally this would include metrics and traces.

**Describe alternatives you've considered**
It would be possible to extend the OWIN instrumentation in [opentelemetry-dotnet-contrib](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/tree/main/src/OpenTelemetry.Instrumentation.Owin) to act as a plugin, [as described in the comments of another issue](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/issues/2733#issuecomment-1635448069).

**Additional context**
.NET Framework web application templates use OWIN by default, and have for some time.

Any new .NET Framework 4.8.1 projects, and many existing projects, will not be able to easily use auto instrumentation. This version of the runtime [has no EOL date](https://learn.microsoft.com/en-us/lifecycle/products/microsoft-net-framework).

**Comment by nrcventura** [comment]
Closing per SIG discussion.
