### ISSUE TITLE
Exported logs duplication

### ISSUE THREAD

**Issue by lachmatt** [open-telemetry/opentelemetry-dotnet-instrumentation#2856]
For `AspNetCore` applications, with `LoggingBuilder` integration enabled with `OpenTelemetry.AutoInstrumentation.AspNetCoreBootstrapper` and bytecode instrumentations enabled, exported logs are duplicated.
It seems that [check](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/15536eb92e9fcfd2d393e2cc8c5a11ba08c9e172/src/OpenTelemetry.AutoInstrumentation/Logger/LogBuilderExtensions.cs#L38) doesn't work anymore (I think there were changes to how `OpenTelemetryLoggerProvider` is added to services collection [here](https://github.com/open-telemetry/opentelemetry-dotnet/commit/ddcff7de3c7f1d17a775b6d131900e4097524b78#diff-9bc22b4d5209176befb274dab509d1e6e60def80ee290447bf9c1bb25c7a4a8f)).

`EnableLogsWithCLRAndHostingStartup` test from `LogTests` tests that configuration, but it exits with success as soon as first `LogRecord` with expected body is received, there are actually 2.

**Comment by Kielek** [comment]
@open-telemetry/dotnet-instrumentation-approvers, I am adding this issue to 1.0.0 milestone.
