### ISSUE TITLE
Environment Variables to align with other OpenTelemetry Auto Instrumentations

### ISSUE THREAD

**Issue by EStork09** [open-telemetry/opentelemetry-dotnet-instrumentation#2874]
# Feature Request

**Are you requesting automatic instrumentation for a framework or library? Please describe.**

- Framework or library name : `Microsoft.Data.SqlClient` and `System.Data.SqlClient`, `System.Net.Http.HttpClient` and `System.Net.HttpWebRequest`
- Library type: http, database
- Library version: Mixed

**Is your feature request related to a problem? Please describe.**
We are trying to get more data out of our traces like we do with other auto instrumented languages (i.e. Java, Node, Python). We notice the sql.statement attributes and ability to add headers as attributes with environment variables aren't included by default like they are with the others.

**Describe the solution you'd like**
Set of environment variables of other options to allow for things such as sql.statement or http headers to be added as attributes (tags). Such as `OTEL_INSTRUMENTATION_HTTP_CAPTURE_HEADERS` 

**Describe alternatives you've considered**
None

**Additional context**
I have very low experience with .NET so I could be very confused and missing something. We are working with some applications that are .NET Framework and have no access to the source code and want to leverage auto instrument to get as much data as we can.
I believe this is sort of similar #2331, if there is a way to do this already I might just not see the documentation and apologize.

**Comment by Kielek** [comment]
@EStork09, internally instrumentation for 
SqlClient is based on https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/src/OpenTelemetry.Instrumentation.SqlClient
HttpClient is based on https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/src/OpenTelemetry.Instrumentation.Http

Could you please create feature requests (separate for each instrumentation) in this repository https://github.com/open-telemetry/opentelemetry-dotnet/?
If possible please link lack of feature parity with other languages. When it will be implemented we can upgrade dependency and bring the feature here.

**Comment by Kielek** [comment]
SIG meeting: Closing. See previous comment.
