### ISSUE TITLE
Auto-instrumentation logs 2 or 3 times in .net 7, but working fine in .net 6

### ISSUE THREAD

**Issue by sam9291** [open-telemetry/opentelemetry-dotnet-instrumentation#2896]
# Bug Report
I discovererd that when I use the version 0.7 and 1.0.0-rc.2, dotnet running with `<TargetFramework>net7.0</TargetFramework>` generates 3 logs for every log. This doesn't happen when using `<TargetFramework>net6.0</TargetFramework>`

## Symptom

When running in .net 7, we see multiple duplicated logs

**Describe the bug**
API running in .net 7 with duplicated logs

![image](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/assets/5232883/ab90cd9a-8ea7-4808-aff6-06ded9f138ed)

**Expected behavior**

.net 6 API output logs running as expected with 1 log per log.

![image](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/assets/5232883/11a07825-834d-42fb-b2e0-959355c10b03)

**Runtime environment (please complete the following information):**

- OpenTelemetry Automatic Instrumentation version: [e.g. 1.0.0-rc.2]
- OS: Windows 11
- .NET Core 6 vs 7
- Happens in Visual studio on Windows as well as in linux docker containers

**Additional context**
I created an extract of the console output in text in my fork here:

https://github.com/sam9291/opentelemetry-dotnet-instrumentation/blob/main/issue/dotnet-6-startup-output.txt
https://github.com/sam9291/opentelemetry-dotnet-instrumentation/blob/main/issue/dotnet-7-startup-output.txt

I noticed the bug in another project context, in my testing on that project we had 3 times the logs, in the one I created here, I have only 2 times, not sure why.

## Reproduce

I created a fork of the repo and added an issue folder with two sample APIs, one in .net 6 and one in .net 7 with auto instrumentation using 1.0.0-rc.2 that we can run in visual studio.

https://github.com/sam9291/opentelemetry-dotnet-instrumentation/tree/main/issue

1. Checkout the fork branch https://github.com/sam9291/opentelemetry-dotnet-instrumentation/tree/main/issue
2. Run both APIs in AutoInstrumentationIssueExample.sln using visual studio
3. Check the console output

**Comment by Kielek** [comment]
Ref #2859. I hope it is fixed already on main. Could you please check current main behavior?

@lachmatt, FYI.

**Comment by sam9291** [comment]
> Ref #2859. I hope it is fixed already on main. Could you please check current main behavior?
> 
> Continous integration artifact can be found under https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/actions/runs/6028572140
> 
> @lachmatt, FYI.

Nice, I tested the artifacts from the build, I confirm it is working as expected in .net7 thanks!

**.net6**

![image](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/assets/5232883/0ab10082-e394-47b7-a374-63720edc10b2)

**.net7**

![image](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/assets/5232883/5d409434-2769-441d-8fa5-c4584922d9ed)
