### ISSUE TITLE
`TraceProvider` is not disposed

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-dotnet-instrumentation#290]
This following field is not disposed at all:

https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/09ea838561d4e8d466c0ee53e975fd3cd0c89848/src/OpenTelemetry.ClrProfiler.Managed/Instrumentation.cs#L19

This causes loss of exported spans when the batch export processor is used.

Probably the easiest thing to fix it would be creating some object with a finalizer that would dispose the `TraceProvider`.

**Comment by nrcventura** [comment]
Another option is to potentially subscribe to the shutdown/terminate event and then trigger the dispose. If we subscribe to the correct event(s), I think that we'll have about 30 seconds (or something similar) to export as much data as possible. New Relic uses the [`ProcessExit` and `DomainUnload` events to trigger similar things](https://github.com/newrelic/newrelic-dotnet-agent/blob/2ba99ea91ac20f79af40259e485949c6b3b1aac3/src/Agent/NewRelic/Agent/Core/AgentInitializer.cs#L29-L31) (The `OnExit` property in that code is later updated with the real shutdown logic that is desired).
