### ISSUE TITLE
Proposal: Always use the startup hook for non-.NET framework apps

### ISSUE THREAD

**Issue by nrcventura** [open-telemetry/opentelemetry-dotnet-instrumentation#291]
I believe that the StartupHook makes the most sense as the go-forward strategy for bootstrapping the OTel SDK for most "modern" applications. At this point, the profiling APIs are only necessary when an application needs to leverage byte-code instrumentation. Furthermore, a solution that doesn't rely on the profiling API should be better able to take advantage of the speed improvements provided by newer runtimes.

Byte code instrumentation in .NET core 3.1+ (and .NET 5+) is currently only needed when:

1. The application uses a library that is not instrumented using the OTel compatible Activity/Span and Metric APIs
2. There isn't an existing OTel instrumentation library that can adapt a library's existing telemetry to OTel's telemetry
3. The application wants to use custom instrumentation to provide additional insight, but does not have access to the source code to use the .NET APIs to add the additional telemetry directly.

Scenarios 1 and 2 should get smaller as time goes on. Scenario 3 is an unknown, but I suspect that it does not represent the majority of use cases.

Another problem with the current bootstrapping process for these newer runtimes is that we've encountered a timing issue where the profiler is attempting to bootstrap the OTel SDK before the required assemblies are available. The Startup Hook does not exhibit this same problem.

As a result I'm recommending that we consider doing one of the following for .NET core (and .NET 5+):

1. Disable the bootstrapping process currently being used in the native profiler code, and rely on users to configure the Startup Hook related environment variables.
2. Replacing the current bootstrapping process being used in the native profiler with code that automatically configures the Startup Hook environment variables.

My current recommendation is approach 1, because I think that it will allow for an easier migration when the customer no longer needs byte-code instrumentation. It might also make things more transparent. The setting of the additional environment variables could be handled by setup scripts.

**Comment by pellared** [comment]
During the SIG meeting, we agreed that this is a good proposal and the documentation should be updated accordingly.
