### ISSUE TITLE
[Flaky test] IntegrationTests.ModuleTests.DefaultNoExporters

### ISSUE THREAD

**Issue by pjanotti** [open-telemetry/opentelemetry-dotnet-instrumentation#2917]
Failed run: https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/actions/runs/6103080295/job/16563027367#step:7:806

Successful re-run: https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/actions/runs/6103080295

**Comment by RassK** [comment]
That must have been very very quick process exit 😮 
Literally starting the process and then the very next thing is to query process name and by that time the process is already closed.

At first seems very unlikely transient exception.

**Comment by rajkumar-rangaraj** [comment]
SIG: Tests did not fail again.
