### ISSUE TITLE
Use `OTEL_DOTNET_AUTO_` as prefix for env vars introduced in this repository

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-dotnet-instrumentation#293]
Motivation: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/sdk-environment-variables.md#language-specific-environment-variables

_Originally posted by @pjanotti in https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/288#discussion_r763480106_

**Comment by nrcventura** [comment]
After thinking about this further, Java has the concept of an `AutoConfigure` module that can be used by both the Java agent/tracer and SDK that is responsible for automatically configuring the Java SDK. I don't think that they are using `Auto` in their environment variable names. We might want to take a similar approach too.

**Comment by pellared** [comment]
I made a quick look and I think most of the env vars come from SDK. The auto-instrumentation specific env vars have `OTEL_JAVAAGENT_` prefix. See: https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/docs/agent-config.md#configuring-the-agent. We could use `OTEL_DOTNETAGENT_`, however, I do not like the "Agent" term 😄

**Comment by pellared** [comment]
Per the SIG meeting discussion, we propose to use `OTEL_DOTNET_AUTO_` in this repository. 
@open-telemetry/dotnet-maintainers are you OK with that?
