### ISSUE TITLE
Remove internal documentation

### ISSUE THREAD

**Issue by Kielek** [open-telemetry/opentelemetry-dotnet-instrumentation#2933]
> Do we want to maintain docs here if they're upstream now? Shouldn't we remove them?

_Originally posted by @theletterf in https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/2930#discussion_r1319461510_

**Comment by pellared** [comment]
I think it is better if the docs also stay in our repository so that we update docs during development.

Then, during releasing, it would be easy for us to update opentelemtry.io docs just by looking at diff.

**Comment by pjanotti** [comment]
We also can allow ourselves to go into internal details, link to issues, code, a more internal dev oriented approach.

**Comment by rajkumar-rangaraj** [comment]
SIG: No plans to remove internal doc from this repo. We could use as a reference to create official docs.
