### ISSUE TITLE
True correlation between trace,logs and metrics

### ISSUE THREAD

**Issue by gajavallisantosh** [open-telemetry/opentelemetry-dotnet-instrumentation#2943]
True correlation between trace,logs and metrics

True correlation between trace,logs and metrics

**Describe the bug**
Unable to correlate with the same tarceid/span id between a trace,log and metrics

**Expected behavior**
Please give a working example or show me a link where i can get true corrleation between 3 pillars of observability

**Screenshots**

**Comment by gajavallisantosh** [comment]
@Kielek Thank you for the prompt response. Please do let me know if this gets sorted out in future

**Comment by Kielek** [comment]
@gajavallisantosh, please observe the changelog/release notes in https://github.com/open-telemetry/opentelemetry-dotnet repository
