### ISSUE TITLE
OpenTelemetry .NET Automatic Instrumentation v1.0.0 opentelemetry.io blog post

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-dotnet-instrumentation#2945]
Create a blog post on https://opentelemetry.io/blog/ that OpenTelemetry .NET Automatic Instrumentation v1.0.0 has been released.

Previous blog posts:
- https://github.com/open-telemetry/opentelemetry.io/pull/1530
- https://github.com/open-telemetry/opentelemetry.io/pull/1340

**Comment by Kielek** [comment]
https://opentelemetry.io/blog/2023/otel-dotnet-auto-instrumentation/
