### ISSUE TITLE
Automate generate changelog entries for updated dependencies

### ISSUE THREAD

**Issue by Kielek** [open-telemetry/opentelemetry-dotnet-instrumentation#2953]
> open-telemetry/dotnet-instrumentation-approvers, as we are after GA, should we start documenting this kind of changes in changelog?

_Originally posted by @Kielek in https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/issues/2932#issuecomment-1711218395_

While working on this, please include direct and indirect dependencies.

**Comment by nrcventura** [comment]
Closing per SIG discussion.
