### ISSUE TITLE
Nuget: do not run any rules on StartupHook

### ISSUE THREAD

**Issue by pjanotti** [open-telemetry/opentelemetry-dotnet-instrumentation#2959]
In principle, the issues detected by the mandatory rules can't happen or not applicable to instrumented apps launched using the NuGet script.

* The application in exclusion list rule, is not applicable to the NuGet, since it is a matter of direct launching the app instead of using the script
* The minimum framework version rule are not relevant since the NuGet package only targets the supported runtime frameworks, so the user can't build for such configuration.

The optional rules are being disabled via #2958.

**Comment by rajkumar-rangaraj** [comment]
This topic was discussed earlier, at which time we decided not to change the behavior for NuGet. Has anything changed since then?

**Comment by pjanotti** [comment]
@rajkumar-rangaraj I complete forgot about #2565. I guess that at the time that you raised the issue I didn't realize that the rules didn't add much value in the NuGet case. Anyway, at this point is seems worth the consideration, but low priority given that the more expensive rules are being disabled via #2958.

**Comment by pjanotti** [comment]
Yes, let's close this one.
