### ISSUE TITLE
Add Windows Forms Instrumentation

### ISSUE THREAD

**Issue by JBodkin-Amphora** [open-telemetry/opentelemetry-dotnet-instrumentation#2982]
# Feature Request

I'm trying to experiment capturing traces from a Windows Form application however I'm encountering an error when clicking a button. The details section on the unhandled exception dialog doesn't expand, so I'm not sure how to progress to resolve the issue.

I've created a class to implement the `OnMethodEnd` function (and registered the integration name), as follows:
```
[InstrumentMethod(
    assemblyName: "System.Windows.Forms",
    typeName: "System.Windows.Forms.Button",
    methodName: "OnClick",
    returnTypeName: ClrNames.Void,
    parameterTypeNames: new string[] { "System.EventArgs" },
    minimumVersion: "4.0.0",
    maximumVersion: "4.65535.65535",
    integrationName: "WinForms",
    type: InstrumentationType.Trace)]
internal class ButtonIntegration
{
    internal static CallTargetReturn OnMethodEnd<TTarget>(TTarget instance, Exception exception, in CallTargetState state)
    {
         return CallTargetReturn.GetDefault();
    }
}
```

When I click the button, I'm getting the following unhandled error:

![image](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/assets/98747854/b0e68dab-37f1-4a0f-ba43-c4ca90c6a457)

The implementation of the button shows a message box:

```
private void button1_Click(object sender, EventArgs e)
{
    MessageBox.Show("Body", "Title");
}
```

Do you have any ideas?

**Comment by pjanotti** [comment]
The first thing that cross my mind is that the assemblies needed to instrument a .NET Framework may not be registered on the GAC. However, that is a very wild guess. Could you provide a short repro? Debug logs would also be helpful, see [here](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/main/docs/troubleshooting.md#enable-detailed-logging).

**Comment by JBodkin-Amphora** [comment]
Please see this [commit](https://github.com/JBodkin-Amphora/opentelemetry-dotnet-instrumentation/commit/4a1692390c2fdc9dc4be6dd045c24249bf3fcacf) for a small application that can be used to reproduce the issue.

These are the log files:
[otel-dotnet-auto-native-Example-2552.log](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/files/12748514/otel-dotnet-auto-native-Example-2552.log)
[otel-dotnet-auto-Example.exe-2552-20230928.log](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/files/12748515/otel-dotnet-auto-Example.exe-2552-20230928.log)
[otel-dotnet-auto-Example.exe-2552-Loader-20230928.log](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/files/12748517/otel-dotnet-auto-Example.exe-2552-Loader-20230928.log)

From further debugging, the issue seems to be when this method is called `OpenTelemetry.AutoInstrumentation.CallTarget.CallTargetInvoker.BeginMethod(2 argument{s})`. It looks like it isn't able to call the method which throws an Exception and then the Exception method cannot be called either.

**Comment by JBodkin-Amphora** [comment]
From further debugging, I've found that when it tries to invoke the `OpenTelemetry.AutoInstrumentation.CallTarget.CallTargetInvoker.BeginMethod(2 argument{s})` method, it is throwing a [MethodAccessException](https://learn.microsoft.com/en-us/dotnet/api/system.methodaccessexception?view=net-6.0), is there a layer of security that needs to be disabled?

**Comment by JBodkin-Amphora** [comment]
The problem was that the `ButtonIntegration` wasn't public, after fixing that, its working

**Comment by Kielek** [comment]
@JBodkin-Amphora, great to hear that you were able to handle the issue.
Could you please share your use case for winforms instrumentation? Based on this, we can consider if it generic enough to include it to this repository.
