### ISSUE TITLE
Describe the relationship with opentelemetry-dotnet

### ISSUE THREAD

**Issue by atrauzzi** [open-telemetry/opentelemetry-dotnet-instrumentation#299]
I'm a bit confused right now about the open telemetry landscape as it pertains to .NET.

There's this repo: https://github.com/open-telemetry/opentelemetry-dotnet

What is the relationship between the two?  If I wanted to instrument an ASP.NET application, would I ultimately want to have both this and the corresponding library from the other repo?  Or is this one implicitly part of any scenario-specific instrumentation?

**Comment by pellared** [comment]
> I'm a bit confused right now about the open telemetry landscape as it pertains to .NET.
> 
> There's this repo: https://github.com/open-telemetry/opentelemetry-dotnet
>
> What is the relationship between the two?

This repository implements [automatic-instrumentation](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/glossary.md#automatic-instrumentation) for .NET.  It is somehow similar to https://github.com/open-telemetry/opentelemetry-java-instrumentation for Java.

If I wanted to instrument an ASP.NET application, would I ultimately want to have both this and the corresponding library from the other repo? Or is this one implicitly part of any scenario-specific instrumentation?

This repo already contains ASP.NET instrumentation. It means that using only this repository should be good enough. Still, it is possible to write some customization using the [OTel .NET SDK](https://github.com/open-telemetry/opentelemetry-dotnet). See more here: https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/main/docs/USAGE.md#customization

Take notice that this repository is in the early stage of development. We would appreciate any help.

**Comment by atrauzzi** [comment]
I'm still a bit confused.

If this library and the other one both perform ASP.NET tracing, which should I use? Why?

**Comment by pellared** [comment]
I think that the key differences are:

1. Does not require code changes to an application.
1. Adds auto-instrumentation to libraries that are not using `System.Diagnostics.Activity` like GraphQL (_it works only when the auto-instrumentation is initialized via the .NET Profiler_)

Why should you use it? Mainly for sake of ease of use and quicker getting your application instrumented.

You can also read more here: https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/main/docs/DESIGN.md

_I am keeping this issue open as I think we should describe it better._
