### ISSUE TITLE
Opentelemetry Autoinstrumentation Plugin failing to load when running .NET Application

### ISSUE THREAD

**Issue by ViplavC** [open-telemetry/opentelemetry-dotnet-instrumentation#3015]
# Bug Report
Attached error

[Error.txt](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/files/13030602/Error.txt)

## Symptom

**Describe the bug**
I have been trying to add additional options to capture db.statement attribute using a plugin to my .NET application running on IIS using Opentelemetry .NET AutoInstrumentation script.

Here is the plugin code to capture additional metadata:

`namespace OTELPluginDB
{
    public class DBPlugin
    {
        public void ConfigureTracesOptions(OpenTelemetry.Instrumentation.SqlClient.SqlClientInstrumentationOptions options)
        {
            options.SetDbStatementForText = true;
            options.RecordException = true;
            options.EnableConnectionLevelAttributes = true;
            options.SetDbStatementForStoredProcedure = true;
        }
    }
}`

In the plugin, following version are used: Opentelemetry 1.6.0 and Opentelemetry.Instrumentations.SqlClient 1.5.1-beta.1 and the Opentelemetry AutoInstrumentation version is 1.0.2.

The plugin is compiled locally and then registered on GAC on the remote server where the application is installed, then it is referenced in the environment variable:
`OTEL_DOTNET_AUTO_PLUGINS = Opentelemetry.AutoInstrumentation.OTELPluginDB, Version=1.0.0.0, Culture=neutral, PublicKeyToken=bfcfed36a529c5b8`

Looking at the documentation for creating plugins: [https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/main/docs/plugins.md](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/main/docs/plugins.md) there is no mention as to how we need to integrate with Autoinstrumentation apart from referencing the assembly qualified name in the environment variable. My interpretation is that we need to install this plugins DLL in the GAC like the script is doing before referencing in the environment variable. So, i might be missing something here.

**Expected behavior**
Autoinstrumentation should atleast capture db.statement field based on the options provided in the backend.

**Runtime environment:**

- OpenTelemetry Automatic Instrumentation version: 1.0.2
- OS: Windows
- .NET version: ASP.NET Version:4.8

## Reproduce

 1. Create a plugin with SqlInstrumentation Options to set database statement capture
 2. Register the plugin's DLL on the remote server in GAC
 3. Add Environment variable OTEL_DOTNET_AUTO_PLUGINS
 4. Register AutoInstrumentation for IIS
 5. Run the application

Relevant logs attached from:
Windows: %ProgramData%\OpenTelemetry .NET AutoInstrumentation\logs\

[Policy-1-133421135351412448-2360-20231018.log](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/files/13030794/Policy-1-133421135351412448-2360-20231018.log)
[Policy-1-133421135351412448-2360-Loader-20231018.log](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/files/13030795/Policy-1-133421135351412448-2360-Loader-20231018.log)
[otel-dotnet-auto-native-w3wp-2360.log](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/files/13030796/otel-dotnet-auto-native-w3wp-2360.log)

**Comment by ViplavC** [comment]
@Kielek That worked, thanks! However, in the db.statement, only stored procedures are captured and not the SQL statements. System.Data.SqlClient is utilized in the code. It would be neat if SQL statements are also captured.

**Comment by ViplavC** [comment]
Looking at the docs: https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry.Instrumentation.SqlClient/README.md

`When using the built-in System.Data.SqlClient only stored procedure command names will ever be captured. When using the Microsoft.Data.SqlClient NuGet package (v1.1+) stored procedure command names, full query text, and other command text will be captured.`

This seems to be the reason for only capturing stored procedures and not the full query text. 

Is enabling capturing of full query text and other command text using autoinstrumentation something in the pipelines for System.Data.SqlClient data provider?

Also, is there any alternative way of capturing the SQL statements?

**Comment by Kielek** [comment]
Under the hood it it suing https://github.com/open-telemetry/opentelemetry-dotnet/blob/1.5.1-beta.1/src/OpenTelemetry.Instrumentation.SqlClient/SqlClientInstrumentationOptions.cs

I suppose you are looking for `SetDbStatementForText `

**Comment by ViplavC** [comment]
@Kielek Yes, i have that option already enabled in my plugin but as the code you shared also mentions, for the option `SetDbStatementForText`, only stored procedures are captured for System.Data.SqlClient dataprovider.

Do you know if enabling capturing of full query text and other command text using `SetDbStatementForText` will be supported in the future for System.Data.SqlClient data provider?

**Comment by pellared** [comment]
Related issue https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/issues/2331

**Comment by Kielek** [comment]
@ViplavC, if you are missing any features related to OpenTelemetry.Instrumentation.SqlClient please create issue under https://github.com/open-telemetry/opentelemetry-dotnet. Contribution by PR is always welcomed, but it is good practice to create issue first.

I am closing this issue as initial problem was solved.
