### ISSUE TITLE
Upgrade functions in powershell module

### ISSUE THREAD

**Issue by regaleagle** [open-telemetry/opentelemetry-dotnet-instrumentation#3018]
# Feature Request

**Is your feature request related to a problem? Please describe.**
I find it challenging to manage version upgrades when working with the powershell module version of the AutoInstrumentation. It requires a bunch of manual scripting workarounds to handle sort of smoothly when you would like to updates, particularly when using the IIS version on a server that has more than one site.

**Describe the solution you'd like**
A managed step in the module itself that will update the core libraries and version and will gracefully (or at least with no more interruption than the current IIS reset for that particular case) switch the service instrumentation to use the new DLLs
Alternatively - some guidance on the best way to achieve this in the docs

**Describe alternatives you've considered**
Right now I'm scripting around the fact that the module doesn't have a version check or update story by versioning the install folder, checking for existence of my requested version, unregistering the old version and installing the new then registering (to put it simply). This is still error prone and it's very tricky to manage the handover when there is more than one process running against the old.

**Comment by RassK** [comment]
I'll take a look.

**Comment by RassK** [comment]
@regaleagle Please check #3042 if this can do what you need.

**Comment by regaleagle** [comment]
@RassK Great, thanks so much! Sorry for the delayed response - holidays. I will take a look asap
