### ISSUE TITLE
Document Additional-deps and runtime package store

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-dotnet-instrumentation#303]
1. Add usage instructions to the `docs/USAGE.md` for the end-users
1. Add some more details in `docs/DESIGN.md`. There is an "Assembly Conflict Resolution" section which could be a good place to describe it. It could e.g. explain why both Additional-deps and runtime package store mechanisms are used together and how they interoperate. Moreover, I think it would facilitate discussions like this one: https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/272#issuecomment-976597141

_Originally posted by @pellared in https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/issues/272#issuecomment-977876618_

**Comment by pellared** [comment]
@rajkumar-rangaraj Can you work on it?

**Comment by rajkumar-rangaraj** [comment]
@pellared This is in my todo list. I will work on it.
