### ISSUE TITLE
Improve the OTel .NET depedencies resolving via improving OpenTelemetry.Instrumentation.AdditionalDeps

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-dotnet-instrumentation#307]
Just an additional idea for later. If we lift `OpenTelemetry.Instrumentation.AdditionalDeps`'s logic to `OpenTelemetry.ClrProfiler.Managed`, does this mean we can fix also all OTel.SDK packages and their dependencies automatically? ... also we don't double load different versions (or crash if it's loaded via StartupHook), in case user code uses the same packages?

_Originally posted by @RassK in https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/272#discussion_r752787495_

**Comment by RassK** [comment]
@rajkumar-rangaraj any progress with the runtime team about controlling these dependencies? Should we open an public GH issue in the runtime project, so we can follow along?

**Comment by pellared** [comment]
**SIG meeting**

@rajkumar-rangaraj will try to discuss it internally
@RassK will create an issue in dotnet/runtime

**Comment by RassK** [comment]
Addressed here https://github.com/dotnet/runtime/issues/66138

**Comment by RassK** [comment]
Closing as this issue won't be solved using additional deps. Needs completely other solution.
