### ISSUE TITLE
Update spdlog to 1.12.0

### ISSUE THREAD

**Issue by Kielek** [open-telemetry/opentelemetry-dotnet-instrumentation#3083]
Ref: https://github.com/gabime/spdlog/releases/tag/v1.12.0 - prerequisite to #2638

**Comment by professorabhay** [comment]
Hey @Kielek, I would like to resolve this. Can you share anything else related to this ?

**Comment by Kielek** [comment]
Please check documentation https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/aa07545a471ad3522d0b99a08d5baf1b8a2659dd/docs/internal/native-dependencies.md#spdlog
