### ISSUE TITLE
[kafka] duck typing improvements

### ISSUE THREAD

**Issue by lachmatt** [open-telemetry/opentelemetry-dotnet-instrumentation#3136]
> Since TTarget is always Confluent.Kafka.Consumer'2, you can always duck type (no chance of failure unless their API changes) and avoid doing it later. The only thing that changes is that now you'll need to change your call to the ConsumerCache so it's like: `ConsumerCache.TryGet(instance.Instance!, out var groupId)`

_Originally posted by @zacharycmontoya in https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/3055#discussion_r1389913770_

**Comment by nrcventura** [comment]
Closing per SIG discussion.
