### ISSUE TITLE
[kafka] add `server.address` attribute

### ISSUE THREAD

**Issue by lachmatt** [open-telemetry/opentelemetry-dotnet-instrumentation#3137]
> I strongly recommend to also set `server.address`, as this will be crucial to differentiate between different Kafka instances. The semantic conventions mandate it as "required if available".

_Originally posted by @pyohannes in https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/3055#discussion_r1391114808_

**Comment by nrcventura** [comment]
Haven't found a good way to get this data yet, so closing for now.
