### ISSUE TITLE
Shared store for Linux is shipping a folder for x86 that could be removed

### ISSUE THREAD

**Issue by pjanotti** [open-telemetry/opentelemetry-dotnet-instrumentation#3167]
The released zips for Linux glibc and musl include a x86 folder for the shared store. However, there is no Linux x86 runtime shipped by .NET. It should be ok to safely remove the folder and reduce the size of the bundle.

**Comment by RassK** [comment]
Linking the issue here also > https://github.com/dotnet/runtime/issues/7335
