### ISSUE TITLE
Please update README on how we can build this and try the code ourselves rather than the published script

### ISSUE THREAD

**Issue by varkey98** [open-telemetry/opentelemetry-dotnet-instrumentation#3184]
Please update docs so that we can build the code locally

**Comment by Kielek** [comment]
Very short answer, but it should allow you to handle most/all cases:
1. Download repository
2. Execute `nuke BuildTracer`
3. Output is under `[repo]\bin`.

**Comment by varkey98** [comment]
Thank you, let me try that
