### ISSUE TITLE
Remove unnecessary env vars

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-dotnet-instrumentation#319]
Support for following env vars can be removed:

- OTEL_TRACE_{0}_ANALYTICS_ENABLED
- OTEL_TRACE_{0}_ANALYTICS_SAMPLE_RATE
- OTEL_{0}_ENABLED ❓ 
- OTEL_{0}_ANALYTICS_ENABLED
- OTEL_{0}_ANALYTICS_SAMPLE_RATE

**Comment by Kielek** [comment]
`OTEL_{0}_ENABLED` to verify if GraphQl/MongoDB integration should be executed.
