### ISSUE TITLE
[docs] Continuous profiler

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-dotnet-instrumentation#3207]
Add documentation for Continuous profiler.

>> Separate comments describe:
>
> This should live in documentation e.g. in `docs/internal/continous-profiler.md`. I propose to make a separate issue for it.

_Originally posted by @pellared in https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/issues/3196#issuecomment-1874937253_

**Comment by pjanotti** [comment]
SIG: while experimental we can lift comments on the PR on use the location suggested above.
