### ISSUE TITLE
Telemetry loss when application is killed or when UnhandledException occurs

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-dotnet-instrumentation#321]
W should add a "Telemetry loss" section to the docs? 
Currently, I understand these situations will cause a data loss:
- abnormal termination of the process
- unhandled exception terminates the process

Could reduce the impact (but not avoid):
- use Simple processor
- use local OTel Collector for faster data handover

_Originally posted by @RassK in https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/294#discussion_r765653240_

**Comment by pellared** [comment]
Can we use the [`UnhandledException`](https://docs.microsoft.com/en-us/dotnet/api/system.appdomain.unhandledexception) event to handle the "unhandled exception terminates the process" use case?

**Comment by nrcventura** [comment]
> Can we use the [`UnhandledException`](https://docs.microsoft.com/en-us/dotnet/api/system.appdomain.unhandledexception) event to handle the "unhandled exception terminates the process" use case?

New Relic is capturing that event, but it seems like an interesting experiment to try. I don't know if there are gotchas with handling that event that could cause a side-effect for the running application.

**Comment by pellared** [comment]
Notes from SIG meeting

1. Check how upstream cleans up the Tracer (maybe
2. Remember also to handle SIG_INT and SIG_TERM 
3. We should add integration tests for applications throwing unhandled exception and is killed

**Comment by nrcventura** [comment]
Handling the `UnhandledException` event partially works. It can sometimes allow the the exporting of the spans that are sitting in the queue of the batch processor (depending on how quickly the application shuts down). However, if the unhandled exception occurs in code similar to the following  code (when handling the `UnhandledException` event), the "First activity" activity can be exported, but the "Second activity" activity does not get exported.
```csharp
using (var activity = myActivitySource.StartActivity("First activity"))
{
    Console.WriteLine("In activity 1");
}

using (var activity = myActivitySource.StartActivity("Second activity"))
{
    Console.WriteLine("In activity 2");
    throw new Exception("Exception inside of using statement.");
}
```
According to https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/try-finally the behavior for the "Second activity" activity is dependent on how the stack is unwound, so it's possible that the behavior can vary.

**Comment by pellared** [comment]
Would it help if would refactor the `public static class Instrumentation` to a singleton that would have the following code in its finalizer https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/1b1300325d5becad03a7038f39275a0ebfbca1ca/src/OpenTelemetry.AutoInstrumentation/Instrumentation.cs#L108-L119?

**Comment by nrcventura** [comment]
> Would it help if would refactor the `public static class Instrumentation` to a singleton that would have the following code in its finalizer?

I'm guessing that change will not help in all situations. Both finalizers and finally blocks are not guarantied to run in the case of unhandled exceptions or the ungraceful terminations of an app (such as the SIGKILL signal).

It might be possible to flush some of the "active" spans, like the one in the above scenario (assuming that Activity.Current is available in the UnhandledException event callback), but we'll likely see problems with lost spans when async code is involved.

Furthermore, I believe that it's possible for the application to finish shutting down before all of the data in the batch processor is flushed (https://codeblog.jonskeet.uk/2022/02/20/diagnosing-an-asp-net-core-hard-crash/).

**Comment by pellared** [comment]
> "Second activity" activity does not get exported.

Wouldn't the OTel .NET SDK behave in the same way?

**Comment by pjanotti** [comment]
Regarding the [OTel SDK snippet for unhandled exception](https://github.com/open-telemetry/opentelemetry-dotnet/blob/d716bb17cd8115a3c6d7afe6da74652000aa8372/docs/trace/reporting-exceptions/README.md#unhandled-exception):

Is it a OTel recommendation to record the exception on all spans of the chain? We are time constrained at that place, while it is very quick to walk the chain it does take extra time. Recording the exception just for the current activity seems enough, no?

**Comment by rajkumar-rangaraj** [comment]
Today we had a discussion in SIG meeting to control [`UnhandledException`](https://docs.microsoft.com/en-us/dotnet/api/system.appdomain.unhandledexception) event with a environment variable flag. We could provide control to user to turn-off this feature if it causes an issue. The plan was to create a new issue, but context matches to this issue hence continuing the conversation here to take feedback on it.

**Comment by nrcventura** [comment]
> Today we had a discussion in SIG meeting to control [`UnhandledException`](https://docs.microsoft.com/en-us/dotnet/api/system.appdomain.unhandledexception) event with a environment variable flag. We could provide control to user to turn-off this feature if it causes an issue. The plan was to create a new issue, but context matches to this issue hence continuing the conversation here to take feedback on it.

I think that with the environment variable flag, I'm more comfortable with also implementing #390 (for the unhandled exception use case).
