### ISSUE TITLE
Continuous profiler - exporter thread - graceful shutdown

### ISSUE THREAD

**Issue by Kielek** [open-telemetry/opentelemetry-dotnet-instrumentation#3216]
### Dispose thread

> Is there a way to dispose this thread?

_Originally posted by @rajkumar-rangaraj in https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/3196#discussion_r1440919726_

> 1. `Thread` is not implementing `IDisposable`. 
> 2. This thread is marked as background. [It will be killed by the runtime when all foreground tasks will be finished](https://learn.microsoft.com/en-us/dotnet/standard/threading/foreground-and-background-threads).
> 3. There is not need to care if all data are correctly _exported_. By the nature, we are sampling. In the worst case the process of handling one buffer will be not handled correctly. IMO it is fine.
>
> Technically, we could pass cancellation token and call it from 'Instrumentation.OnExit'. But it might extend killing process time. I would keep it as is, but if you thing otherwise, we can improve in follow up issue. What do you thint?

_Originally posted by @Kielek in https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/3196#discussion_r1441381638_

### Task.Delay/Cancellation Token

> Consider using Task.Delay with async pattern and if possible send cancellation Token as parameter.

_Originally posted by @rajkumar-rangaraj in https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/3196#discussion_r1440919353_
            
> Then `sampleExporter.Process()` should also accept a cancellation token so that the export can be interrupted during application shutdown

_Originally posted by @pellared in https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/3196#discussion_r1441395986_

> BTW I am not sure if adding Task.Delay here bill brings a lot of benefits. We are in the dedicated thread which handles calls synchrnously.

_Originally posted by @Kielek in https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/3196#discussion_r1441474296_

**Comment by pellared** [comment]
SIG meeting:

The issue is not that minor as .NET does NOT always get rid of Background threads which are still running.
