### ISSUE TITLE
Remove Microsoft.Extensions.* libraries from net folder

### ISSUE THREAD

**Issue by Kielek** [open-telemetry/opentelemetry-dotnet-instrumentation#3223]
> These libraries are present in the runtime store. Do we need to keep a copy of it in the net directory?

_Originally posted by @rajkumar-rangaraj in https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/3213#discussion_r1442079988_

**Comment by RassK** [comment]
I guess these can be any, not just `Microsoft.Extensions.*`. Post build scan the output of `net/` and `store/`, delete all duplicates.
