### ISSUE TITLE
Update native layer based on latest Datadog codebase

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-dotnet-instrumentation#323]
[Datadog](https://github.com/DataDog/dd-trace-dotnet) has recently made significant improvements in their native code.

One of the great improvements is getting rid of `integrations.json` in favor of  [`InstrumentationDefinitions`](https://github.com/DataDog/dd-trace-dotnet/blob/cee205b58877fd337a6dd2648860b0ce4d48fee7/tracer/src/Datadog.Trace/ClrProfiler/InstrumentationDefinitions.Generated.cs). I believe this code is a lot more performant. It should not be also hard to later add a hook for adding additional custom (e.g. vendor-specific) byte-code instrumentation.

We should consider making an "upstream sync" similar to https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/218.

**Comment by pellared** [comment]
SIG meeting notes:
Nice to have for beta (not must have).

**Comment by Kielek** [comment]
Done in scope of #2280
