### ISSUE TITLE
OTEL_SERVICE_NAME is override in the same IIS Application Pool

### ISSUE THREAD

**Issue by ShayYaari** [open-telemetry/opentelemetry-dotnet-instrumentation#3247]
Hello,

I'm facing an issue trying to use Open Telemetry in two .NET Framework (4.8) apps, both hosted in IIS and share the same Application Pool.

For each app, I updated the Web.config with the following:
`  <appSettings>
    <add key="OTEL_SERVICE_NAME" value="MyApp1"/>
  </appSettings>
`

and
`  <appSettings>
    <add key="OTEL_SERVICE_NAME" value="MyApp2"/>
  </appSettings>
`

Looking at the OpenTelemtry spans or metrics, it seems like only one of them is being used, determined on the first app being used.
Basically, after the IIS is restarted, if I perform a request from 'MyApp1' app, and then a second request to 'MyApp1' app, I can see two span reports, both with service.name = "MyApp1".
However if I restart IIS again and change the order (first calling 'MyApp2' app and then calling 'MyApp1' app, then I see two span reports both with service.name = "MyApp2".

I noticed as well that if I put the apps in two different application pools, then I get the right behavior (each span has its own correct service name).

Any idea? (I didn't see any documentation about the need to put apps in different application pool)

Thanks,
Shay

**Comment by RassK** [comment]
That's how ASP.NET Framework works, no connections to auto instrumentation.
https://techcommunity.microsoft.com/t5/iis-support-blog/how-to-prevent-web-config-files-to-be-overwritten-by-config/ba-p/297627

**Comment by nrcventura** [comment]
Closing this based on the discussion during the SIG meeting.
