### ISSUE TITLE
.NET Core IIS appSettings.json is ignored

### ISSUE THREAD

**Issue by ShayYaari** [open-telemetry/opentelemetry-dotnet-instrumentation#3248]
Hello,

I have a .NET core app (.NET Core 6.0), deployed in IIS.
I'm trying to update its OTEL_SERVICE_NAME by updating the appsettings.json as follows:

`
{
  "OTEL_SERVICE_NAME": "MyApp3",
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft.AspNetCore": "Warning"
    }
  },
  "AllowedHosts": "*"
}
`

When I restart the IIS, I can see this new config in the Configuration Editor in the IIS settings, however the `service.name` is not being updated in the spans and metrics I receive.

However, when I decide to update the `system.webServer/aspNetCore` and add this as an environment variables under 'environemntVariables`, then I do can see it has an impact on the span being collected.

I have not seen any documentation about it. Can you explain why the appsettings are ignored by environment variables are OK?

Thanks,
Shay

**Comment by RassK** [comment]
The "traditional" mechanism how auto instrumentation is configured is via environment variables.
There is currently no feature that converts ASP.NET Core settings to instrumentation options.

Currently the only exception is .NET Fx (the old framework), where `web.config` values are respected.
ASP.NET Core configuration brings also extra dependencies, which is not good.

**Comment by RassK** [comment]
Verified. `SetupOpenTelemetry` without `IServiceCollection` cannot read `appsettings,json`. 

```csharp
public static void SetupOpenTelemetry()
{
    var builder = Sdk.CreateTracerProviderBuilder()
        .AddAspNetCoreInstrumentation()
        .SetResourceBuilder(ResourceBuilder
            .CreateEmpty()
            .AddEnvironmentVariableDetector()
            .AddTelemetrySdk())
        .AddConsoleExporter();
       
    _tracerProvider = builder.Build();
}

public static void SetupOpenTelemetry(this IServiceCollection serviceCollection)
{
    serviceCollection.AddOpenTelemetry()
        .WithTracing(tracing => tracing
            .AddAspNetCoreInstrumentation()
            .SetResourceBuilder(
                ResourceBuilder
                    .CreateEmpty()
                    .AddEnvironmentVariableDetector()
                    .AddTelemetrySdk())
            .AddConsoleExporter());
}
```

**Comment by ShayYaari** [comment]
What about when I use auto instrumentation? What is the expected behavior in this case?

**Comment by RassK** [comment]
Does not support currently keys from appsettings.json. Instead environment variables should be used like you described for `system.webServer/aspNetCore`.

**Comment by nrcventura** [comment]
Closing per SIG meeting discussion:
- There is a work in the OTel specification for standardizing file based configuration, and this functionality should eventually be replaced with the behavior in that specification.
