### ISSUE TITLE
Remove x86 output for AdditionalDeps

### ISSUE THREAD

**Issue by RassK** [open-telemetry/opentelemetry-dotnet-instrumentation#3279]
### What

Currently we output both x86 and x64 for AdditionalDeps Windows project.

Here is the general overview of what we have:
o - we have output but no compatible binary in `net` folder.
x - we have properly supported output.
a - we use the old AnyCpu flag that makes compatible binary for x86 and x64 for .NET Framework.

(arm64) - means the planned route and not yet available.

|                                              | x86 | x64 | (arm64) | 
| -------------------------------| ----| ---- | --------- |
| Windows (.NET Framework) |  a  |   a   |        -      |
| Windows (.NET Core)           |  o   |   x   |        -      |
| Linux                                    |  -   |   x   |        x      |
| MacOS                                 |  -   |   x   |        -      |

### Propose

Cleanup AdditionalDeps by removing x86 output.

CC: @rajkumar-rangaraj

**Comment by zacharycmontoya** [comment]
Can you clarify why you'd like to remove the x86 AdditionalDeps files? .NET 6.0 is [officially supported on Windows x86](https://github.com/dotnet/core/blob/main/release-notes/6.0/supported-os.md) so it seems like we should also support it

**Comment by RassK** [comment]
@zacharycmontoya we do not have a build that supports x86 for Windows. GH CI is compiling .NET Core with AnyCpu flag which for .NET Core means current CPU instead of x86 + x64 like for .NET Fx. So as far as I understand the whole `net` folder is x64 binaries.

`o - we have output but no compatible binary in net folder.`

Original issue is here: https://github.com/dotnet/sdk/issues/26647

**Comment by RassK** [comment]
@rajkumar-rangaraj ah, forgot about x86 apps on x64 platform. Just tested this case and it seems working.

Currently bit surprised and not sure how this does work. does WOW64 do some dark magic?
I can see that the app reports correctly x86, debugging modules it successfully loads libs from the `net` folder, where dll's are supposed to be x64 🤔

**Comment by RassK** [comment]
Discussed it with @pjanotti, we managed to conclude that it's not entirely true that .NET Core does not have AnyCpu flag.
The process itself (exe) is compiled to x64 or x86. AnyCpu compiles it to the current machine platform (eg x64 machine = x64 exe). However libraries will be still in msil format.

**Comment by RassK** [comment]
Closing the issue now, nothing more to add.
