### ISSUE TITLE
CI Failure: IntegrationTests.AspNet.AspNetTests.SubmitsTraces 

### ISSUE THREAD

**Issue by pjanotti** [open-telemetry/opentelemetry-dotnet-instrumentation#328]
Test `IntegrationTests.AspNet.AspNetTests.SubmitsTraces` is falling on CI:

See https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/327#issuecomment-1016881463 and https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/runs/4874184601?check_suite_focus=true

**Comment by pellared** [comment]
Closing as duplicate https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/issues/295
