### ISSUE TITLE
Use `OTEL_{SIGNAL}_EXPORTER` to handle console exporter

### ISSUE THREAD

**Issue by Kielek** [open-telemetry/opentelemetry-dotnet-instrumentation#3289]
# Feature Request

**Are you requesting automatic instrumentation for a framework or library? Please describe.**

- 1.4.0 and current main

**Is your feature request related to a problem? Please describe.**

Spec changed 3 months ago: https://github.com/open-telemetry/opentelemetry-specification/commit/d72b0da79645432c62593f074c64ae44778680aa

**Describe the solution you'd like**

Support `console` for `OTEL_TRACES_EXPORTER`, `OTEL_METRICS_EXPORTER`, and `OTEL_LOGS_EXPORTER`.

**Describe alternatives you've considered**

N/A

**Additional context**

What to do with `OTEL_DOTNET_AUTO_TRACES_CONSOLE_EXPORTER_ENABLED`, `OTEL_DOTNET_AUTO_METRICS_CONSOLE_EXPORTER_ENABLED`, and `OTEL_DOTNET_AUTO_LOGS_CONSOLE_EXPORTER_ENABLED`.

**Comment by pellared** [comment]
> What to do with OTEL_DOTNET_AUTO_TRACES_CONSOLE_EXPORTER_ENABLED, OTEL_DOTNET_AUTO_METRICS_CONSOLE_EXPORTER_ENABLED, and OTEL_DOTNET_AUTO_LOGS_CONSOLE_EXPORTER_ENABLED.

I suggest that before dropping support we should first make a minor release where we  we mark it as deprecated in docs and emitting a warning (e.g. to console) when anybody uses any of these env vars that they are deprecated and are going to be removed in next minor release.
