### ISSUE TITLE
Invalid managed log path for IIS app

### ISSUE THREAD

**Issue by RassK** [open-telemetry/opentelemetry-dotnet-instrumentation#3312]
### What

Managed logs for .NET Framework IIS app are gathered to:
`C:\ProgramData\OpenTelemetry .NET AutoInstrumentation\logs\otel-dotnet-auto-\LM\W3SVC\3`

Should be in `logs` folder.

### Issue

Problematic code:
```csharp
using var process = Process.GetCurrentProcess();
var appDomainName = AppDomain.CurrentDomain.FriendlyName;

return string.IsNullOrEmpty(suffix)
    ? $"otel-dotnet-auto-{appDomainName}-{process.Id}-.log"
    : $"otel-dotnet-auto-{appDomainName}-{process.Id}-{suffix}-.log";
```

because appdomain name is `/LM/W3SVC/3/ROOT-1-133543106327420478` it will create deep dir instead of file.

### Suggestion

if `appDomainName` contains `/W3SVC/` replace appDomainName with `iisapp`.

**Comment by Kielek** [comment]
I think taht we should check if it contains any `\` or `/` and try to remove/repleace them to avoid nested folders.

**Comment by RassK** [comment]
For .NET Fx IIS app it will generate anyway unimportant gibberish... either replace it with `iisapp` or fallback completely to template without `addDomainName`. The most important part is the `process.id` anyway.

**Comment by nrcventura** [comment]
Alternatively, you could do something like https://github.com/newrelic/newrelic-dotnet-agent/blob/f8422d6c538db6ff32e0b1055e824b3536245c59/src/NewRelic.Core/Strings.cs#L19-L41 which is an implementation of the character replacement.

The process id may not be enough to differentiate apps that share an app pool, so it might be better to use the invalid character replacement approach so each of the apps that share an app pool can have their own log file.

**Comment by nrcventura** [comment]
Is the code using the app pool name, or the app domain name? I thought that each app in the app pool got its own app domain. My naming comment was based on the assumption that we used the app domain name instead of the app pool name.

**Comment by RassK** [comment]
oops, I mixed app domain and app pool name up. I was actually talking about app domain names.

**Comment by nrcventura** [comment]
The app domain name is not very meaningful, but it is a way for the logging to be directed to separate files. If multiple IIS hosted apps are logging to the same file, we may need something else in our logs to differentiate those apps.

**Comment by RassK** [comment]
SIG: May try to rearrange parts in the file name {otel-auto-prefix}-{pid}-{type}-(all non common parts following).
This helps same context file groups to be next to each other when sorted by name.

Resolves also problem with app domain names, when encoded.

**Comment by nrcventura** [comment]
As I thought about the filename format more, I remember us moving the process id to the end so that logs for the same application would group together. If we move the process id earlier in the name, those logs would not be grouped together anymore.

**Comment by RassK** [comment]
@nrcventura I'm not sure what do you mean. Sort by name while pid is the last part groups together similar file names, not logs from the same process.

without name format fix:
![image](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/assets/4929112/de2d4455-3dc9-4cb1-b87b-2ee23d7fc09b)

**Comment by nrcventura** [comment]
I have been trying to track down the details of the previous log file discussion that I was thinking of, but I have not had much luck finding it using the github search feature. I looked through the github history as best as I could to see if we ever used the file naming convention that is being proposed, but I did not see anything that showed us placing the process id before the app domain information.

A nice side-effect of the naming scheme you are proposing is that it groups the native log and managed logs together.

The downside is that it is harder to see all of the runs across multiple process ids.

Since I can't find or remember the details of the previous discussion, and it does not seem like we are switching back to a previously used naming scheme, I think that we will be ok with the proposal from @RassK.

**Comment by RassK** [comment]
> The downside is that it is harder to see all of the runs across multiple process ids.

May need to add log marker also to the managed log. Just discovered that there is no way to filter only managed logs.
Filtering works for all other types:

```
*-Loader.log
*-Native.log
```

This way you can filter any type and sort by "Date modified" desc for example to bring up active logs / processes.

Grouping should be also very important for bug / support tickets, as these logs should be attached like by default, then it's easier for customer to locate all types.
