### ISSUE TITLE
Cleanup sample applications

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-dotnet-instrumentation#333]
The samples need review and have at least some basic documentation to describe what are they demonstrating.

**Comment by pellared** [comment]
Partially addressed in https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/412

**Comment by pjanotti** [comment]
Another step on this one: #422 

After that renaming the projects per discussion on the SIG: using the prefix "Demo".
