### ISSUE TITLE
Dotnet 7 and 8 auto instrumentation logs not being sent to collector

### ISSUE THREAD

**Issue by jamesoneill** [open-telemetry/opentelemetry-dotnet-instrumentation#3331]
# Bug Report

## Symptom

**Describe the bug**
When using dotnet 7 and 8 auto instrumentation for otel logs don't seem to be being sent. Downgrading to dotnet 6 and all the same environment variables logs are sent
 

**Expected behavior**
Logs are sent correctly viewable and correlated in am observability stack.

**Screenshots**

**Runtime environment (please complete the following information):**

- OpenTelemetry Automatic Instrumentation version: [ 1.4.0]
- OS: [dotnet docker container alpine ]
- .NET version: [dotnet 7 amd 8]

**Additional context**

## Reproduce

 1. Add auto instrumentation at container level
 2. setup logs exporting
 3. see logs dont seem to be sent

<!--
NOTE: If possible, also include the log files found (by default) in:
Windows: %ProgramData%\OpenTelemetry .NET AutoInstrumentation\logs\
Linux and macOS: /var/log/opentelemetry/dotnet/
--!>

**Comment by rajkumar-rangaraj** [comment]
Would you mind enabling detailed logging as per the instructions provided in this [link](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/main/docs/troubleshooting.md#enable-detailed-logging)? Once done, could you please share the resulting output files here?

**Comment by jamesoneill** [comment]
Sure please find logs attached.
[otel-dotnet-auto-ourservicename-1-StartupHook-20240320.log](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/files/14694671/otel-dotnet-auto-ourservicename-1-StartupHook-20240320.log)
[otel-dotnet-auto-native-dotnet-1.log](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/files/14694672/otel-dotnet-auto-native-dotnet-1.log)
[otel-dotnet-auto-ourservicename-1-20240320.log](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/files/14694668/otel-dotnet-auto-ourservicename-1-20240320.log)
[otel-dotnet-auto-ourservicename-1-Loader-20240320.log](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/files/14694670/otel-dotnet-auto-ourservicename-1-Loader-20240320.log)

**Comment by rajkumar-rangaraj** [comment]
Logs are clear, auto-instrumentation wired up as expected. This requires troubleshooting from OpenTelemetry .NET SDK. Please collect self-diagnostics to troubleshoot an issue. Ref: https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry/README.md#self-diagnostics

**Comment by pjanotti** [comment]
SIG: closing since the issue seems related to the SDK, re-opening if appropriate.
