### ISSUE TITLE
End-user documentation

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-dotnet-instrumentation#335]
The following documentation must be provided:
- installation and usage instructions
- troubleshooting (especially the workarounds for assembly version conflicts and missing assemblies, possible telemetry loss)
- supported env (OS and frameworks)
- list of provided instrumentation libraries 
- configuration
- manual instrumentation instructions
- changelog

It would be also good to improve the contributing docs.

**Comment by pellared** [comment]
Current state

| what | state |
| - | - |
| installation and usage instructions | TODO: use "releases" instead of CI artifacts |
| troubleshooting (especially the workarounds for assembly version conflicts and missing assemblies, possible telemetry loss) | ✔️ |
| supported env (OS and frameworks) | ✔️ | 
| list of provided instrumentation libraries | TODO: Reference `config.md#instumented-libraries-and-framework` in `README.md`  |
| configuration | Remove: all references to MongoDB |
| manual instrumentation instructions | TODO: Add instructions to use Actvity API (https://opentelemetry.io/docs/instrumentation/net/manual/#creating-activities), test it
| changelog | Add info about all supported env vars, instrumentation libraries, supported .NET versions |

**Comment by pellared** [comment]
@rajkumar-rangaraj Can you please take a look at [examples/README.md](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/main/examples/README.md). I think that the intention of `AspNetCoreMvc` was also a demo where one instrument the application without using a .NET Profiler. Do I remember correctly? 

@pjanotti FYI

I think it would be worth documenting it in a timely manner, but I would not consider it as a beta release blocker. If both of you agree I will just create a separate issue to track it.

**Comment by pjanotti** [comment]
Re-opening for follow up from PRs.

**Comment by pellared** [comment]
@theletterf is going to make a review of our docs

**Comment by theletterf** [comment]
Interested 🤚🏻
