### ISSUE TITLE
Kafka instrumentation creates span for no messages

### ISSUE THREAD

**Issue by lachmatt** [open-telemetry/opentelemetry-dotnet-instrumentation#3367]
# Bug Report

## Symptom

When `Consume` is called without timeout specified (e.g either with CancellationToken, or with no params), when there are no messages read from a topic, spans will be generated, by default, every 100ms (default value of CancellationDelayMaxMs from ConsumerConfig).
This results in great number of spans generated.

## Affected versions of autoinstrumentation

v1.3.0, v1.4.0, v1.5.0

## Workaround

Disable kafka client instrumentation e.g by setting `OTEL_DOTNET_AUTO_TRACES_KAFKA_INSTRUMENTATION_ENABLED` to `false`

[Fix](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/3363) merged and targeted for next release [v1.5.1](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/milestone/22).

**Comment by pellared** [comment]
Fixed by https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/3363
