### ISSUE TITLE
Improve interaction with strongly named assemblies

### ISSUE THREAD

**Issue by nrcventura** [open-telemetry/opentelemetry-dotnet-instrumentation#342]
Some of our .NET framework tests are failing to run locally because of strongly named assemblies requiring other assemblies to be strongly named. We should revisit our assumption about not needing to strongly name the assemblies in this project, or fix the regression in how we're loading the managed assemblies.

Sample error message from a test:
```
[webserver][stdout] fail: GraphQL.Server.Transports.AspNetCore.GraphQLHttpMiddleware[0]
[webserver][stdout]       GraphQL execution error(s): GraphQL.ExecutionError: Could not load file or assembly 'OpenTelemetry.ClrProfiler.Managed, Version=0.0.1.0, Culture=neutral, PublicKeyToken=34b8972644a12429' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044) ---> System.IO.FileLoadException: Could not load file or assembly 'OpenTelemetry.ClrProfiler.Managed, Version=0.0.1.0, Culture=neutral, PublicKeyToken=34b8972644a12429' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044) ---> System.IO.FileLoadException: A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)
[webserver][stdout]          --- End of inner exception stack trace ---
[webserver][stdout]          at GraphQL.Validation.DocumentValidator.Validate(String originalQuery, ISchema schema, Document document, IEnumerable`1 rules, Object userContext, Inputs inputs)
[webserver][stdout]          at GraphQL.DocumentExecuter.<ExecuteAsync>d__8.MoveNext()
[webserver][stdout]          --- End of inner exception stack trace ---
```

**Comment by pjanotti** [comment]
Original PR that removed strong name for reference: https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/205

@nrcventura it should not require strong name with the `PublicToken` is omitted from https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/89795dfa54b9b818b84018ec3c45abbed7a48c73/src/OpenTelemetry.ClrProfiler.Native/dd_profiler_constants.h#L80

**Comment by nrcventura** [comment]
That's good to know. I'm ok with us removing the PublicToken to get things working sooner. I'm going to update the description and title to reflect this possibility.

**Comment by nrcventura** [comment]
@pjanotti It looks like that one update is all that it takes to get the tests passing again, so for simplicity my preference is to just make that change and not reintroduce strong naming (unless something else causes us to reconsider it in the future).

**Comment by pjanotti** [comment]
I agree with that ^
