### ISSUE TITLE
Allow customization of the StartupHook dll

### ISSUE THREAD

**Issue by pjanotti** [open-telemetry/opentelemetry-dotnet-instrumentation#346]
This is more to facilitate development and experimentation and perhaps an extension point for vendors. See https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/314#discussion_r798054857 for the context.

The profiler code currently assumes that the StartupHook has a particular name, and is located in a specific installation directory. We might want to break some of these assumptions to support different experiments and vendor extension points. Perhaps there's an additional experimental startup hook, or perhaps a vendor wants to use their own startup hook.

**Comment by pellared** [comment]
**SIG meeting**

@nrcventura to describe it better
post-beta

**Comment by Kielek** [comment]
Not needed by 2+years. Closing. Feel free to reopen when needed.
