### ISSUE TITLE
Proposal: Renaming assemblies and related packages

### ISSUE THREAD

**Issue by nrcventura** [open-telemetry/opentelemetry-dotnet-instrumentation#349]
This issue is in response to the questions in https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/314#discussion_r797531853.

We need to come up with names for our assemblies (and ultimately the corresponding the packages) that are consistent with both the OTel .NET SDK and the .NET community, and are reasonably short so as to play nicer with path size limits in Windows. As part of that consistency we should not prefix our current assemblies with `OpenTelemetry.Instrumentation`.

The current set of assemblies to consider when thinking of this naming strategy include:
- OpenTelemetry.ClrProfiler.Managed.Core
- OpenTelemetry.ClrProfiler.Managed.Loader
- OpenTelemetry.ClrProfiler.Managed
- OpenTelemetry.ClrProfiler.Native
- OpenTelemetry.Instrumentation.StartupHook

Here are some ideas to get the discussion started:

1. Use the `OpenTelemetry.AutoInstrumentation` prefix for assemblies. This would give us names that look like:
   - OpenTelemetry.AutoInstrumentation.Core
   - OpenTelemetry.AutoInstrumentation.Loader
   - OpenTelemetry.AutoInstrumentation
   - OpenTelemetry.AutoInstrumentation.Native
   - OpenTelemetry.AutoInstrumentation.StartupHook

2. Use the `OpenTelemetry.NoCode` prefix for assemblies. This would give us names that look like:
   - OpenTelemetry.NoCode.Core
   - OpenTelemetry.NoCode.Loader
   - OpenTelemetry.NoCode
   - OpenTelemetry.NoCode.Native
   - OpenTelemetry.NoCode.StartupHook
 
3. Use the `OpenTelemetry.Auto` prefix.
   - OpenTelemetry.Auto.Core
   - OpenTelemetry.Auto.Loader
   - OpenTelemetry.Auto
   - OpenTelemetry.Auto.Native
   - OpenTelemetry.Auto.StartupHook

Other things to consider when naming the Startup Hook assembly. Should it be considered as an OpenTelemetry extension and use the `OpenTelemetry.Extensions` prefix? Should it be simply `OpenTelemetry.StartupHook`?

I also think that the `Managed` distinction in the original assembly names are not adding extra value to the project, so the example names I listed above dropped that part of the assembly name.

***My current recommendation is to go with approach 1.*** I also think that ***the Startup Hook should use the same naming convention as the other assemblies***, because that assembly is coupled to the loader assembly in this project. If we break that coupling, and the startup hook can be used outside of this project, then we should follow one of the other suggested naming conventions. I do not see any value in providing a NuGet package for any of these assemblies in isolation. As a result we could have a single NuGet package with the name `OpenTelemetry.AutoInstrumentation`.

Approach 2 is even shorter, but I don't think it accurately represents all use cases of this project (there will still be cases where code or build changes need to be made).

**Comment by pjanotti** [comment]
While `OpenTelemetry.AutoInstrumentation` is a bit on the longer side it makes clear the purpose. The removal of `Managed` helps reducing the size a bit. I had originally favored `Auto` but seeing the alternatives above I think `AutoInstrumentation` is better since `Auto` can be seem as ambiguous.

**Comment by rajkumar-rangaraj** [comment]
`OpenTelemetry.AutoInstrumentation` well aligns.

**Comment by zacharycmontoya** [comment]
`OpenTelemetry.AutoInstrumentation` 👍🏼
