### ISSUE TITLE
[test] Revert #3520: workaround for `dotnet CLI build-server` shutdown issue 

### ISSUE THREAD

**Issue by pjanotti** [open-telemetry/opentelemetry-dotnet-instrumentation#3522]
We should revert #3520 when we have runners with https://github.com/dotnet/roslyn/pull/74436 fixed. I rather be alerted of such issues and quickly re-instate the workaround if needed than let these type of issues go silent.

**Comment by Kielek** [comment]
Checked on CI - not possible at this moment. Moving to 1.9.0. I suppose that it will be possible when we instal .NET9 SDK (November).
