### ISSUE TITLE
Enhanced Handling of Comma-Separated Lists

### ISSUE THREAD

**Issue by ysolomchenko** [open-telemetry/opentelemetry-dotnet-instrumentation#3534]
# Feature Request Enhanced Handling of Comma-Separated Lists

**Is your feature request related to a problem? Please describe.**
Currently, when handling comma-separated lists, the system does not trim spaces and allows duplicate entries. This can lead to confusion and inefficiencies. For instance, now the input should only be “otlp,zipkin”, which is not ideal.

**Describe the solution you'd like**

The system should:

- Trim trailing spaces around list elements.
- Remove duplicate entries.
- log a warning when duplicates are found.
- log a warning when an empty element is detected due to trailing commas or consecutive commas.

**Comment by Kielek** [comment]
@ysolomchenko,
specification is pretty strict, we should support only comma-separated values. On the other hand, we should not fail if the fail fast is not enabled.

| desctiption| input example |Fail Fast disabled | fail fast enabled |
|-|-|-|-|
|Spaces around list elements.|`otlp, console`|Log warning, that the value ` console is not supported`, only OTLP protocol is used | Log warning + crash application|
|Duplicated entries.|`otlp,console,otlp`|Log warning about duplicated entries|Log warning about duplicated entries, Crash applcation|
|Empty element|`otlp, ,console`|Treat it as any non-supported exporter. Warn log only| Same as fail fast disabled + crash application |

Please let me know if it makes sense to you.

**Comment by ysolomchenko** [comment]
> @ysolomchenko, specification is pretty strict, we should support only comma-separated values. On the other hand, we should not fail if the fail fast is not enabled.
> 
> desctiption	input example	Fail Fast disabled	fail fast enabled
> Spaces around list elements.	`otlp, console`	Log warning, that the value ` console is not supported`, only OTLP protocol is used	Log warning + crash application
> Duplicated entries.	`otlp,console,otlp`	Log warning about duplicated entries	Log warning about duplicated entries, Crash applcation
> Empty element	`otlp, ,console`	Treat it as any non-supported exporter. Warn log only	Same as fail fast disabled + crash application
> Please let me know if it makes sense to you.

What about the duplicated entries? Should we remove them and log a warning about duplicated entries, crash the application (fail fast), or keep the duplicates?
And what should we do with OTEL_DOTNET_AUTO_[SIGNAL]_CONSOLE_EXPORTER_ENABLED if it is enabled and present in the list?

**Comment by pellared** [comment]
> What about the duplicated entries?

My proposal:

Fail Fast disabled: Remove them and log a warning about duplicated entries
Fail Fast enabled: crash the application

**Comment by Kielek** [comment]
Table updated.

**Comment by Kielek** [comment]
I would allow to have both `OTEL_DOTNET_AUTO_[SIGNAL]_CONSOLE_EXPORTER_ENABLED` without any issue, but log warning is also fine. It will be gone away in the 1.9.0 probably.
