### ISSUE TITLE
Console Logger for internal diagnostic logs

### ISSUE THREAD

**Issue by RassK** [open-telemetry/opentelemetry-dotnet-instrumentation#3552]
### What

I'm thinking to add switch that passes diagnostic logs also to console (currently there is only a file output).
This should simplify diagnostic logging for containerized apps, like k8s pods.

Any opinions on this?

**Comment by nrcventura** [comment]
I think this is a good idea, we'll need to be careful with default logging levels, to ensure that it doesn't affect performance too much.

**Comment by Mpdreamz** [comment]
👍 we do something similar in the Elastic distribution

https://github.com/elastic/elastic-otel-dotnet/pull/129

We switch this on if we detect `DOTNET_RUNNING_IN_CONTAINER` and `OTEL_LOG_LEVEL` is `debug`.

**Comment by RassK** [comment]
SIG: Let's try to keep it simple and without magic. 
1. Leave the default to log to file
2. In case of failure, use Noop sink
3. User can explicitly set sink to file, console, noop (none).
