### ISSUE TITLE
.NET SDK consistency check

### ISSUE THREAD

**Issue by Kielek** [open-telemetry/opentelemetry-dotnet-instrumentation#3595]
As a maintainer I would like to have .NET SDK consistency check between docker files and pipeline definitions.

The goal is to prevent merges such as #3573 and #3577 without updating pipeline definitions #3588

The check should cover
 - `actions/setup-dotnet` - dotnet versions in yml files
 - Docker base images
 - dotnet versions installed by dotnet-install.sh

**Comment by Kielek** [comment]
@pjanotti, FYI

**Comment by Kielek** [comment]
While working on this, you can consider creating automatic script to update all versions based on https://dotnet.microsoft.com/en-us/download/dotnet

**Comment by pjanotti** [comment]
Thanks @Kielek!
