### ISSUE TITLE
OpenTelemetry.AutoInstrumentation 1.7.0 NuGet | Fatal Error System.AccessViolationException + Missing DLL's referenced in instrument.cmd and instrument.sh scripts

### ISSUE THREAD

**Issue by 3mv3** [open-telemetry/opentelemetry-dotnet-instrumentation#3596]
# Bug Report
Fatal error thrown when trying to launch application using instrument.cmd or instrument.sh

## Symptom

**Describe the bug**
Following the NuGet [installation steps](https://www.nuget.org/packages/OpenTelemetry.AutoInstrumentation/#readme-body-tab) and running

> `./instrument.cmd dotnet run --project ../../../webapplication1.csproj`

results in the following error

> `Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
Repeat 2 times:
   at OpenTelemetry.AutoInstrumentation.NativeMethods+Windows.AddInstrumentations(System.String, OpenTelemetry.AutoInstrumentation.NativeCallTargetDefinition[], Int32)
   at OpenTelemetry.AutoInstrumentation.NativeMethods.AddInstrumentations(System.String, OpenTelemetry.AutoInstrumentation.NativeCallTargetDefinition[])
   at OpenTelemetry.AutoInstrumentation.Instrumentation.RegisterBytecodeInstrumentations(Payload)
   at OpenTelemetry.AutoInstrumentation.Instrumentation.Initialize()
   at System.RuntimeMethodHandle.InvokeMethod(System.Object, Void**, System.Signature, Boolean)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(System.Object, System.Reflection.BindingFlags)
   at System.Reflection.MethodBase.Invoke(System.Object, System.Object[])
   at OpenTelemetry.AutoInstrumentation.Loader.Loader.TryLoadManagedAssembly()
   at OpenTelemetry.AutoInstrumentation.Loader.Loader..cctor()
   at OpenTelemetry.AutoInstrumentation.Loader.Loader..ctor()
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean, Boolean)
   at System.RuntimeType.CreateInstanceImpl(System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo)
   at System.Reflection.Assembly.CreateInstance(System.String)
   at StartupHook.Initialize()
   at System.RuntimeMethodHandle.InvokeMethod(System.Object, Void**, System.Signature, Boolean)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(System.Object, System.Reflection.BindingFlags)
   at System.StartupHookProvider.CallStartupHook(StartupHookNameOrPath)
   at System.StartupHookProvider.ProcessStartupHooks(System.String)`

**Expected behavior**
The application should launch with automatic instrumentation working.

**Screenshots**

**Runtime environment (please complete the following information):**

- OpenTelemetry Automatic Instrumentation version: 1.7.0
- OS: Microsoft Windows 10 Pro
- .NET version: .NET 8

**Additional context**
I also noticed that the install scripts reference DLL's that don't appear to be installed as transitive dependencies 
![image](https://github.com/user-attachments/assets/7d47b16c-01b2-4024-94fd-04bd00079f7b)
![image](https://github.com/user-attachments/assets/f405ec2e-eb4a-41fa-a476-48acb484a01b)

I can see that `OpenTelemtry.AutoInstrumentation.Runtime.Native` _is_ installed as a transitive dependency, but the DLL never gets compiled, and even if it did, the path names would be incorrect.

I can also see the DLL is logged as missing in the autoinstrumentation logs
![image](https://github.com/user-attachments/assets/560776cd-9374-4efb-90d6-25343cfd98de)

## Reproduce

Steps to reproduce the behaviour:

 1. First step; Create a new ASP.NET core web application bootstrapped with .NET 8 and OpenAPI 
 2. Second step; Install the OpenTelemetry.AutoInstrumentation NuGet package
 3. Third step: Run the command `./instrument.cmd dotnet run --project ../../../webapplication1.csproj` and 💥 

<!--
NOTE: If possible, also include the log files found (by default) in:
Windows: %ProgramData%\OpenTelemetry .NET AutoInstrumentation\logs\
Linux and macOS: /var/log/opentelemetry/dotnet/
--!>
[logs.zip](https://github.com/user-attachments/files/16799809/logs.zip)

**Comment by lachmatt** [comment]
Related to #3567

**Comment by 3mv3** [comment]
> Related to #3567

@lachmatt do you want me to close this one and follow all updates on the original bug?

**Comment by Kielek** [comment]
@3mv3, 

I think that you are messing 2 things. Building process with instrumentation: `.\instrument.cmd dotnet run --project ../../../webapplication1.csproj -r win-x64`

The expected solution is

1. Execute build: `dotnet build --project ../../../webapplication1.csproj -r win-x64`
2. Execute your instrumented application `.\instrument.cmd your-application`

Please let me know if it helps.

**Comment by 3mv3** [comment]
@Kielek Thanks for the response. I tried those steps and got the same results:
![image](https://github.com/user-attachments/assets/5d422b32-994b-4287-a6f1-b53911db9409)

**Comment by Kielek** [comment]
@3mv3, please provide [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example). Without this, it can be hard to advice. It can be separate GH repository where we can find the code and all steps to follow/execute.

**Comment by 3mv3** [comment]
@Kielek @lachmatt I was getting throw off by this line in the docs
> Use the script in the output folder of the build to launch the application with automatic instrumentation activated.

As I understand it, the default 'output' folder of a build is `./bin/<configuration>/<framework>/`, and given that I could see the instrument scripts there, I assumed they were the correct ones:
![image](https://github.com/user-attachments/assets/ba150e5a-c77b-4a97-8d9d-b1d8a5904508)

I now understand you mean the output folder for the specific RID used to initiate the build, the path to which would be `./bin/<configuration>/<framework>/<rid>/`
![image](https://github.com/user-attachments/assets/a3dfc067-100f-4a5a-b202-14fb3cbd8b1b)

Another thing I noticed is, even without specifying a RID during a build, the native DLL's are compiled regardless and placed in a `runtimes` folder in the output directory:
![image](https://github.com/user-attachments/assets/31944be3-6bac-47f7-86fb-c28fb04cd6d1)

That allowed me to build 'as normal' in Visual Studio, and use launchSettings to configure the environment variables, negating the need to launch each time with the instrument scripts:
![image](https://github.com/user-attachments/assets/d990840b-4766-4ca2-89e9-244152965fc4)

**Comment by lachmatt** [comment]
@3mv3 

> I now understand you mean the output folder for the specific RID used to initiate the build, the path to which would be `./bin/<configuration>/<framework>/<rid>/`

**Comment by lachmatt** [comment]
I'm closing the issue as underlying problem was addressed, @3mv3 feel free to reopen if you disagree.
