### ISSUE TITLE
Releasing 1.8.0

### ISSUE THREAD

**Issue by noamApps** [open-telemetry/opentelemetry-dotnet-instrumentation#3624]
# Feature Request

Would like to ask if its possible to release 1.7.X to unblock the support per signal overrides

**Is your feature request related to a problem? Please describe.**
Currently, 1.7.0  doesn't support overriding the OTEL_EXPORTER_OTLP_ENDPOINT per signal.
For example, metrics url re-wiring is something that is relatively popular as there are multiple metrics ingestion projects that accepts the open telemetry protocol , and wiring to directly to them simplify infrastructure and eases adoption a lot.

Also its part of the Opentelemetry spec, and people that already adopted open telemetry in the past might find this discrepancy highly confusing and time consuming (its not documented as lacking in the dotnet auto instrumentation anywhere other than the unreleased Changelog here that implies it)

And lastly, no log to communicate this isn't supported whatsoever, and no log on getting 404/error from the unavailable global endpoint.

**Describe the solution you'd like**
patch release 1.7.X to unblock this feature

**Describe alternatives you've considered**
no clear alternatives for people requiring that change in the source (e.g not in Otel collector)

If this is not possible, it will be great to have some rough ETA on when 1.8.0 is expected if possible

Thanks 🙏

**Comment by Kielek** [comment]
As it is a feature , it better fits to normal release. Patch is dedicated to bugfixes.
You can expect it is a release 1.8.0 with all other things listed under https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/b48a9e8fa7e0586ce27576500f25a1506c104c71/CHANGELOG.md#unreleased

We will disucss potentiall release date in the next SIG meeting (Wednesday).

**Comment by Kielek** [comment]
@noamApps, very tentative release date is end of September.
