### ISSUE TITLE
Bump DotNet.ReproducibleBuilds to 1.2.25+

### ISSUE THREAD

**Issue by Kielek** [open-telemetry/opentelemetry-dotnet-instrumentation#3636]
>  It is not the best option to upgrade it now. It is better option to wait and make upgrade when we drop .net6 and .net7 support.
This package is designed to fully work with .NET8 SDK+.

_Originally posted by @Kielek in https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/issues/3632#issuecomment-2345290386_

**Comment by pjanotti** [comment]
SIG: on hold until we drop .NET 6.
