### ISSUE TITLE
Update LICENSE-3rdparty

### ISSUE THREAD

**Issue by Kielek** [open-telemetry/opentelemetry-dotnet-instrumentation#365]
Update LICENSE-3rdparty. For now, it contains references to Datadog. Probably part of the records is also unused (or missing).

https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/1c1ef96b8bc907f3d2507cd7c9c538013c80db19/LICENSE-3rdparty.csv

**Comment by pellared** [comment]
**SIG meeting notes**

NOTICE file should also be updated.

**Comment by pellared** [comment]
According to https://github.com/open-telemetry/community/blob/main/CONTRIBUTING.md#copyright-notices

1. We MUST be sure to have original copyright notice where applicable (e.g. vendored code)
2. We can remove `LICENSE-3rdparty.csv`.

**Comment by mtwo** [comment]
I'm not an expert on licensing issues, so I brought up these questions with the governance committee.

Given that we use an Apache 2 license, we shouldn't need to re-list the licenses of code that we reference, as long as they are also using licenses that are Apache 2 compatible (which MIT and Apache 2 are), as the fact that we're under a compatible license means that it's effectively redistributed / re-posted. You may delete the file if you wish, or you may continue to maintain it, but you're not obligated to keep it.

As an aside, we're going to take an action as a project to regularly run a license check tool across all SIGs, to ensure that we're only referencing projects with compatible licenses. However I don't know of any examples where we've referenced something with an incompatible license.

**Comment by Kielek** [comment]
One more comment from Liz from the governance committee.

https://infra.apache.org/licensing-howto.html#permissive-deps basically encapsulates the ASF guidance

which I believe says that you do not need a separate NOTICE if your deps have their own NOTICE

The NOTICE file is reserved for a certain subset of legally required notifications which are not satisfied by either the text of LICENSE or the presence of licensing information embedded within the bundled dependency. Aside from Apache-licensed dependencies which supply NOTICE files of their own, it is uncommon for a dependency to require additions to NOTICE.
