### ISSUE TITLE
Remove .NET Framework 4.6.1 support

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-dotnet-instrumentation#376]
https://devblogs.microsoft.com/dotnet/net-framework-4-5-2-4-6-4-6-1-will-reach-end-of-support-on-april-26-2022/

_Originally posted by @Kielek in https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/issues/375#issuecomment-1046641141_

**Comment by nrcventura** [comment]
I think that it makes sense to replace 4.6.1 with 4.6.2 as the minimum supported framework version.

**Comment by pellared** [comment]
**SIG notes**

We can also switch to the `windows-2022` runner.
