### ISSUE TITLE
Execute integration tests for .NET 4.6.2 in CI pipeline

### ISSUE THREAD

**Issue by Kielek** [open-telemetry/opentelemetry-dotnet-instrumentation#378]
#377 follow up.

Our pipeline executes only integration tests for .NET (Core). We should execute it also for .NET Framework 4.6.2.

Issue occurring while executing all tests:
```
  Error: [xUnit.net 00:01:19.62]     IntegrationTests.MongoDB.MongoDbTests.SubmitsTraces [FAIL]
  13:01:34 [ERR] [xUnit.net 00:01:19.62]     IntegrationTests.MongoDB.MongoDbTests.SubmitsTraces [FAIL]
  13:01:34 [DBG]   Failed IntegrationTests.MongoDB.MongoDbTests.SubmitsTraces [1 ms]
  13:01:34 [DBG]   Error Message:
  13:01:34 [DBG]    System.AggregateException : One or more errors occurred. (One or more errors occurred. (The operation has timed out.)) (One or more errors occurred. (The operation has timed out.)) (The following constructor parameters did not have matching fixture data: MongoDbFixture mongoDb)
  13:01:34 [DBG] ---- System.AggregateException : One or more errors occurred. (The operation has timed out.)
  13:01:34 [DBG] -------- System.TimeoutException : The operation has timed out.
  13:01:34 [DBG] ---- System.AggregateException : One or more errors occurred. (The operation has timed out.)
  13:01:34 [DBG] -------- System.TimeoutException : The operation has timed out.
  13:01:34 [DBG] ---- The following constructor parameters did not have matching fixture data: MongoDbFixture mongoDb
  13:01:34 [DBG]   Stack Trace:
```

It is probably related to the taking port number for MongoDB https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/main/test/integration-tests/IntegrationTests.MongoDB/MongoDbCollection.cs#L27 or trying to start container https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/main/test/integration-tests/IntegrationTests.MongoDB/MongoDbCollection.cs#L78 in contructor

**Comment by pellared** [comment]
I think we could also refactor the build pipeline to execute the tests on the given framework in parallel. Example: https://github.com/signalfx/signalfx-dotnet-tracing/blob/7a668c48d40a1acd11764f0c59edcf610b24b10e/.github/workflows/ci.yml#L297

**Comment by pellared** [comment]
Done in https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/574
