### ISSUE TITLE
Verrify `TypeAttributes.Serializable` in DuckTyping

### ISSUE THREAD

**Issue by Kielek** [open-telemetry/opentelemetry-dotnet-instrumentation#3799]
> The usage of `TypeAttributes.Serializable` seems to have been used since its introduction into the Datadog automatic instrumentation. I've messaged my colleagues to understand if it's truly needed, and if it is then we'll need to suppress this compiler warning. Or perhaps if it's not needed for newer runtimes we can ifdef its usage, but I don't know if that's the case

_Originally posted by @zacharycmontoya in https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/3796#discussion_r1851105285_

It can be done after merge, it was working fine on .NET8 with .NET6 binaries for a while. No rush to changes.

**Comment by zacharycmontoya** [comment]
I asked around with some colleagues at Datadog and the consensus is that there is risk in removing the attribute, but there's no clear scenario where the error could occur. To be safe, the recommendation is to keep applying the Serializable attribute on the generated types (keeping the code as-is).
