### ISSUE TITLE
Changelog for 1.10.0

### ISSUE THREAD

**Issue by KasperHoldum** [open-telemetry/opentelemetry-dotnet-instrumentation#3821]
It seems like 1.10.0 was released without any changelogs which makes it hard to upgrade into. 

Any chance you can publish the missing change logs?

**Comment by KasperHoldum** [comment]
Ohh yeah, might be

**Comment by Kielek** [comment]
@KasperHoldum, feel free to create issue/PR with expected fixes. I will be happy to review any of OTel .NET repositories.
