### ISSUE TITLE
[Proposal] Add `Containers` Nuke parameter

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-dotnet-instrumentation#389]
Currently, it is not possible to run the tests using Linux containers on Windows using Nuke.

I propose introducing an enum parameter `Containers` with possible values `None`, `Linux`, `Windows` which would be used to control the test run filter. Setting `Linux` as the default value should make local development easier.

I also consider changing the traits in the following way:

```csharp
    [Trait("LinuxContainers", "true")] // the test uses Linux containers
    [Trait("WindowsContainers", "true")] // the test uses Windows containers
```

Maybe we could also refactor it and introduce new attributes like:
- `LinuxContainersTraitAttribute`
- `WindowsContainersTraitAttribute`

**Comment by nrcventura** [comment]
Can you explain a little more about how these traits can help us with running the tests locally? We'll have a mix of tests that use different container types (Linux or Windows). Are you thinking that the test runner will check to see which OS is configured for docker currently, and then filter the test cases appropriately?

**Comment by pellared** [comment]
_Writting from mobile_

Currently tests using Windows container have 

```
    [Trait("WindowsOnly", "true")]
```

And the Nuke target filters out these tests if the OS is not Windows.

I also think that these are the only integration tests run on Windows (but I may be wrong). 


I find the current test build/filter/run setup too complex. I want to try to make it a little more clear and robust at the same time.

**Comment by nrcventura** [comment]
Another piece of complexity to consider with the solution is that the CI pipeline will likely only be able to run windows containers when running the windows pipeline.

**Comment by pellared** [comment]
True. The windows job(s) will simply explicitly set the parameter.

**Comment by nrcventura** [comment]
I think that it would be great if we could run more of the tests on Windows, even if that means we need to run a separate command locally than we run in the CI pipeline. I just want us to also be able to run the same command that we use in the CI pipeline to make it easier for us to reproduce problems or to have more confidence in a change before submitting a PR.
