### ISSUE TITLE
MongoDB Instrumentation keeps generating spans on the background

### ISSUE THREAD

**Issue by pjanotti** [open-telemetry/opentelemetry-dotnet-instrumentation#411]
**Description**
The MongoDB Instrumentation keeps generating spans triggered by the driver that are not related to any transaction or client call. This seems a regression of https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/207

1. Run the Samples.AspNetCoreMvc31 and let it running in the background
2. Check the spans being generated (see image above)

**Expected behavior**
Only spans directed related to the client app requests.

**Screenshots**
![image](https://user-images.githubusercontent.com/5600755/158480502-a10c9f62-a4af-4c52-9de9-33386f990c3f.png)

**Comment by pellared** [comment]
We should consider using https://www.nuget.org/packages/MongoDB.Driver.Core.Extensions.OpenTelemetry/ instead
