### ISSUE TITLE
Review recommendations for `DOTNET_ADDITIONAL_DEPS` usage

### ISSUE THREAD

**Issue by pjanotti** [open-telemetry/opentelemetry-dotnet-instrumentation#417]
While reviewing the samples it became clear that the recommendations for `DOTNET_ADDITIONAL_DEPS` need to be reviewed. Context: https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/412/files#r829101344

**Comment by pjanotti** [comment]
It seems that the additional deps were broken on non-Windows, see https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/422/commits/da90c9acdcb7147c3932fe5377d918d815246596 on PR #420 

Likely, we don't need to change anything regarding the recommendations for additional deps, anyway, I want to review them before closing this issue.

**Comment by pellared** [comment]
@pjanotti PR #422, right?

**Comment by pjanotti** [comment]
yes, correct @pellared - editing previous comment
