### ISSUE TITLE
Allow for OTel span data model without code divergence from Datadog

### ISSUE THREAD

**Issue by macrogreg** [open-telemetry/opentelemetry-dotnet-instrumentation#42]
Hey folks,

Based on the discussion in the meetings, I want to make a concrete proposal.
Please treat it as the first stub; we can modify it in any way we want. I just want to help moving the discussion from theoretical to practical, so that we can move forward. :)

Challenge: 
The OTel tracer must ensure that span tags use OTel conventions for both, tag-names and tag-content-format. For OTel it's a must-have, for Datadog it is optional. The OTel currently depends on Datadog's contributions. Until this changes we need to make code internations easy. This is a proposal on how we can achieve this.

Requirements:
- OTel data model conventions must be met.
- Code bases must not diverge as a result of this particular effort. This implies that:
   - Changes to the OTel Tracer repo must be merged into the Datadog repo.
   - Datadog will only do it, if it has zero performance impact and low complexity effort.

The following solution applies only to new-style CallTarget instrumentations, and to `DiagnosticSource`-based instrumentations. We will not modify older CallSite instrumentations.
We will delegate the logic of setting tags on spans to a tag-creator/span-initializer class, which will be a singleton _per instrumentation_.  The logic of extracting data from the instrumented code will be shared, only the tag configuration will be delegated. 

Consider the [`HttpClient` instrumentation as an example](https://github.com/DataDog/dd-trace-dotnet/blob/488ccfbb1e2a70dba921676b74fbd7f7ea4daed6/src/Datadog.Trace.ClrProfiler.Managed/AutoInstrumentation/HttpClientHandler/HttpClientHandlerIntegration.cs#L36). The meat of the logic is [here](https://github.com/DataDog/dd-trace-dotnet/blob/488ccfbb1e2a70dba921676b74fbd7f7ea4daed6/src/Datadog.Trace.ClrProfiler.Managed/AutoInstrumentation/SocketsHttpHandler/SocketsHttpHandlerCommon.cs#L17).

Note the line
```cs
Scope scope = ScopeFactory.CreateOutboundHttpScope(Tracer.Instance, requestMessage.Method.Method, requestMessage.RequestUri, IntegrationId, out HttpTags tags);
```
It does 2 things: (1) Create a span and (2) set tags on that span. We want to separate these 2 concerns as follows:

I. Create an instrumentation-specific iface:

```cs
interface ISpanInitializerForSocketsHttpHandler
{
    void InitializeSpan(Span span, string httpMethod, Uri requestUri, IntegrationInfo integrationId);
}
```

Here, `span` is the span object that will be emitted, and `httpMethod`, `requestUri`, etc is all the data that we extracted from the instrumented API that is relevant for the span. If we wanted more (e.g. request headers), we would add a corresponding parameter.

II. Now the [driver class](https://github.com/DataDog/dd-trace-dotnet/blob/488ccfbb1e2a70dba921676b74fbd7f7ea4daed6/src/Datadog.Trace.ClrProfiler.Managed/AutoInstrumentation/SocketsHttpHandler/SocketsHttpHandlerCommon.cs#L11) will get a singleton like this:

```cs
internal class SocketsHttpHandlerCommon
{
    ...
    ISpanInitializerForSocketsHttpHandler s_spanInitializer = SpanInitializerForSocketsHttpHandler_VendorName();
    ...
}
```

That one line will be different for each vendor, e.g.:
```cs
    ISpanInitializerForSocketsHttpHandler s_spanInitializer = SpanInitializerForSocketsHttpHandler_NewRelic();
    ISpanInitializerForSocketsHttpHandler s_spanInitializer = SpanInitializerForSocketsHttpHandler_Splunk();
```

Specifically, in the OTel repo it will be
```cs
    ISpanInitializerForSocketsHttpHandler s_spanInitializer = SpanInitializerForSocketsHttpHandler_OTel();
```
and in the Datadog repo it will be
```cs
    ISpanInitializerForSocketsHttpHandler s_spanInitializer = SpanInitializerForSocketsHttpHandler_Datadog();
```

III. Then, the above-mentioned [lines that calls the `ScopeFactory`](https://github.com/DataDog/dd-trace-dotnet/blob/488ccfbb1e2a70dba921676b74fbd7f7ea4daed6/src/Datadog.Trace.ClrProfiler.Managed/AutoInstrumentation/SocketsHttpHandler/SocketsHttpHandlerCommon.cs#L22-L31) would need to be refactored into something like:

```cs
Scope scope = tracer.StartActive(..);
if (scope != null)
{
    s_spanInitializer.InitializeSpan(scope.Span, requestMessage.Method.Method, requestMessage.RequestUri, IntegrationId);
    return new CallTargetState(scope);
}
else
{
    return CallTargetState.GetDefault();
}
```

Some minor refactoring to the Tracer / Scope classes will be required to allow setting all tags, operation name, etc _after_ creation (most of it is possible already).

Each vendor will supply its own `SpanInitializerForSocketsHttpHandler_Xxx` class. Initially, they can all live in all repos in each respective instrumentation folder. Long term, we may or may not require them to live in vendor-specific repositories.

Notably, it is important that the responsibility of the
    SpanInitializerFor**InstrumentationName**_**VendorName**.InitializeSpan(Span span, ...)
method is to completely initialize the Span with the intercepted data from the instrumented code and from the environment. Nothing else.

This will ensure that we can continue using the same code base while allowing for span data-model customization.

Because the customization is, essentially, compile-time, a similar mechanism, can be used for exporter. So the Datadog exporters will expect Datadog tags on Spans, the OTel exporter will expect OTel tags, and each vendor can decide what they want to use when building the product.

### Q & A

**Who will do the work?**

1. OTel team will review this proposal an validates that it meets our goals. 
2. Datadog tracer team will review the proposal and agree (after potential modifications, if required).
3. OTel team will do the work for one instrumentation. This will include any required refactoring to `Tracer` etc, if any. Datadog will code-review.
4. We will push into OTel master branch, then integrate into Datadog repo.
5. OTel team will do the work for all other instrumentation. Datadog will code-review.
6. We will push into OTel master branch, then integrate into Datadog repo.

(Of course, 5 & 6 can happen in batches, we do not need to do all at once. The point is to do one instrumentation, get it in all the necessary places, and only then proceed to the rest).

**What if for some particular existing instrumentation, the OTel data model requires some data currently not collected by that instrumentation?**

In all likelihood this is "useful data". We will modify the instrumentation (non-vendor-specific code) to collect the additional info and include it into both, Datadog and OTel tags.

There may be some exceptions to this, e.g. when collecting some info is very expensive and the existing instrumentation does not need it. In that case we have two options:
- There are good reasons not to collect that data and OTel will skip it.
- That one particular instrumentation will not be compatible and the code for it (and only for it) will diverge. I expect that very few, if any, instrumentations will be in this bucket.

**What about existing `DiagnosticSource`-based telemetry integrations?**

We will use the same `InitializeSpan(..)`-style pattern there.

**Comment by nrcventura** [comment]
This abstraction can work, assuming that the interface requires passing in all of the data needed for all of the semantic conventions. The downside is that there might be cases where either the OTel or Datadog conventions require less data than is extracted and passed to the span initializer so more work is done than is necessary. But this approach can be good enough for now.

**Comment by macrogreg** [comment]
> This abstraction can work, assuming that the interface requires passing in all of the data needed for all of the semantic conventions. The downside is that there might be cases where either the OTel or Datadog conventions require less data than is extracted and passed to the span initializer so more work is done than is necessary.

@nrcventura, good point! A suggestion on how to deal with such cases is in the Q&A sub-section "_What if for some particular existing instrumentation, the OTel data model requires some data currently not collected by that instrumentation?_"

**Comment by nrcventura** [comment]
> > This abstraction can work, assuming that the interface requires passing in all of the data needed for all of the semantic conventions. The downside is that there might be cases where either the OTel or Datadog conventions require less data than is extracted and passed to the span initializer so more work is done than is necessary.
> 
> @nrcventura, good point! A suggestion on how to deal with such cases is in the Q&A sub-section "_What if for some particular existing instrumentation, the OTel data model requires some data currently not collected by that instrumentation?_" What do you think of it?

I think that those are appropriate options if we run into those issues. We'll probably understand each situation better as we encounter them and can choose an option on a case-by-case basis. Assuming the cost for collecting the data is low, and the information is "useful" (and doesn't contain "sensitive" information) I don't think that there'll be harm in always collecting it. Each  span initializer can choose whether or not to add the data to the span too.

**Comment by pjanotti** [comment]
I like the proposal and it will help flush issues around other areas like configuration. (Side note: config is a potential place to deal with any extra data extracted by instrumentation if not used but we don't want to bring this complexity upfront.)

Some of the data model differences, eg.: ` RecordException` (creates an OTel "event") vs `SetException` (adds tags) can be done via partial classes/interfaces so they won't affect performance. 

I looked at some instrumentations like HttpClient and the differences are relatively minor: span name, tag conventions, etc. The fact that both respect/use some of the OpenTracing conventions helps in this regard.

> The following solution applies only to new-style CallTarget instrumentations, and to DiagnosticSource-based instrumentations

Absolutely, OTel should not support even a choice in this regard for users.

**Comment by pjanotti** [comment]
Regarding:

> 1. OTel team will review this proposal an validates that it meets our goals.

@macrogreg @nrcventura I think we can consider this reviewed and approved.

**Comment by tonyredondo** [comment]
The idea looks great!

The only thing that I can see right now and just as an implementation detail is the following:

We should check and think about the `zero cost` promise. The original code we use the HttpTags instance because it's faster to set properties in a class than adding to a dictionary (lookup cost), that's why we should try to keep this optimization.

Also if we want to squeeze performance a little bit more (loosing readability) we should consider to replace the use of interface instances at field level in favor of [generics + struct + interface constraint](https://github.com/tonyredondo/PerfTests/blob/master/PerfTests/Test02.cs#L52-L73) that will be [faster](https://gist.github.com/tonyredondo/b608518de9ad408e385f469758ed046c).

But as I said, only implementation details.

**Comment by pjanotti** [comment]
> We should check and think about the zero cost promise. The original code we use the HttpTags instance because it's faster to set properties in a class than adding to a dictionary (lookup cost), that's why we should try to keep this optimization.

As you said, implementation details, anyway, I don't see a problem in keeping these internal optimizations since the goal is to have the generated spans following the OTel semantic conventions, not, the behavior of OTel API. Even when we eventually support manual OTel API integration the internal behavior of the integration code doesn't necessarily need to change.

**Comment by zacharycmontoya** [comment]
A couple of feedback items I have:
1. In addition to having a span decorator in the `OnMethodBegin` CallTarget callback, we should also add a span decorator in the `OnMethodEnd` CallTarget callback (though it doesn't apply in all cases). For example, Datadog inspects the response message and sets a tag for the HTTP status code.
2. For both decorators I mentioned, to minimize any ambiguity, I would recommend the interfaces closely match the method parameters of the appropriate `OnMethodBegin` CallTarget callback and the `OnMethodEnd` CallTarget callback

**Comment by kevingosse** [comment]
> For both decorators I mentioned, to minimize any ambiguity, I would recommend the interfaces closely match the method parameters of the appropriate OnMethodBegin CallTarget callback and the OnMethodEnd CallTarget callback

I agree with that. Actually I've been discussing with @tonyredondo about using base classes/inheritance for calltarget instrumentation rather than static methods. If we actually decide to go this way, it's possible we can find a flexible way to allow extensions points by using virtual methods and/or partial methods (I like partial methods because they can be declared in a separate file, that can be added/removed from compilation just by making changes to the csproj. This should make things much easier when pulling changes)

**Comment by pellared** [comment]
Bunch of questions and comments from a newbie before I start any coding.

**A)**
Would it be more SemVer safe (less risk for breaking changes) if the pluggable interfaces look more like: 
```
type (maybe abstract class for performance reasons) SpanInitializerForSocketsHttpHandler
{
    void InitializeSpan(Span span, HttpHandlerArgs arg, IntegrationInfo integrationId);
}

struct HttpHandlerArgs
{
    public string HttpMethod;
    public Uri RequestUri;
}
```
?

**B)**
Extra questions more regarding the vision than the first version of how it would be implemented.

1. Would you like to register more than one SpanInitilizer? E.g. OTel + Datadog. Thanks to it we could use some instrumentation for multiple backends and just use the exporter where it should land. Somone for local development my like to use Jaeger but on staging/production environments to use Datadog backend.

2. Would you like it to be possible to register (unregister) the span initializers in the runtime e.g. via the client's code or environmental variables?

I am asking these questions b/c the more code can be shared the easier it would be for us to fork/merge etc.

Of course, for the first version. I think it is more pragmatic to do it in the way proposed by @macrogreg .


I plan to start working on this issue next week. I will try to make some draft PR (even without complete implementation or tests, maybe even not everything will build) to gather quicker feedback. I want to make sure I go in the correct direction.

**Comment by pellared** [comment]
Not sure if this proposal is valid.
1. https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/issues/106
2. 128 bit `TraceID` and `Span.Status` are already making code divergence 

Any thoughts?

**Comment by macrogreg** [comment]
Closing in favor of several more detailed work items.
