### ISSUE TITLE
Rename Configuration Keys Environment Variables

### ISSUE THREAD

**Issue by rajkumar-rangaraj** [open-telemetry/opentelemetry-dotnet-instrumentation#420]
Following environment variables has very generic name. 

`OTEL_DOTNET_AUTO_ENABLED`
`OTEL_DOTNET_AUTO_LOAD_AT_STARTUP`
`OTEL_DOTNET_AUTO_CONSOLE_EXPORTER_ENABLED`
`OTEL_DOTNET_AUTO_INSTRUMENTATION_PLUGINS`

When auto-instrumentation is enabled for all 3 signals (traces, logs and metrics) this could cause confusion. I propose adding a `_TRACE_` to these variable names. Something like below.

`OTEL_DOTNET_AUTO_TRACE_ENABLED`
`OTEL_DOTNET_AUTO_TRACE_LOAD_AT_STARTUP`
`OTEL_DOTNET_AUTO_TRACE_CONSOLE_EXPORTER_ENABLED`
`OTEL_DOTNET_AUTO_TRACE_INSTRUMENTATION_PLUGINS`

**Comment by RassK** [comment]
Just an idea: `OTEL_DOTNET_AUTO_TRACE_INSTRUMENTATION_PLUGINS` => `OTEL_DOTNET_AUTO_PLUGINS`

**Comment by RassK** [comment]
> @RassK `OTEL_DOTNET_AUTO_PLUGINS` is generic, I agree with you we don't need Instrumentation as it could be used for other purpose too. How about `OTEL_DOTNET_AUTO_TRACE_PLUGINS`?

I was thinking generic for purpose, as the extension point prob comes from a single lib? So the interfaces are anyway separated by the Trace / Metrics / Logs namespace.

**Comment by rajkumar-rangaraj** [comment]
In our source `OTEL_DOTNET_AUTO_INSTRUMENTATION_PLUGINS` is directly tied to `TracerProviderBuilder `. We won't be able to use this for logs and metrics. OpenTelemetry SDK provides an option to plugin through `TracerProviderBuilder`, `MeterProviderBuilder`. Hence we need separate environmental variables to control the plugins for traces and metrics.

https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/1f9b2f41118a948ef0c52bef63642f5d5e75192c/src/OpenTelemetry.AutoInstrumentation/Configuration/Settings.cs#L75

https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/dfa682dbab10715b13e7ab9e151f33bc664da88e/src/OpenTelemetry.AutoInstrumentation/Configuration/PluginsConfigurationHelper.cs#L25

**Comment by pellared** [comment]
I think we could use a single env var `OTEL_DOTNET_AUTO_PLUGINS`. We could first check if an extension point is implemented before executing the method. This would require some little changes here: 

https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/dfa682dbab10715b13e7ab9e151f33bc664da88e/src/OpenTelemetry.AutoInstrumentation/Configuration/PluginsConfigurationHelper.cs#L39-L44

**Comment by nrcventura** [comment]
I think that it makes sense to use a more specific name that includes `trace` for now, because it will be easier for us to introduce a generic version in the future that supports both traces and metrics. This additive change can be more backwards compatible (allowing the more specific version to have more priority than the generic version). We also don't really know if it makes sense to have a generic version of all of these environment variables yet.
