### ISSUE TITLE
Plugin to add Redis Instrumentation is not working

### ISSUE THREAD

**Issue by pjanotti** [open-telemetry/opentelemetry-dotnet-instrumentation#423]
The sample server app loads a plugin that was intended to load the instrumentation for Redis. However, it doesn't report any error but I didn't see any data for the Redis client. 

Note that the plugin as part of the sample server app is not an ideal scenario, it would be better to move the "functionality" to the Vendor plugin under .the /samples folder.

**Comment by pellared** [comment]
> Note that the plugin as part of the sample server app is not an ideal scenario, it would be better to move the "functionality" to the Vendor plugin under .the /samples folder.

I think the issue was that the instrumentation needed a shared "Redis connection" object.
