### ISSUE TITLE
Bug: AspNetMvc "CLRProfiler Self-hosted" stuck on shutdown

### ISSUE THREAD

**Issue by pjanotti** [open-telemetry/opentelemetry-dotnet-instrumentation#427]
AspNetMvc is not properly shutting down and needs to be forcible closed when launched without debugging in VS2022.

**To Reproduce**
1. Open the solution on VS2022;
2. Launch the app without debugging (CTRL+F5) with the profiler "CLRProfiler Self-hosted";
3. On the app terminal hit CTRL+C. The app will start shutdown but won't actually complete it.
4. Hit CTRL+C the application terminates with an error from Windows indicating that it was forcibly terminated (0xC000013A)

```terminal
Hello from Examples.AspNetCoreMvc.OtelSdkPlugin
>>>>>>>>>>>>>>>>>>>>>>> Process: Examples.AspNetCoreMvc(12616): OpenTelemetry tracer initialized.
>>>>>>>>>>>>>>>>>>>>>>> Process: Examples.AspNetCoreMvc(12616): OpenTracingShim loaded.
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: http://localhost:54568
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\src\otel\dotnet-instr\examples\AspNetCoreMvc
info: Microsoft.Hosting.Lifetime[0]
      Application is shutting down...

C:\src\otel\dotnet-instr\examples\AspNetCoreMvc\bin\Debug\netcoreapp3.1\Examples.AspNetCoreMvc.exe (process 12616) exited with code -1073741510.
Press any key to close this window . . .
```

**Expected behavior**
Clear exit of the application.

**Additional context**
Notice that it doesn't repro when launching with the debugger, anyway, we should understand what is happening in this case.

**Comment by pjanotti** [comment]
Perhaps related with profiler "StartupHook Self-hosted" but with debugger.

```
Exception thrown at 0x00007FFE9C57D6A7 (KernelBase.dll) in Examples.AspNetCoreMvc.exe: 0x40010005: Control-C.
```

**Comment by pellared** [comment]
SIG meeting:
@rajkumar-rangaraj investigate - decision what to do later

**Comment by rajkumar-rangaraj** [comment]
I could not recreate this issue. 

```
\opentelemetry-dotnet-instrumentation\examples\AspNetCoreMvc\bin\Debug\netcoreapp3.1\Examples.AspNetCoreMvc.exe (process 88744) exited with code 0.
```

Performed some research on the error code `0xC000013A`. This is thrown on when a user terminates an app using Ctrl+C. I don't think it is coming from auto-instrumentation. 

![image](https://user-images.githubusercontent.com/9479006/162496084-8ed47323-bce6-47c5-826c-9fe2c8a70e90.png)
