### ISSUE TITLE
Bump OTel .NET references to 1.2.0

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-dotnet-instrumentation#468]
I know that you are documenting current state. April 15 is expected official release for 1.2.0.
I think that it will be good idea to bump it before our beta release.

See https://docs.google.com/document/d/1yjjD6aBcLxlRazYrawukDgrhZMObwHARJbB9glWdHj8/edit#

_Originally posted by @Kielek in https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/467#discussion_r847225050_

**Comment by pellared** [comment]
@Kielek Double-checking. Do you mean https://github.com/open-telemetry/opentelemetry-dotnet/pull/3098?

**Comment by Kielek** [comment]
@pellared, yes.

**Comment by Kielek** [comment]
My comment should be handled by #485
