### ISSUE TITLE
Logfile size is limited

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-dotnet-instrumentation#469]
Currently, after the logfile reaches the hardcoded size, no more logs are appended.

Possible options:

1. Make file size configurable (`-1` can mean unbounded)
1. Add logfile rolling
1. Add logfile rotation
Add rolling or rotation for logfiles.

_Originally posted by @pellared in https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/456#discussion_r847270204_

**Comment by pellared** [comment]
**SIG meeting:**

@lachmatt is proposing "logfile rotation" as a followup
@pjanotti  mentioned that they may be a name conflict if PID is used in the file name (PID can be reused)

**Comment by pellared** [comment]
Maybe we should use [OTel SDK's self-diagnostics](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry/README.md#self-diagnostics) for logging in order not to reinvent the wheel?

**Comment by pellared** [comment]
Closing per https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/issues/959 and https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/issues/960

**Comment by Kielek** [comment]
Fixed by @lachmatt in few latest PRs related to logging.
