### ISSUE TITLE
Add `VERSIONING.md`

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-dotnet-instrumentation#474]
Adhere to https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/versioning-and-stability.md

**Comment by pellared** [comment]
We can start by describing our pre-release versioning approach. 
The discussion started here: https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/issues/471
We can continue here.

**Comment by pellared** [comment]
## Proposal 1 (simple)

Use `0.x.y` versioning.

Bump `y` (patch) when doing a bugfix, adding new instrumentation or new features, bumping dependencies.

Bump `x` (minor) when making a breaking change e.g. change env var name. if we decide to totally redesign the approach.

When we are close to `1.0.0` we will start doing `1.0.0-rc.1`, `1.0.0-rc.2` etc.

**Comment by nrcventura** [comment]
## Proposal 2
Use `0.x.y-beta.z` versioning.

Bump `z` (beta number) for all stability related changes for `0.x.y`.

Drop `-beta.z` when we consider a release "stable" enough for non-experimental usage.

Bumping `x` and `y` occur when we make a change to a non-beta version or the next beta is different enough (such as a change in architecture) to better indicate that there is a bigger difference between releases.

When we are close to 1.0.0 we will start doing 1.0.0-rc.1, 1.0.0-rc.2 etc.

After 1.0.0 is released we can consider using suffixes -beta.1 to publish experimental builds.

This option assumes that there is a longer road towards providing the stability guaranties that a 1.0.0 release implies.
