### ISSUE TITLE
Have the same version of dependencies for Windows and Linux/MacOs in native code

### ISSUE THREAD

**Issue by Kielek** [open-telemetry/opentelemetry-dotnet-instrumentation#492]
I think that we should treat native code dependencies PR created as a reminder that we should check it also for linux.

BTW based on what I see we have different versions  for Windows and Linux/MacOs.
See https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/d486e2e5c590d2b5314fc326551e0758d0b61eec/src/OpenTelemetry.AutoInstrumentation.Native/CMakeLists.txt#L105
and 
https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/d486e2e5c590d2b5314fc326551e0758d0b61eec/src/OpenTelemetry.AutoInstrumentation.Native/packages.config#L3

_Originally posted by @Kielek in https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/487#discussion_r851066032_

**Comment by Kielek** [comment]
`nlohmann.json` dependency is needed only for `CallSite` intrumentation. We can fix it or consider to drop it as on upstream side.
@zacharycmontoya, do you have any recommendations?

**Comment by zacharycmontoya** [comment]
We still need this today, even for `CallTarget` instrumentation. We'll be able to remove this once we update the native code to an upstream version that doesn't require `integrations.json`, which I've started working on but still needs more work

**Comment by Kielek** [comment]
Thanks for clarification. Based on this, it should be enough to sync it manually without any additional CI-check, as long-term solution is to just remove this dependency.
