### ISSUE TITLE
Spell check the docs

### ISSUE THREAD

**Issue by Kielek** [open-telemetry/opentelemetry-dotnet-instrumentation#555]
Follow up task to #473.
In #473 only markdowlint is introduced.

**Comment by pellared** [comment]
The OTel .NET SDK  which added config [here](https://github.com/open-telemetry/opentelemetry-dotnet/pull/3127) for https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker which AFAIK under the hood uses https://github.com/streetsidesoftware/cspell
