### ISSUE TITLE
Release v0.1.0 opentelemetry.io blog post

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-dotnet-instrumentation#572]
Create a blog post on https://opentelemetry.io/blog/, probably by doing a PR here: https://github.com/open-telemetry/opentelemetry.io.

**Comment by nrcventura** [comment]
@open-telemetry/dotnet-instrumentation-maintainers and @open-telemetry/dotnet-instrumentation-approvers I put together [a draft document ](https://docs.google.com/document/d/1VNKZNSg_q1AXs7r-QKNencXZUhWKwt4loNusIa9-tJU/edit?usp=sharing) for our blog post that we can comment on.

When we're ready I can get a PR opened in the appropriate repo to get the blog post submitted for its final review.

**Comment by pjanotti** [comment]
@nrcventura LGTM: straight to the point taking the interested ones to our repo for more information.

**Comment by zacharycmontoya** [comment]
LGTM as well. I've left some small wording suggestions, but the overall message looks goood

**Comment by nrcventura** [comment]
The announcement is available at https://opentelemetry.io/blog/2022/dotnet-instrumentation-first-beta/
