### ISSUE TITLE
Rename OTEL_PROFILER_EXCLUDE_PROCESSES to match naming conventions

### ISSUE THREAD

**Issue by nrcventura** [open-telemetry/opentelemetry-dotnet-instrumentation#630]
We should rename the OTEL_PROFILER_EXCLUDE_PROCESSES setting so that it matches the naming conventions of the variables specific to this project.

Proposed name: `OTEL_DOTNET_AUTO_EXCLUDE_PROCESSES`.

**Comment by nrcventura** [comment]
SIG meeting: Review the other settings that don't match the naming convention and see just how much effort it will be to rename all of them to follow the naming conventions.

**Comment by Kielek** [comment]
@nrcventura, I cannot find the old name. Also other variables looks good. Could you please check it once more time?

It was fixed in https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/commit/b62129eb4de6aadd3baf44f8aadb6df4a9a54074

**Comment by nrcventura** [comment]
> @nrcventura, I cannot find the old name. Also other variables looks good. Could you please check it once more time?
> 
> It was fixed in [b62129e](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/commit/b62129eb4de6aadd3baf44f8aadb6df4a9a54074)

I must be going crazy...I came across it when I was putting together an end to end installation example, and could have sworn that I saw it in one of the scripts or docs. I'm overdue for running a `git clean -dfx`.
