### ISSUE TITLE
DiagnosticSource / OpenTelemetry Assembly Resolution Design

### ISSUE THREAD

**Issue by rajkumar-rangaraj** [open-telemetry/opentelemetry-dotnet-instrumentation#633]
<H2>DiagnosticSource Assembly Load Design</H2>

<H4>Scope</H4>

- .NET 6.0
- .NET 7.0-Preview

<H4>Out of scope</H4>

- .NET Core 3.1 - End of life on Dec 3rd, 2022
- .NET 5.0 - End of life on May 8th, 2022
- .NET Framework 

<H3>DiagnosticSource Usage in An Application</H3>

<H4>.NET 6.0</H4>
There are two possible ways to use System.Diagnostics.DiagnosticSource with .NET 6.0 apps.

1. App with no package reference to DiagnosticSource. 
In this scenario, if there is a need DiagnosticSource 6.0.0 version from the framework will be utilized.

2. App with direct or indirect package reference to DiagnosticSource >= 6.0.0. 

<H4>.NET 7.0 - Preview</H4>
 
For .NET 7.0 apps, only DiagnosticSource version of 7.0.0 will be utilized. 

1. App with no reference to DiagnosticSource. 
In this scenario, if there is a need DiagnosticSource 7.0.0 version from the framework will be utilized.

2. App with direct or indirect have reference to DiagnosticSource 7.0.0.  

**Note**: Loading DiagnosticSource version less than .NET version is not possible. For example, In .NET 6.0 loading DiagnosticSource version less than 6.0.0 is not possible. Even if an app has reference to use 5.0.0 version of DiagnosticSource, framework will auto-upgrade DiagnosticSource to 6.0.0 (framework version) during the build. 

<H3>DiagnosticSource Assembly Load Issue</H3>

An application has a package reference to V1 version of DiagnosticSource. An attempt to dynamically load V2 (higher) version of DiagnosticSource in default assembly context either from StartupHook or CLR Profiler will crash the application.

In case of OpenTelemetry Auto-Instrumentation, if it tries to load DiagnosticSource version higher than the DiagnosticSource version used by an application we will run into this issue. The workaround for this issue is to take a build time package reference to the same version of DiagnosticSource or use additional deps with runtime store.
 
This issue will not happen currently in .NET 6.0 applications as the DiagnosticSource version used is same or higher than the one used by OpenTelemetry SDKs. But we could anticipate an issue, when OpenTelemetry SDK releases a package which takes dependency on 7.0.0 version of System.Diagnostics.DiagnosticSource.
 
For .NET 7.0 applications, we may not run into this issue until DiagnosticSource 8.0.0 is released.

<H3>DiagnosticSource Assembly Load Resolution Proposal</H3>

<H4>Proposal 1:</H4> 

OpenTelemetry Auto-Instrumentation to include two versions of OpenTelemetry SDK, first SDK package with the reference to lowest possible supported version of DiagnosticSource and second SDK package with highest supported version of OpenTelemetry SDK. 

**Limitations:** 

1. If a security vulnerability is identified in OpenTelemetry SDK we need help from SDK maintainers to fix the critical security bugs in the package which has the lowest possible supported version of DiagnosticSource. For example, OpenTelemetry SDK 1.2, 1.3 and 1.4 has reference to DiagnosticSource 6.0.0 and OpenTelemetry SDK 1.5 has reference to 7.0.0. When critical security fixes are identified, SDK will apply the fix to 1.5 version and release a new version. In addition, some help from SDK maintainer to patch 1.4 version and release 1.4.1 for auto-instrumentation needs.
2. If a security vulnerability is identified in DiagnosticSource and if a minor version upgrade happens with DiagnosticSource. Auto-Instrumentation should back-off when it identifies a vulnerable library and provide a message in logs to update the DiagnosticSource. Based on a need, we could also use a flag to control this behavior.
**Example**: App has a direct reference to DiagnosticSource 6.0.0 and if critical security bugs are fixed with 6.0.1. Auto-Instrumentation should be updated to carry its least DiagnosticSource which has reference to 6.0.1. 

<H4>Proposal 2:</H4>  

This is discussed on another issue #260.	

Load OpenTelemetry referenced `System.Diagnostics.DiagnosticSource.dll` in a different assembly context using `Assembly.LoadFile`. Create a proxy to listen to `Activity`s emitted by a lower version of `DiagnosticSource` and create a clone of the same `Activity` in the OpenTelemetry supported `DiagnosticSource`.  

Enable the proxy feature when an application uses a lower version of `DiagnosticSource` than the OpenTelemetry referenced DiagnosticSource.

Use `Additional-deps` in supported environments.

```text
+--------------------+             +-------------------+    
| DS (Lower Version) |             | DS (OTel Version) |---------
+--------------------+             +-------------------+         |
        |                                 ^                      | OTel supported Activity
        | Activity                        |                      v
        |                +-------+        |             +----------------------+
         --------------> | Proxy | -------              | Otel Instrumentation |
                         +-------+                      +----------------------+
				 
```
**Limitation**

- High maintenance cost – We need to track the possible API changes and maintain different proxy versions for all supported DiagnosticSource

<H2>OpenTelemetry SDK Side-by-Side Design</H2>

Four possible scenarios for an auto-instrumentation to load OpenTelemetry SDK.
 
1. Application without OpenTelemetry SDK
4. Application with OpenTelemetry API/SDK same as of Auto-Instrumentation OpenTelemetry SDK.
5. Application with OpenTelemetry API/SDK higher than Auto-Instrumentation OpenTelemetry SDK.
6. Application with OpenTelemetry API/SDK lower than Auto-Instrumentation OpenTelemetry SDK.

There are no problems with approach 1, 2 and 3 as the app does not use or uses the same or higher version of OpenTelemetry SDK package. 

In scenario 4, an attempt is made to dynamically load a higher version of SDK from OpenTelemetry Auto-Instrumentation. This will crash an application. We could avoid the crash by taking build time dependency.

Explored ILRepack option, this may not work well for us. ILRepack makes it difficult for custom processors / exporters to be used with this auto-instrumentation plugin.

<H4>Proposal</H4>  

OpenTelemetry Auto-Instrumentation to include two versions of OpenTelemetry SDK, first SDK package with the lowest supported SDK version and another with highest supported version of OpenTelemetry SDK. 

In this approach will have the TracerProvider from user application and Instrumentation. This collects duplicate telemetry, and we should have an option at SDK to disable the tracer provider for user-initiated providers. Work with OpenTelemetry SDK maintainers/approvers to introduce a new switch in TracerProvider to stop the further build of TracerProvider or MeterProvider after the auto-instrumentation is initialized. This could be a special option to help only auto-instrumentation needs and no need be documented for public usage.

https://github.com/open-telemetry/opentelemetry-dotnet/blob/c7af2d0646012aa07f32ffe60734961581a6a2a8/src/OpenTelemetry/Trace/TracerProviderBuilderBase.cs#L188

**Comment by RassK** [comment]
Adding here @pjanotti vision and my idea that was built on top of Paulo's idea.
![dependencies](https://user-images.githubusercontent.com/4929112/166903447-4a88e9e6-c897-42ce-8ff5-da6e07709798.jpg)

Sources for case 1:

Create a .NET Core application with plugins
https://docs.microsoft.com/en-us/dotnet/core/tutorials/creating-app-with-plugin-support

Understanding System.Runtime.Loader.AssemblyLoadContext
https://docs.microsoft.com/en-us/dotnet/core/dependency-loading/understanding-assemblyloadcontext

AssemblyDependencyResolver 
https://docs.microsoft.com/en-us/dotnet/api/system.runtime.loader.assemblydependencyresolver

**Comment by nrcventura** [comment]
I think that we should leverage the ideas in proposal 1. I think that it will be quicker to build and easier to maintain. To prevent some of the dependency loading errors we should be able to inspect the version of .NET in use and potentially see if DiagnosticSource is already loaded, before we attempt to load our code.

> Work with OpenTelemetry SDK maintainers/approvers to introduce a new switch in TracerProvider to stop the further build of TracerProvider or MeterProvider after the auto-instrumentation is initialized. This could be a special option to help only auto-instrumentation needs and no need be documented for public usage.

In the case of someone already bootstrapping the SDK manually, I think that it might be better to disable our own bootstrapping, or at least provide a configuration to disable that bootstrapping. Perhaps this is something that the SDK could detect and allow us to capture some sort of warning/error. It just seems unintuitive to automatically disable someones code, which could cause a difference in behavior that they were not expecting. 

In the case of a cloud offering leveraging this project to collect telemetry out of the box for the cloud customer, perhaps the cloud environment tooling could automatically detect this scenario during the deployment process, and adjust some of its default settings?

**Comment by pellared** [comment]
It seems to me that @RassK Case 1 could be a "general" solution for solving assembly conflicts.

**Comment by Kielek** [comment]
Discussed with @rajkumar-rangaraj , moving to post 1.0.0.
For current state we should be safe to work with what we have

**Comment by alanwest** [comment]
> An application has a package reference to V1 version of DiagnosticSource. An attempt to dynamically load V2 (higher) version of DiagnosticSource in default assembly context either from StartupHook or CLR Profiler will crash the application.

I have not found this to be true. Is there a scenario where this is still problematic?

**Comment by rajkumar-rangaraj** [comment]
Closing this issue as we want to pursue out-of-process based solution.
