### ISSUE TITLE
Document supported versions for instrumented libraries

### ISSUE THREAD

**Issue by pjanotti** [open-telemetry/opentelemetry-dotnet-instrumentation#636]
Versions for source instrumentations are just marked with an asterisk. Perhaps it is worth to link to respective information on the package or copy it on our docs. See https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/635#discussion_r861159969 for context.

**Comment by pjanotti** [comment]
SIG meeting: link to package documentation (in GH).

**Comment by pellared** [comment]
I changed the title as I found it misleading.

THe information regarding the instrumentation libraries versions is somehow documented here: https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/4fa14e4ddb7e1daeee42071f6d5f2a49040d0852/docs/README.md?plain=1#L25-L27
