### ISSUE TITLE
[Observation] Grpc libraries out of sync

### ISSUE THREAD

**Issue by RassK** [open-telemetry/opentelemetry-dotnet-instrumentation#645]
### What

**Testbed:** Grpc applications (ASP.NET Core Grpc server + Grpc Console Client) + Otlp exporter over Grpc. Application is configured to use lower versions of Grpc libs than SDK. Application 2.41, SDK 2.43.
**Hypothesis:** Crash or 2 different sets of Grpc libraries.
**Result:** Everything survives and works, although lower version is loaded.
![grpc_anomaly](https://user-images.githubusercontent.com/4929112/166665218-d472341e-8c3f-4110-aa44-7443392e27a1.png)

**New Hypothesis:** SDK will crash with an exception (MissingMethodException, MissingMemberException, etc) when tries to execute code that doesn't exist in lower version.
**Result:** (TODO: Grpc client has quite compact public part, hard to break intentionally currently)

**Comment by RassK** [comment]
> This behavior will likely also vary between .NET Framework and .NET Core depending on which Grpc library is used. There are probably some additional failure modes when the native Grpc component is used.

I would guess that with .NET Framework at least it's quite easy to fix it: just update binding redirections.

**Comment by pjanotti** [comment]
SIG meeting: closing this as understood, will revisit and fix/document as actual issues are found.

**Comment by RassK** [comment]
[Case 1](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/issues/633#issuecomment-1118389914) could be potential fix. Does not touch application's version and in same time loads a version for SDK to use.

![image](https://user-images.githubusercontent.com/4929112/166975801-b4163634-fd5f-4b02-b1bd-21ce2099a703.png)
