### ISSUE TITLE
Error while Instrumenting beta version with netcoreapp3.1 application

### ISSUE THREAD

**Issue by NamitaJaokar** [open-telemetry/opentelemetry-dotnet-instrumentation#647]
Hi ,

I am trying to instrument my application which is netcoreapp3.1 version. While trying to run the application I'm getting below error stack trace 
Unhandled exception. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
---> System.TypeInitializationException: The type initializer for 'OpenTelemetry.AutoInstrumentation.Loader.Startup' threw an exception.
---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
---> System.TypeInitializationException: The type initializer for 'OpenTelemetry.Sdk' threw an exception.
---> System.IO.FileLoadException: Could not load file or assembly 'System.Diagnostics.DiagnosticSource, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. Could not find or load a specific file. (0x80131621)
File name: 'System.Diagnostics.DiagnosticSource, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
---> System.IO.FileLoadException: Could not load file or assembly 'System.Diagnostics.DiagnosticSource, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at System.Reflection.Assembly.LoadFromResolveHandler(Object sender, ResolveEventArgs args)
   at System.Runtime.Loader.AssemblyLoadContext.InvokeResolveEvent(ResolveEventHandler eventHandler, RuntimeAssembly assembly, String name)
   at System.Runtime.Loader.AssemblyLoadContext.OnAssemblyResolve(RuntimeAssembly assembly, String assemblyFullName)
   at OpenTelemetry.Sdk..cctor()
 
 
   --- End of inner exception stack trace ---
   at OpenTelemetry.Sdk.CreateTracerProviderBuilder()
   at OpenTelemetry.AutoInstrumentation.Instrumentation.Initialize() in D:\a\opentelemetry-dotnet-instrumentation\opentelemetry-dotnet-instrumentation\src\OpenTelemetry.AutoInstrumentation\Instrumentation.cs:line 86
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at OpenTelemetry.AutoInstrumentation.Loader.Startup.TryLoadManagedAssembly() in D:\a\opentelemetry-dotnet-instrumentation\opentelemetry-dotnet-instrumentation\src\OpenTelemetry.AutoInstrumentation.Loader\Startup.cs:line 71
   at OpenTelemetry.AutoInstrumentation.Loader.Startup..cctor() in D:\a\opentelemetry-dotnet-instrumentation\opentelemetry-dotnet-instrumentation\src\OpenTelemetry.AutoInstrumentation.Loader\Startup.cs:line 46
  --- End of inner exception stack trace ---
   at OpenTelemetry.AutoInstrumentation.Loader.Startup..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean wrapExceptions, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& hasNoDefaultCtor)
   at System.RuntimeType.CreateInstanceDefaultCtorSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean fillCache)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Reflection.Assembly.CreateInstance(String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Reflection.Assembly.CreateInstance(String typeName)
   at StartupHook.Initialize() in D:\a\opentelemetry-dotnet-instrumentation\opentelemetry-dotnet-instrumentation\src\OpenTelemetry.AutoInstrumentation.StartupHook\StartupHook.cs:line 60
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.StartupHookProvider.CallStartupHook(StartupHookNameOrPath startupHook)
   at System.StartupHookProvider.ProcessStartupHooks()

Below is the environment variables set in my script:
export COR_ENABLE_PROFILING="1"
export COR_PROFILER="{918728DD-259F-4A6A-AC2B-B85E1B658318}"
export COR_PROFILER_PATH_64="D:/OTEL-dotnet/opentelemetry-dotnet-instrumentation-windows/win-x64/OpenTelemetry.AutoInstrumentation.Native.dll"
export CORECLR_ENABLE_PROFILING="1"
export CORECLR_PROFILER="{918728DD-259F-4A6A-AC2B-B85E1B658318}"
export CORECLR_PROFILER_PATH_64="D:/OTEL-dotnet/opentelemetry-dotnet-instrumentation-windows/win-x64/OpenTelemetry.AutoInstrumentation.Native.dll"
export DOTNET_ADDITIONAL_DEPS="D:/OTEL-dotnet/opentelemetry-dotnet-instrumentation-windows/AdditionalDeps"
export DOTNET_SHARED_STORE="D:/OTEL-dotnet/opentelemetry-dotnet-instrumentation-windows/store"
export DOTNET_STARTUP_HOOKS="D:/OTEL-dotnet/opentelemetry-dotnet-instrumentation-windows/netcoreapp3.1/OpenTelemetry.AutoInstrumentation.StartupHook.dll"
export OTEL_DOTNET_AUTO_HOME="D:/OTEL-dotnet/opentelemetry-dotnet-instrumentation-windows/"
export OTEL_DOTNET_AUTO_INTEGRATIONS_FILE="D:/OTEL-dotnet/opentelemetry-dotnet-instrumentation-windows/integrations.json"
export OTEL_DOTNET_AUTO_DEBUG="true"
export OTEL_DOTNET_AUTO_ENABLED="true"
export OTEL_TRACE_METRICS_ENABLED="true"
export OTEL_TRACES_EXPORTER="zipkin"
export OTEL_SERVICE_NAME="EmpApplicationService"
export OTEL_AGENT_HOST="localhost"
export OTEL_TRACE_AGENT_PORT="9411"
export OTEL_EXPORTER_ZIPKIN_ENDPOINT="http://localhost:9411/api/v2/spans"
export OTEL_DOTNET_AUTO_LOG_DIRECTORY="C:/ProgramData/OpenTelemetry .NET AutoInstrumentation/logs"
export OTEL_DOTNET_AUTO_INCLUDE_PROCESSES="EmpApplication.exe,PostgreSqlDotnetCore.exe"

Command Used to run the script:
source instrument_new_version.sh
cd /d/pathtomyapplication/PostgreSqlDotnetCore
./PostgreSqlDotnetCore.exe

Could someone please help/advise on resolving the issue.

Thanks & Regards,
Namita

**Comment by pellared** [comment]
Can you add a reference to [System.Diagnostics.DiagnosticSource 6.0.0](https://www.nuget.org/packages/System.Diagnostics.DiagnosticSource/6.0.0) in your instrumented application?

Reference: https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/main/docs/troubleshooting.md#handling-of-assembly-version-conflicts

**Comment by pellared** [comment]
I also think that the following env vars are not needed

```
export OTEL_AGENT_HOST="localhost"
export OTEL_TRACE_AGENT_PORT="9411"
```

**Comment by NamitaJaokar** [comment]
Hi @pellared ,

Adding System.Diagnostics.DiagnosticSource version 6.0.0 resolved the error I was initially getting. But still I'm unable to view the traces in zipkin.
I have removed the OTEL_AGENT_HOST and OTEL_TRACE_AGENT_PORT from the configurations.

Attaching the tracer-native logs.
[dotnet-tracer-native-MyAppname.log](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/files/8620675/dotnet-tracer-native-MyAppname.log)

Please let me know incase I have missed out on any configurations.

Thanks & Regards,
Namita

**Comment by pellared** [comment]
You probably need to enable some library instrumentations via `OTEL_DOTNET_AUTO_ENABLED_INSTRUMENTATIONS` env var

See: https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/main/docs/config.md#instrumented-libraries-and-frameworks

**Comment by NamitaJaokar** [comment]
Hi @pellared ,

After adding OTEL_DOTNET_AUTO_ENABLED_INSTRUMENTATIONS to the configurations I am able to view traces in zipkin.
But the database traces for the transactions are not available. My application uses postgreSQL as database with package reference Npgsql.EntityFrameworkCore.PostgreSQL.

Are there any specific configurations for adding instrumentation for postgreSQL.

Also, The above instrumentation set up does not work for net5.0 version application. Is there something I am missing in the instrumentation setup. Kindly advise.

Thank you in advance,
Namita

**Comment by nrcventura** [comment]
The postgreSQL library is not supported at this point by this project. There does appear to be [some OpenTelemetry support in newer versions of the npgsql library](https://github.com/npgsql/npgsql/blob/25030d4477161e9960ec6fcf41613eeb6ac3eff6/src/Npgsql.OpenTelemetry/README.md), but you need to directly use the OpenTelemetry SDK to take advantage of it. PostgreSQL is something that I believe this project should eventually support, it is just not on our immediate roadmap.

**Comment by pellared** [comment]
> Also, The above instrumentation set up does not work for net5.0 version application. Is there something I am missing in the instrumentation setup. Kindly advise.

Nothing comes to my mind. And I am not sure if it is worth investing time to troubleshoot it as we have removed support for .NET 5.0 for the upcoming release. Today is its official last day of support (see: https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core). Can you try with .NET 6.0?

**Comment by nrcventura** [comment]
Issue #666 can be used to follow our progress on enabling support for PostgreSQL.

**Comment by NamitaJaokar** [comment]
Thanks @nrcventura . Will check for updates in the above link provided for PostgreSQL Instrumentation.

@pellared , Will check with net6.0 and let you know on the results.

I also wanted to understand how can asp.net mvc applications can be configured with the auto-instrumentation setup. Is it similar to the current setup or do I need to make changes in the configurations.

Please suggest/advise on the same. 

Thanks & Regards,
Namita Jaokar

**Comment by pellared** [comment]
> I also wanted to understand how can asp.net mvc applications can be configured with the auto-instrumentation setup. Is it similar to the current setup or do I need to make changes in the configurations.

Do you mean "legacy" .NET Framework ASP.NET? If so then you can look at https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/issues/631

We plan to improve the documentation in the upcoming days/weeks, but I suggest not waiting for it.

**Comment by NamitaJaokar** [comment]
Hi @pellared ,

I deployed my asp.net mvc application over IIS, But when I browse through the application it's giving me below error.

![image](https://user-images.githubusercontent.com/32196871/168227837-c61372f5-65ee-4ce4-85ac-13f5af47b41c.png)

Could you please advise on the same. I have tried deploying multiple applications and they give similar error on browsing the URL.

Thanks in advance,
Namita Jaokar

**Comment by pellared** [comment]
I see that our test application has the following reference https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/main/test/test-applications/integrations/aspnet/TestApplication.AspNet/packages.config#L12

Can you try adding it? I am right now on mobile so I am unable to verify it myself.

**Comment by NamitaJaokar** [comment]
@pellared , @nrcventura 

I am unable to debug further into this issue. I suspect this to be the issue with the previous beta version release (which required the .msi to be installed) installed in my system.
I have uninstalled the setup and still facing the same issue.
Below is the error message:
**Could not load file or assembly 'OpenTelemetry.AutoInstrumentation.AspNet, Version=1.0.0.0, Culture=neutral, PublicKeyToken=34b8972644a12429' or one of its dependencies. The system cannot find the file specified.**

None of my asp.net application deployed on IIS have package referencing to OpenTelemetry.

Below is the screen shot of the error with stacktrace details while trying to load the application.
![image](https://user-images.githubusercontent.com/32196871/168761737-26470b8e-40f3-434b-b267-a2c52187099c.png)


The application is up and running when checked through visual studio IIS Express. The error only occurs in IIS.
I have tried restarting the IIS server after uninstalling the older beta version. But that as well did not work.
I am unable to understand why the Application deployed over IIS is trying to load the assembly OpenTelemetry.AutoInstrumentation.AspNet


Could you please help and advise me so as to mitigate this issue as I am unable to proceed further.

Thanks in advance,
Namita

**Comment by pellared** [comment]
> I am unable to understand why the Application deployed over IIS is trying to load the assembly OpenTelemetry.AutoInstrumentation.AspNet

It looks like some trash from the previous beta version release (which required the .msi to be installed)

How are you setting the environment variables when deploying the application to IIS? Have you configured the IIS-related Windows Services (`WAS` and `W3SVC`) to have the required environmental variables? 

Side note:

I am working on https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/issues/632

You can take a look at https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/688. It is not fully tested and reviewed but it might occur helpful for you. ⚠️  Just take notice that some env vars names are different in my branch (the new version will have `_TRACES` in some names). So for example set `OTEL_DOTNET_AUTO_ENABLED_INSTRUMENTATIONS` and NOT `OTEL_DOTNET_AUTO_TRACES_ENABLED_INSTRUMENTATIONS`

**Comment by pellared** [comment]
@NamitaJaokar , any success?

https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/688 is merged so you can benefit from the latest docs

**Comment by NamitaJaokar** [comment]
@pellared 
Yes, All the asp.net applications which initially were giving error _Could not load file or assembly 'OpenTelemetry.AutoInstrumentation.AspNet, Version=1.0.0.0, Culture=neutral, PublicKeyToken=34b8972644a12429' or one of its dependencies. The system cannot find the file specified._ is resolved.

The issue was probably with the first pre-release beta version i.e the OTEL .msi installed. My IIS configuration's applicationHost.config had reference to opentelemetry 
"<add name="OpenTelemetry.AutoInstrumentationModule" type="Datadog.Trace.AspNet.TracingHttpModule,OpenTelemetry.AutoInstrumentation.AspNet,Version=1.0.0.0,Culture=neutral,PublicKeyToken=34b8972644a12429" preCondition="managedHandler,runtimeVersionv4.0" />" in the module attributes of the .config.

Removing the above from the applicationhost.config and the sample application's .config which are present in the appPools path inside inetpub and performing iisreset resolved the issue for me 

The application was able to run successfully after performing above steps.

Best Regards,
Namita
