### ISSUE TITLE
Refine `OTEL_DOTNET_AUTO_ENABLED_INSTRUMENTATIONS` description

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-dotnet-instrumentation#649]
We already had 2 cases where the users have not set the `OTEL_DOTNET_AUTO_ENABLED_INSTRUMENTATIONS` env var:
- https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/issues/647
- https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/issues/631

I guess we should describe it somewhere in the main `README.md`.

**Comment by nrcventura** [comment]
I agree. I think that we need a bigger/more prominent call out for that setting.
