### ISSUE TITLE
[Feature Request] Add support for PostgreSQL instrumentation

### ISSUE THREAD

**Issue by nrcventura** [open-telemetry/opentelemetry-dotnet-instrumentation#666]
Add support for PostgreSQL instrumentation.

PostgreSQL provides some [source-based instrumentation in its own repository](https://github.com/npgsql/npgsql/blob/25030d4477161e9960ec6fcf41613eeb6ac3eff6/src/Npgsql.OpenTelemetry/README.md) (separate from the OpenTelemetry repositories). We should add support for this instrumentation library so that PostgreSQL users can start capturing telemetry for the PostgreSQL usage.

**Comment by RassK** [comment]
Similar case with MongoDb, I have a question if we should actually reference the 3rd party package or just add the src ourselves?
This is again basically one liner Nuget package. With MongoDb I didn't include the src subscribing extension package.

instead just: https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/cccdec06cde4fdec27c52c842780ae886c01c72d/src/OpenTelemetry.AutoInstrumentation/Configuration/EnvironmentConfigurationHelper.cs#L32

**Comment by nrcventura** [comment]
Yes, I think we can use a similar approach, but I'll delegate the decision to someone that has looked into the details more.

**Comment by pellared** [comment]
It should be enough to enable it by `builder.AddSource("Npgsql");`.

Reference: https://github.com/npgsql/npgsql/blob/f0650f624f7e6cd22979f9a642c1dbff91cb4387/src/Npgsql.OpenTelemetry/TracerProviderBuilderExtensions.cs#L18
