### ISSUE TITLE
Do not require installing `OpenTelemetry.Instrumentation.AspNet.TelemetryHttpModule` when instrumenting an ASP.NET application

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-dotnet-instrumentation#689]
1. Describe steps to instrument ASP.NET (.NET Framework) application without installing  `OpenTelemetry.Instrumentation.AspNet.TelemetryHttpModule`
1. Update the test-application to not reference `OpenTelemetry.Instrumentation.AspNet.TelemetryHttpModule` (if possible)

_Originally posted by @pellared in https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/688#discussion_r876992545_

I found it as the easiest way to add `OpenTelemetry.Instrumentation.AspNet.TelemetryHttpModule` ASP.NET HTTP module which is required by [OpenTelemetry.Instrumentation.AspNet](https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/src/OpenTelemetry.Instrumentation.AspNet). This is also how our `test-application` was created.

I think it should be possible to simply edit `Web.config` to add the `OpenTelemetry.Instrumentation.AspNet.TelemetryHttpModule` as the required assemblies are under `$trace-home/net462`. I will check it tomorrow.

I would prefer to make baby steps. Therefore I am creating a GH issue for it. Please resolve if you are fine with such an approach.

**Comment by rajkumar-rangaraj** [comment]
We can make this lot easier by providing a PowerShell script register the modules to ApplicationHost.config or web.config. `ApplicationHost.config` is a better place as it gets applied to all the ASP.NET apps running under IIS.

**Comment by pellared** [comment]
I propose to postpone the creation of a helper script. We do not even have "supported" scripts to help with instrumenting a CLI application.
