### ISSUE TITLE
Add tests for environment helpers

### ISSUE THREAD

**Issue by pjanotti** [open-telemetry/opentelemetry-dotnet-instrumentation#705]
There are enough behavior behind the environment helpers, especially `SetExporter`, to justify dedicated unit tests. The tests should cover:

- EnvironmentConfigurationMetricHelper
- EnvironmentConfigurationTracerHelper

**Comment by pellared** [comment]
@pjanotti Do you expect any more tests than we have right now (mostly thanks to https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/845)? I think we have integration tests for testing these classes - anything other than them would be very artificial.

**Comment by pjanotti** [comment]
@pellared this issue was opened when I was doing https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/708 - the helper was not working as intended and there were no tests covering it. Now they are covered via integration tests as you said. Taking that into account I don't think we need this anymore.
