### ISSUE TITLE
Separate settings that apply to all signals

### ISSUE THREAD

**Issue by pjanotti** [open-telemetry/opentelemetry-dotnet-instrumentation#706]
Currently some settings that apply to metrics and traces are under "Tracer" we should factor out settings that apply to all signals for consistency and to avoid confusion.

**Comment by pjanotti** [comment]
OTLP protocol is also related to this issue, see https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/708/files#r886378692

**Comment by dszmigielski** [comment]
Are there any particular settings that you had in mind? We already have separate sections in https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/main/src/OpenTelemetry.AutoInstrumentation/Configuration/ConfigurationKeys.cs as well as separated class with signal agnostic settings - https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/main/src/OpenTelemetry.AutoInstrumentation/Configuration/Settings.cs

**Comment by pjanotti** [comment]
@dszmigielski I found just one such case, see #1082.

**Comment by pjanotti** [comment]
> OTLP protocol is also related to this issue, see https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/708/files#r886378692

Separating OTLP settings per signal is a much bigger issue, let's track it at #1083
