### ISSUE TITLE
Add integration tests for selected docker images

### ISSUE THREAD

**Issue by pjanotti** [open-telemetry/opentelemetry-dotnet-instrumentation#715]
Add integration tests that use the selected docker images: it is possible that our build requires dependencies that are not present on the some docker images, see https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/issues/703#issuecomment-1143088402 for an example that the first beta didn't work on netcoreapp3.1.

**Comment by Kielek** [comment]
Closing. Tests for different systems will be handled under #2006.
