### ISSUE TITLE
[Metrics] Support for Prometheus exporter

### ISSUE THREAD

**Issue by Kielek** [open-telemetry/opentelemetry-dotnet-instrumentation#832]
# Feature Request

https://www.nuget.org/packages/OpenTelemetry.Exporter.Prometheus/1.3.0-rc.2

**Comment by rajkumar-rangaraj** [comment]
Adding Prometheus exporter will make the integration test efforts easier. I will start the work and send a PR. Once this work is complete we will start work on Integration tests to cover Prometheus exporter and all supported metrics instrumentation.

**Comment by rajkumar-rangaraj** [comment]
Below are the 4 available options for OpenTelemetry .NET Prometheus Exporter. Prometheus exporter does not define any environment variables to like Zipkin in the SDK. Until we follow up and create environment variables with OpenTelemetry SDK, proposing the below environmental variables for usage. Please let me know your thoughts.

| Options | Example | Proposed Environment Variable
| -- | -- | -- |
| StartHttpListener | true | OTEL_AUTO_PROMETHEUS_STARTHTTPLISTENER |
| HttpListenerPrefixes | http://localhost:{port}/ | OTEL_AUTO_PROMETHEUS_HTTPLISTENERPREFIXES |
| ScrapeEndpointPath | /metrics | OTEL_AUTO_PROMETHEUS_SCRAPEENDPOINTPATH |
| ScrapeResponseCacheDurationMilliseconds | 10000  | OTEL_AUTO_PROMETHEUS_SCRAPERESPONSECACHEDURATIONMILLISECONDS |

**Comment by pellared** [comment]
Maybe we could simply implement the env var defined by the [spec](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/sdk-environment-variables.md) which are:

- `OTEL_METRICS_EXPORTER`
- `OTEL_EXPORTER_PROMETHEUS_HOST`
- `OTEL_EXPORTER_PROMETHEUS_PORT`

I guess it should be enough for now.

**Comment by Kielek** [comment]
There is a ongoing initiative to split Prometheus exporters into two parts
 - AspNetCore
 - HttpListener

See https://github.com/open-telemetry/opentelemetry-dotnet/issues/3057 and https://github.com/open-telemetry/opentelemetry-dotnet/pull/3361
