### ISSUE TITLE
Update OpenTelemetry protos when next version is released

### ISSUE THREAD

**Issue by nrcventura** [open-telemetry/opentelemetry-dotnet-instrumentation#849]
There is an update to [opentelemetry-proto](https://github.com/open-telemetry/opentelemetry-proto/blob/main/opentelemetry/proto/metrics/v1/metrics.proto) with C# namespace. I recommend taking the newer version of proto files from the repo.

_Originally posted by @rajkumar-rangaraj in https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/716#pullrequestreview-1010767556_

**Comment by pellared** [comment]
SIG meeting:
We need just to monitor https://github.com/open-telemetry/opentelemetry-proto is released.
