### ISSUE TITLE
Remove big BLOBs from Git repo history

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-dotnet-instrumentation#86]
## Problem

After https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/70 we pulled BLOBs into the Git repository. This is what I saw after `git fetch`:

```sh
Receiving objects: 100% (597/597), 43.73 MiB | 4.30 MiB/s, done
```

Inspecting big objects in Git:
```
$git rev-list --all | xargs -rL1 git ls-tree -r --long | sort -uk3 | sort -rnk4  | less
100644 blob 36346064ad2437279f8a8371df00c75bf88b37cf 22442896   test/Datadog.Trace.ClrProfiler.IntegrationTests/CI/Data/gitda
ta-03/objects/pack/pack-7fa7cbe93d4ea75e170452b838378c33df1f8b50.pack
100644 blob 8dbb48aa5640ae723c1523e3edafa1c46cb45b22 22441964   test/Datadog.Trace.ClrProfiler.IntegrationTests/CI/Data/gitda
ta-01/objects/pack/pack-996ad06b538da839c6c16a8e878c37ac7a66b0a8.pack
100644 blob 9958f19ca10cda84161780068c66cd60d088577b 22437075   test/Datadog.Trace.ClrProfiler.IntegrationTests/CI/Data/gitda
ta-04/objects/pack/pack-c15d5f0d30e22438173611f8d403f4df497c024f.pack
100644 blob da42dd55fccac27b620396054d50484daba46f55 22436166   test/Datadog.Trace.ClrProfiler.IntegrationTests/CI/Data/gitda
ta-02/objects/pack/pack-ae1a6c8f26907755201d8984390c0679322589af.pack
100644 blob 932a42009599e096b061c8e0cf52dca0de713623 22435531   test/Datadog.Trace.ClrProfiler.IntegrationTests/CI/Data/gitda
ta-05/objects/pack/pack-cf1c5a3f513e65c8502d26ae38d746a506b9d564.pack
100644 blob ae6a3a3818007dff2723d43b95246664e6174ad7 5412090    src/Datadog.Trace.ClrProfiler.Native/lib/fmt_x64-windows-stat
ic/lib/fmt.lib
100644 blob be5cec66567e69b6abdf7f2c753285799853745a 5271876    src/Datadog.Trace.ClrProfiler.Native/lib/fmt_x64-windows-stat
ic/debug/lib/fmtd.lib
100644 blob 114e7079afe99a530d6e2182e3956b89484a424d 4550498    src/Datadog.Trace.ClrProfiler.Native/lib/fmt_x86-windows-stat
ic/lib/fmt.lib
100644 blob 9ceb6355130a5e87b5e0c97e9d46d73f92d4ea10 3797062    src/Datadog.Trace.ClrProfiler.Native/lib/fmt_x86-windows-stat
ic/debug/lib/fmtd.lib
100644 blob 8f68a334d9b4481d96ded3142a9a56764977f0ad  808620    test/Datadog.Trace.ClrProfiler.IntegrationTests/CI/Data/gitda
ta-03/objects/pack/pack-7fa7cbe93d4ea75e170452b838378c33df1f8b50.idx
100644 blob 74104f742f407c6009b32fa64e70932f5aefd193  808620    test/Datadog.Trace.ClrProfiler.IntegrationTests/CI/Data/gitda
ta-04/objects/pack/pack-c15d5f0d30e22438173611f8d403f4df497c024f.idx
100644 blob 5e6a540477537aff1bf86d0948e2d565e8a24308  808620    test/Datadog.Trace.ClrProfiler.IntegrationTests/CI/Data/gitda
ta-02/objects/pack/pack-ae1a6c8f26907755201d8984390c0679322589af.idx
100644 blob 58b8b2d9096d92f48a80bc504ed774bcc008f8d9  808620    test/Datadog.Trace.ClrProfiler.IntegrationTests/CI/Data/gitda
ta-01/objects/pack/pack-996ad06b538da839c6c16a8e878c37ac7a66b0a8.idx
100644 blob d489a8287e83a9939d9c415dae07db8d593c0adb  808340    test/Datadog.Trace.ClrProfiler.IntegrationTests/CI/Data/gitda
ta-05/objects/pack/pack-cf1c5a3f513e65c8502d26ae38d746a506b9d564.idx
```

The first file in the list is 22442896 Bytes = **21.4032 Megabytes**
The last one 808340 Bytes = 0.770893 Megabytes (still quite big)

These files were introduced here in the upstream repository: https://github.com/DataDog/dd-trace-dotnet/pull/1247/

There is a git folder parser within the tracer for a Datadog specific product, the test suite uses a couple of git folder data cloned and checked out in different ways, and test the parser using those folders:
https://github.com/DataDog/dd-trace-dotnet/blob/a9582968040b32ca78640d2fe99f5ef0573bf853/test/Datadog.Trace.ClrProfiler.IntegrationTests/CI/GitParserTests.cs#L14-L104

## Possible Solution no 1

1. @tonyredondo in https://github.com/DataDog/dd-trace-dotnet creates a repo with fewer objects and run the test against that repo .git folder.
1. All Datadog devs are pushing their changes before history rewrite
1. @tonyredondo removes  he `GitParserTests`-related BLOBs from the git history
1. All Datadog devs which use https://github.com/DataDog/dd-trace-dotnet as origin should update local repositories. The easier way is to clone it again https://stackoverflow.com/questions/48267025/how-to-sync-local-history-after-massive-git-history-rewrite
1. ⚠️⚠️⚠️ All forks would be affected after this change. 
1. @pellared https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation is not a "normal" fork so we could just first sync (cherry-pick) the changes 
1. @pellared then do the same history-rewrite as mentioned in point 3 but for https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation
1. All OTel devs create new forks of https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation

I am concerned about how this change would impact "normal" forks. IMO it can almost "destroy" them.

## Possible Solution no 2

1. @pellared removes the tests `GitParserTests` from https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation
1. @pellared removes the `GitParserTests`-related BLOBs from the https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation git history
1. All OTel devs create new forks of  https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation

## Plan

Personally, I am concerned about possible side-effects of rewriting https://github.com/DataDog/dd-trace-dotnet for the forks (GitHub sees 66 but I imagine there are more).

That is why I suggest: `Solution no 2`.

## Additional Resources:

- https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History
- https://pajak.home.blog/2019/07/07/git-snippet-cleaning-and-migrating-a-repo/

**Comment by pellared** [comment]
@pjanotti @nrcventura @zacharycmontoya 

Should we go `Solution no 2`?
I would need probably `admin` permissions if it is me who will do that.

**Comment by tonyredondo** [comment]
I prefer solution 2
