### ISSUE TITLE
Hardcoded name of the output file in the code

### ISSUE THREAD

**Issue by dszmigielski** [open-telemetry/opentelemetry-dotnet-instrumentation#87]
**Describe the bug**
There is a hardcoded output file name [here](https://github.com/dszmigielski/opentelemetry-dotnet-instrumentation/blob/a0b44313c7dca6a7655622a95e26350b31087e6c/src/Datadog.Trace.ClrProfiler.Native/cor_profiler.cpp#L2656). It was confirmed that it causes client applications with profiler attached to crash when the .dylib file's name is changed after compilation - see [this](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/84) comment for reference.

**To Reproduce**
1. Install profiler on macOS
2. Rename .dylib file
3. Set new name in CORECLR_PROFILER_PATH
4. Run application
5. Application crashes

**Expected behavior**
I assume name of the profiler file should not affect how it works, and definitely shouldn't crash client apps.

**Screenshots**

**Runtime environment (please complete the following information):**
- Instrumentation mode: Used files compiled on my machine
- OS: macOS Catalina Version 10.15.7 (19H524)
- .NET version: .NET 5

**Comment by pellared** [comment]
### Actual behaviour

The application crashed with

```
Unhandled exception. System.OverflowException: Arithmetic operation resulted in an overflow.
at DDVoidMethodType.DDVoidMethodCall()
at Microsoft.DotNet.Cli.Program.Main(String[] args)
```

**Comment by macrogreg** [comment]
Mac OS related.
@tonyredondo should we tweak this. Can you please advise? :)

**Comment by macrogreg** [comment]
Assigning the tracking item to myself to keep current.

**Comment by Kielek** [comment]
Reference removed in scope of #2216
