### ISSUE TITLE
Refactor Nuke tasks

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-dotnet-instrumentation#889]
The current build implementation using Nuke uses different APIs for defining and ordering dependencies, making it hard to maintain.

We should document and use some guidelines to make it more maintainable.

The proposal is to define two types of tasks:

- **target** which contains logic and use `After` to specify targets that are required to be built before this one is run,
- **workflow** which groups targets (or workflows) using `DependsOn` into a suite.

Slack thread: https://cloud-native.slack.com/archives/C01NR1YLSE7/p1656060079086989

**Comment by pellared** [comment]
The other idea  is to only use `DependsOn` and one could use `--skip` to Skip all other dependencies or some specified ones.

**Comment by Kielek** [comment]
Stale issue. Closing. I do not think that anybody would like to work on this.
