### ISSUE TITLE
Remove support for `OTEL_DOTNET_AUTO_INCLUDE_PROCESSES`

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-dotnet-instrumentation#895]
`ApplicationIsNotIncluded` test asserts the current wrong behavior.
Search for `https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/issues/895` in code.

Looks like a not finished "next step" after https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/275

**Comment by pjanotti** [comment]
@pellared I find a bit confuse to have both include and exclude configs to control this. Just thinking if we should instead just have the exclude option, with an empty default.

**Comment by pellared** [comment]
I removed the milestone so that we discuss it during our next SIG meeting.

**Comment by Kielek** [comment]
SIG meeting: lets remove support for the env. variable.
