### ISSUE TITLE
Add codecov integration

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-dotnet-instrumentation#91]
## Why

Having code coverage reports as part of PRs is going to help during code reviews.
Moreover, the test coverage on the main branch would also tell what code is tested by unit tests (not integration tests).

## What

Integrate with https://about.codecov.io/ like. https://github.com/open-telemetry/opentelemetry-dotnet did it already

**Comment by macrogreg** [comment]
Closing as discussed in the SIG meeting.
