### ISSUE TITLE
A few suggestions to add to the docs

### ISSUE THREAD

**Issue by yesmarket** [open-telemetry/opentelemetry-dotnet-instrumentation#916]
A couple things that would be good to see added to the docs:

1. A minimal example for an (no-code) auto instrumentation pipeline e.g. `Test .NET Core app -> OTEL collector agent -> Elasticsearch` or something similar. I'm trying to build the following pipeline `Test .NET Core app -> OTEL collector agent -> AWS Kinesis -> Logastash -> Elasticsearch` - see [here](https://github.com/yesmarket/otel-kinesis-logstash-elastic), but can't get any trace instrumentation data coming through. A minmal examplar (using OTLP) would be really handy right now - something that I can just fork and run via `docker-compose up`. FWIW have got OTEL pipelines working for filelog and prometheus receivers, but not OTEL auto-instrumentation...

2. How to propagate trace IDs for service-to-service communication? e.g. .NET Core app invoking a Spring Boot Java app.

3. I noticed that OTEL auto-instrumentation docs mention "metrics" in a few places e.g. `OTEL_DOTNET_AUTO_METRICS_ENABLED_INSTRUMENTATIONS`. Is there any cross-over with the OTEL prometheus receiver? Would be good to explain OTEL metrics in comparison to Prometheus metrics (explicitly exposed by apps) and when to use either one...

**Comment by pellared** [comment]
@yesmarket Are my answers helpful? Do you have any more questions?
