### ISSUE TITLE
Add license headers for C# source files

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-dotnet-instrumentation#93]
## Why 

https://github.com/open-telemetry/community/blob/main/CONTRIBUTING.md#code-attribution

## What

1. License information should be included in all source files where applicable.
2. Add a CI check to validate if all (applicable) source files have license information (at least C# and C++ source code)
3. Remove from `src/Datadog.Trace/GlobalSuppressions.cs`:
```
// Copyright claims are suppressed until re-naming is finalized
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1636:File header copyright text must match", Justification = "Reviewed.")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1641:File header company name text must match", Justification = "Reviewed.")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1638:File header file name documentation must match file name", Justification = "Reviewed.")]
```

**Comment by macrogreg** [comment]
Revisit after Beta.
