### ISSUE TITLE
Reorganize constants

### ISSUE THREAD

**Issue by RassK** [open-telemetry/opentelemetry-dotnet-instrumentation#939]
Currently there are lot of loose constants around. Some of them are required to pass down as a parameter not to create code couplings. 
I think we should reorganize constants to a single location similarly as done in `ConfigurationKeys.cs`.

Some examples to fix: `MeterSettings.cs` `TracerSettings.cs` `ConfigurationSourceExtensions.cs`
Some examples of common constants: `,` `;` `:` `none` 

_Issue mentioned by @pellared https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/937#discussion_r921980215_

**Comment by pellared** [comment]
I propose to keep all constant related to env var values in `ConfigurationValues.cs`
