### ISSUE TITLE
Add StackExchange.Redis instrumentation

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-dotnet-instrumentation#947]
Add `StackExchange.Redis` source&bytecode instrumentation using https://github.com/open-telemetry/opentelemetry-dotnet-contrib/tree/main/src/OpenTelemetry.Instrumentation.StackExchangeRedis

**Comment by pjanotti** [comment]
We should add another method to the current package prior we can add it to auto instrumentation: calling `AddRedisInstrumentation(connection)` when setting up the tracer is not a good pattern (not only for automatic instrumentation).

**Comment by pellared** [comment]
I think it can be implemented similarly to MongoDB instrumentation.

1. We can call `AddSource` during initialization.
2. We can apply byte-code instrumentation to reJIT `ConnectionMultiplexer.Connect` methods so that [StackExchangeRedisCallsInstrumentation.cs](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/main/src/OpenTelemetry.Instrumentation.StackExchangeRedis/StackExchangeRedisCallsInstrumentation.cs) is applied for each connection multiplexer instance.
