### ISSUE TITLE
Use OTel SDK's self-diagnostics - managed code - document troubleshooting

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-dotnet-instrumentation#959]
We should use [OTel SDK's self-diagnostics](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry/README.md#self-diagnostics) for internal logging.

**Comment by nrcventura** [comment]
One thing that I do not like about this approach, based on the current functionality in that feature, is that it requires someone to drop a file in a particular location to get the log files generated. The problems that I have seen people experience with that approach are the following.

1. Figuring out which directory to place this special file in
2. Having enough permissions to get a file added to that directory

If we had the ability to control these log files via environment variables, I think that would improve the experience, and simplify things for us and our users.

**Comment by Kielek** [comment]
Only describe in troubleshooting doc how to do it.

**Comment by lachmatt** [comment]
[SdkSelfDiagnosticsEventListener](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/54984087e73407a4b6bac2c8c2b68bbd271d07f1/src/OpenTelemetry.AutoInstrumentation/Diagnostics/SdkSelfDiagnosticsEventListener.cs) fulfills similar purpose.
I think with recent logging improvements to internal logger, this is no longer needed.

**Comment by Kielek** [comment]
Closing per previous comment.
