### ISSUE TITLE
Fix MongoDBTests to handle MongoDB.Driver 2.17.0 

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-dotnet-instrumentation#997]
There were some breaking changes in MongoDB.Driver

See build failures here: https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/955

**Comment by Kielek** [comment]
Changes introduced in MongoDB v 2.15. https://github.com/mongodb/mongo-csharp-driver/pull/698
